[GitHub] Update to 1.1.4-d44d6894d755f6888947b8cdae731dc6 from 1.1.4-5a577f15b770f82145094bef33435130 Detected Schema changes:
├─┬Paths
│ ├──[-] path (10384:3)❌
│ ├──[-] path (10142:3)❌
│ ├──[-] path (10244:3)❌
│ ├──[-] path (31224:3)❌
│ ├─┬/repos/{owner}/{repo}/import/lfs
│ │ └─┬PATCH
│ │   ├──[M] description (27285:20)
│ │   ├──[-] deprecated (27724:19)
│ │   └─┬Extensions
│ │     └──[M] x-github (27340:9)
│ ├─┬/repos/{owner}/{repo}/import
│ │ ├─┬GET
│ │ │ ├──[M] description (26874:20)
│ │ │ ├──[-] deprecated (27293:19)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (26937:9)
│ │ ├─┬PUT
│ │ │ ├──[M] description (26943:20)
│ │ │ ├──[-] deprecated (27379:19)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (27019:9)
│ │ ├─┬DELETE
│ │ │ ├──[M] description (27114:20)
│ │ │ ├──[-] deprecated (27503:19)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (27135:9)
│ │ └─┬PATCH
│ │   ├──[M] description (27025:20)
│ │   ├──[-] deprecated (27472:19)
│ │   └─┬Extensions
│ │     └──[M] x-github (27108:9)
│ ├─┬/repos/{owner}/{repo}/import/authors/{author_id}
│ │ └─┬PATCH
│ │   ├──[M] description (27184:20)
│ │   ├──[-] deprecated (27617:19)
│ │   └─┬Extensions
│ │     └──[M] x-github (27241:9)
│ ├─┬/repos/{owner}/{repo}/import/large_files
│ │ └─┬GET
│ │   ├──[M] description (27248:20)
│ │   ├──[-] deprecated (27658:19)
│ │   └─┬Extensions
│ │     └──[M] x-github (27278:9)
│ └─┬/repos/{owner}/{repo}/import/authors
│   └─┬GET
│     ├──[M] description (27142:20)
│     ├──[-] deprecated (27549:19)
│     └─┬Extensions
│       └──[M] x-github (27177:9)
├─┬repository-ruleset-edited
│ └─┬POST
│   └──[M] summary (57311:16)
├─┬repository-ruleset-deleted
│ └─┬POST
│   └──[M] summary (57245:16)
├─┬repository-ruleset-created
│ └─┬POST
│   └──[M] summary (57179:16)
├──check-run-rerequested
└─┬Components
  ├──[-] parameters (234892:7)❌
  ├──[-] examples (215602:7)❌
  ├──[-] examples (215617:7)❌
  ├──[-] examples (215639:7)❌
  ├──[-] examples (225794:7)❌
  ├──[-] examples (215627:7)❌
  ├──[-] schemas (68975:7)❌
  ├──[-] schemas (68936:7)❌
  └──[-] schemas (68991:7)❌

Date: 10/13/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 9             | 9
paths            | 28            | 4
webhooks         | 3             | 0
❌  13 Breaking changes out of 40
INFO: Modifications: 19
INFO: Removals: 21
INFO: Breaking Removals: 13

ERROR: breaking changes discovered