[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 9b3d5fd88f0342673e16628e57088732) from 1.1.4 (hash: 0048e453b0a490b3a38d05a669c7dac9) Detected Schema changes:
└─┬Paths
  ├─┬/enterprises/{enterprise}/code-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (4950:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/analyses
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22530:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
  │ └─┬POST
  │   ├──[M] description (22864:20)
  │   └─┬External Docs
  │     └──[M] url (22906:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
  │ └─┬GET
  │   ├──[M] description (22982:20)
  │   └─┬External Docs
  │     └──[M] url (22995:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (22783:14)
  │ └─┬PATCH
  │   ├─┬External Docs
  │   │ └──[M] url (22819:14)
  │   └─┬Responses
  │     └─┬200
  │       └─┬application/json
  │         └──[-] examples (22841:19)❌
  ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22473:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (22372:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (22412:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (22613:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (22725:14)
  ├─┬/repos/{owner}/{repo}/code-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22300:14)
  └─┬/orgs/{org}/code-scanning/alerts
    └─┬GET
      └─┬External Docs
        └──[M] url (9909:14)

Date: 07/11/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 16            | 1
❌ 1 Breaking changes out of 16

ERROR: breaking changes discovered