[GitHub] Update to 1.1.4-7d805bd34cdea7b6c0229ab2be120a36 from 1.1.4-70c15d3e8826de45231fa16fc40897e0 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/codespaces/secrets/{secret_name}
│ │ ├─┬PUT
│ │ │ └──[🔀] description (27671:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (27727:20)
│ ├─┬/orgs/{org}/personal-access-tokens
│ │ └─┬GET
│ │   └──[➖] parameters (230483:13)❌
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│ │ └─┬POST
│ │   └──[🔀] description (31013:20)
│ └─┬/orgs/{org}/personal-access-token-requests
│   └─┬GET
│     └──[➖] parameters (230483:13)❌
└─┬Components
  ├──[➖] parameters (230483:7)❌
  └─┬hook-delivery-item
    ├─┬installation_id
    │ └──[➖] format (68932:19)❌
    ├─┬repository_id
    │ └──[➖] format (68940:19)❌
    └─┬id
      └──[➖] format (68879:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 2                |
| components       | 4             | 4                |

Date: 03/12/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _9_
- **Modifications**: _3_
- **Removals**: _6_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered