[GitHubEnterprise-3.5] Update to 1.1.4 (hash: 643981e926f846275908658ca15d377a) from 1.1.4 (hash: 8cab3d8f1254e71d5a97d76fb3cd116a) Detected Schema changes:
└─┬Components
  ├─┬organization-full
  │ └──[-] required (43936:9)❌
  └─┬team-organization
    └──[-] required (45165:9)❌

Date: 07/07/23 | Commit: New: etc/specs/GitHubEnterprise-3.5/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.5/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌ 2 Breaking changes out of 2

ERROR: breaking changes discovered