[GitHubEnterprise-3.8] Update to 1.1.4-23df11f468bf532e9a0153604bba612b from 1.1.4-60bf3351604f2c0c184a950a90e7b58d Detected Schema changes:
├─┬Paths
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (72007:14)❌
├─┬user-deleted
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (56644:9)
├─┬user-created
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (56574:9)
├─┬ping
│ └──POST
└─┬Components
  └──[-] schemas (72007:7)❌

Date: 09/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 1
webhooks         | 2             | 0
components       | 1             | 1
❌  2 Breaking changes out of 4
INFO: Modifications: 3
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered