[GitHub] Update to 1.1.4-c1e4d4617fb30b28dd9ff95dbcd32f2e from 1.1.4-ffc57be6cdf0e66d7c933d6f52367abe Detected Schema changes:
```
└─┬Components
  └─┬code-scanning-default-setup
    ├──[➖] properties (83767:9)❌
    └──[➖] properties (83758:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 2                |

Date: 12/26/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _2_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered