[GitHubEnterprise-3.9] Update to 1.1.4-ca55fee682516827afc096c706b2f986 from 1.1.4-5a96d9af7eabd28e4ec1d95e4848779e Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 2404ec
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           ├──[+] properties (27203:21)
│ │           └──[+] properties (27199:21)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬config
│             └──[M] $ref (27315:19)❌
└─┬Components
  └─┬hook
    └─┬config
      └──[M] $ref (75718:11)❌

Date: 01/13/24 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 1             | 1
paths            | 3             | 1

❌  2 Breaking changes out of 4
INFO: Modifications: 2
INFO: Additions: 2
INFO: Breaking Modifications: 2

ERROR: breaking changes discovered