[GitHubEnterprise-3.9] Update to 1.1.4-93fcb79e417a73083950e021c1a1da31 from 1.1.4-9ad8c815b4579945b036e8094bf35ae2 Detected Schema changes:
└─┬Components
  └─┬code-scanning-default-setup-update
    ├──[-] additionalProperties (72828:29)❌
    └─┬state
      └──[M] description (72817:24)

Date: 11/11/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 1

❌  1 Breaking changes out of 2
INFO: Modifications: 1
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered