[GitHubAE] Update to 1.1.4-4c4e1701d928399d4897fc32d297d17b from 1.1.4-a2da0f53e6e409f85678904ce5808926 Detected Schema changes:
├─┬Paths
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (58795:14)❌
├─┬user-created
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (45394:9)
├──check-run-created
├─┬user-deleted
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (45454:9)
└─┬Components
  └──[-] schemas (58795:7)❌

Date: 09/28/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 1
webhooks         | 2             | 0
components       | 1             | 1
❌  2 Breaking changes out of 4
INFO: Modifications: 3
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered