[GitHub] Update to 1.1.4-d934eed2382f2e3ae89ee32d3f556f88 from 1.1.4-afc6e722cc5a6bed827aa47c96932184 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 1b2cb1
SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [62895:7]
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └──[M] description (16601:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ └─┬PUT
│ │   └──[M] description (29964:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/jobs
│ │ └─┬GET
│ │   └──[M] description (17063:20)
│ ├─┬/teams/{team_id}/members/{username}
│ │ └─┬PUT
│ │   └──[M] description (38824:20)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (39303:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs
│ │ └─┬GET
│ │   └──[M] description (16864:20)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ └─┬PUT
│ │   └──[M] description (23049:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (13665:20)
│ ├─┬/users/{username}
│ │ └─┬GET
│ │   └──[M] description (43899:20)
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (39142:32)
│ ├─┬/user/following/{username}
│ │ └─┬PUT
│ │   └──[M] description (41098:20)
│ ├─┬/gists/{gist_id}/star
│ │ └─┬PUT
│ │   └──[M] description (2340:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └──[M] description (18006:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (13517:32)
│ ├─┬/user/starred/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (43714:20)
│ └─┬/orgs/{org}/public_members/{username}
│   └─┬PUT
│     └──[M] description (11193:20)
└─┬Components
  ├─┬code-scanning-alert-rule-summary
  │ └──[-] properties (68251:9)❌
  └─┬code-scanning-organization-alert-items
    └─┬rule
      └──[M] $ref (68223:13)❌

Date: 12/16/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 16            | 0
components       | 2             | 2

❌  2 Breaking changes out of 18
INFO: Modifications: 17
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered