[GitHub] Update to 1.1.4-3eab7bc09a6d3be61aedace0f4ddc61d from 1.1.4-ed43ce3c2a6bf973841dfa10ad4655d5 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 89dac0
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           ├──[🔀] value (197603:9)
│ │           └──[➖] value (197609:9)
│ └─┬/repos/{owner}/{repo}/pages
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬cname
│             └──[🔀] description (32300:32)
└─┬Components
  └─┬api-overview
    └──[➖] properties (67645:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 15            | 0                |
| components       | 1             | 1                |

Date: 05/09/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _16_
- **Modifications**: _14_
- **Removals**: _2_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered