[GitHub] Update to 1.1.4-27d2025567219eabd469390370e022c1 from 1.1.4-9458c0477f3e10e00654df3219f3506a Detected Schema changes:
```
└─┬Paths
  └─┬/user/emails
    ├─┬POST
    │ └─┬Requestbody
    │   └─┬application/json
    │     └─┬Schema
    │       ├─┬ONEOF
    │       │ ├──[➕] items (43194:19)❌
    │       │ └──[🔀] type (43192:23)❌
    │       ├─┬ONEOF
    │       │ ├──[➖] required (43187:19)❌
    │       │ ├──[🔀] type (43198:23)❌
    │       │ ├──[➖] example (43189:19)
    │       │ └──[➖] properties (43173:19)❌
    │       └─┬ONEOF
    │         ├──[➕] required (43187:19)❌
    │         ├──[➖] items (43194:19)❌
    │         ├──[🔀] type (43171:23)❌
    │         ├──[➖] minItems (43197:27)❌
    │         ├──[➕] example (43189:19)
    │         └──[➕] properties (43173:19)
    └─┬DELETE
      └─┬Requestbody
        └─┬application/json
          └─┬Schema
            ├─┬ONEOF
            │ ├──[➕] items (43273:19)❌
            │ └──[🔀] type (43271:23)❌
            ├─┬ONEOF
            │ ├──[➖] items (43273:19)❌
            │ ├──[🔀] type (43277:23)❌
            │ └──[➖] minItems (43276:27)❌
            └─┬ONEOF
              └─┬emails
                ├──[➖] minItems (43264:31)❌
                └─┬Schema
                  └──[➕] minItems (43262:33)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 19            | 16               |

Date: 09/05/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _16_ out of _19_
- **Modifications**: _5_
- **Removals**: _8_
- **Additions**: _6_
- **Breaking Removals**: _7_
- **Breaking Modifications**: _5_
- **Breaking Additions**: _4_

ERROR: breaking changes discovered