[GitHub] Update to 1.1.4-c956dacd1ed3014e8efb91f1eb6a337d from 1.1.4-12b8dbc76c459480c3e846bc22d32615 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit f9d01d
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├──[➖] path (6351:3)❌
│ ├─┬/orgs/{org}
│ │ ├─┬GET
│ │ │ └──[🔀] description (3791:20)
│ │ └─┬PATCH
│ │   ├──[🔀] description (3839:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├─┬advanced_security_enabled_for_new_repositories
│ │         │ ├──[🔀] description (3987:32)
│ │         │ └──[➖] deprecated (3975:31)
│ │         ├─┬dependabot_alerts_enabled_for_new_repositories
│ │         │ ├──[🔀] description (3995:32)
│ │         │ └──[➖] deprecated (3986:31)
│ │         ├─┬dependabot_security_updates_enabled_for_new_repositories
│ │         │ ├──[🔀] description (4003:32)
│ │         │ └──[➖] deprecated (3997:31)
│ │         ├─┬dependency_graph_enabled_for_new_repositories
│ │         │ ├──[🔀] description (4011:32)
│ │         │ └──[➖] deprecated (4008:31)
│ │         ├─┬secret_scanning_enabled_for_new_repositories
│ │         │ ├──[🔀] description (4019:32)
│ │         │ └──[➖] deprecated (4019:31)
│ │         └─┬secret_scanning_push_protection_enabled_for_new_repositories
│ │           ├──[🔀] description (4027:32)
│ │           └──[➖] deprecated (4030:31)
│ ├─┬/orgs/{org}/code-security/configurations/defaults
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (201398:7)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (201344:7)
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (201380:9)
│ │   │       ├──[🔀] value (201380:9)
│ │   │       ├──[🔀] value (201380:9)
│ │   │       └──[➖] value (201467:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (6278:17)❌
│ ├─┬/repos/{owner}/{repo}/automated-security-fixes
│ │ └─┬GET
│ │   └─┬Responses
│ │     ├─┬200
│ │     │ └──[🔀] description (19712:24)
│ │     └─┬404
│ │       └──[🔀] description (19723:24)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └─┬Extensions
│ │     └──[🔀] x-github (39256:9)
│ └─┬/orgs/{org}/code-security/configurations/{configuration_id}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         ├──[🔀] value (201380:9)
│   │         ├──[🔀] value (201380:9)
│   │         ├──[🔀] value (201380:9)
│   │         └──[➖] value (201467:9)
│   └─┬PATCH
│     ├─┬Responses
│     │ └─┬200
│     │   └─┬application/json
│     │     └─┬default
│     │       ├──[🔀] value (201437:9)
│     │       ├──[🔀] value (201437:9)
│     │       ├──[🔀] value (201437:9)
│     │       └──[➖] value (201527:9)
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (6540:17)❌
└─┬Components
  ├─┬code-security-configuration
  │ └──[➖] properties (71157:9)❌
  └─┬organization-full
    ├─┬advanced_security_enabled_for_new_repositories
    │ ├──[🔀] description (70268:24)
    │ └──[➖] deprecated (70342:23)
    ├─┬dependabot_alerts_enabled_for_new_repositories
    │ ├──[🔀] description (70276:24)
    │ └──[➖] deprecated (70353:23)
    ├─┬dependabot_security_updates_enabled_for_new_repositories
    │ ├──[🔀] description (70285:24)
    │ └──[➖] deprecated (70364:23)
    ├─┬dependency_graph_enabled_for_new_repositories
    │ ├──[🔀] description (70294:24)
    │ └──[➖] deprecated (70375:23)
    ├─┬secret_scanning_enabled_for_new_repositories
    │ ├──[🔀] description (70303:24)
    │ └──[➖] deprecated (70386:23)
    └─┬secret_scanning_push_protection_enabled_for_new_repositories
      ├──[🔀] description (70312:24)
      └──[➖] deprecated (70397:23)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 13            | 1                |
| paths            | 34            | 3                |

Date: 07/15/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _47_
- **Modifications**: _28_
- **Removals**: _19_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered