[GitHubEnterprise-3.8] Update to 1.1.4-61ab1ad544b6e8b98414b22a38b898ae from 1.1.4-49c3c63f136551913beffc8f5d1748ab Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (26253:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (26271:9)
│ │ ├─┬DELETE
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (26378:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (26389:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (26286:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26366:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (26530:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26551:9)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (204459:9)
│ ├─┬/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default-response
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           ├──[M] value (203301:9)
│ │           └──[+] value (203301:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (26619:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26630:9)
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (26116:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (26140:9)
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (26154:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26239:9)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[-] codes (219170:7)❌
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[M] value (213364:9)
│ │ │         ├──[M] value (213364:9)
│ │ │         ├──[M] value (213364:9)
│ │ │         ├──[M] value (213364:9)
│ │ │         ├──[M] value (213364:9)
│ │ │         ├──[+] value (213364:9)
│ │ │         ├──[+] value (213364:9)
│ │ │         ├──[+] value (213364:9)
│ │ │         ├──[+] value (213364:9)
│ │ │         ├──[+] value (213364:9)
│ │ │         └──[+] value (213364:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[M] value (213382:9)
│ │           ├──[+] value (213382:9)
│ │           └──[+] value (213382:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (26592:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26603:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (26488:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26517:9)
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (204459:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-repository-permissions
│ │           ├──[M] value (202840:9)
│ │           ├──[M] value (202840:9)
│ │           ├──[M] value (202840:9)
│ │           ├──[M] value (202840:9)
│ │           ├──[M] value (202840:9)
│ │           ├──[M] value (202840:9)
│ │           ├──[M] value (202840:9)
│ │           └──[+] value (202840:9)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-extra-repository-information
│ │           ├──[M] value (214941:9)
│ │           ├──[M] value (214941:9)
│ │           ├──[M] value (214941:9)
│ │           ├──[M] value (214941:9)
│ │           ├──[M] value (214941:9)
│ │           ├──[M] value (214941:9)
│ │           ├──[M] value (214941:9)
│ │           └──[+] value (214941:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (26405:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (26421:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (26436:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (26474:9)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│   └─┬POST
│     ├─┬External Docs
│     │ └──[M] url (26564:14)
│     └─┬Extensions
│       └──[M] x-github (26578:9)
├─┬pull-request-edited
│ └─┬POST
│   └──[M] description (51166:20)
└─┬Components
  ├─┬webhook-fork
  │ └─┬forkee
  │   └─┬ALLOF
  │     └──[-] properties (92503:15)❌
  ├─┬webhook-issues-opened
  │ └─┬changes
  │   └─┬old_repository
  │     └──[-] properties (107791:17)❌
  ├─┬webhook-team-created
  │ └─┬repository
  │   └──[-] properties (187951:13)❌
  ├─┬team-repository
  │ └──[+] properties (66142:9)
  ├─┬webhook-team-added-to-repository
  │ └─┬repository
  │   └──[-] properties (187364:13)❌
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_repository
  │     └──[-] properties (112135:17)❌
  ├─┬job
  │ └─┬status
  │   └──[-] enum (67260:13)❌
  ├─┬webhook-push
  │ └─┬repository
  │   └──[-] properties (179266:13)❌
  ├─┬webhook-team-removed-from-repository
  │ └─┬repository
  │   └──[-] properties (189771:13)❌
  ├─┬webhook-team-deleted
  │ └─┬repository
  │   └──[-] properties (188539:13)❌
  ├─┬webhook-team-edited
  │ └─┬repository
  │   └──[-] properties (189182:13)❌
  └─┬repository-webhooks
    └──[-] properties (79556:9)❌

Date: 11/06/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 106           | 1
webhooks         | 1             | 0
components       | 12            | 12
❌  13 Breaking changes out of 119
INFO: Modifications: 95
INFO: Removals: 12
INFO: Additions: 12
INFO: Breaking Removals: 12

ERROR: breaking changes discovered