[GitHubEnterprise-3.13] Update to 1.1.4-06fa59f66a2537626b799fec04db81b5 from 1.1.4-50b5f868629d9d1260dbd8cc8a0f7a02 Detected Schema changes:
```
├─┬Paths
│ └─┬/orgs/{org}
│   └─┬GET
│     └──[🔀] description (8433:20)
└─┬Components
  ├──[➖] schemas (75224:7)❌
  └─┬repository-rule-params-required-reviewer-configuration
    ├──[➕] required (75247:9)❌
    ├──[➕] properties (75241:9)
    └──[➖] properties (75257:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 4             | 3                |
| paths            | 1             | 0                |

Date: 02/27/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _5_
- **Modifications**: _1_
- **Removals**: _2_
- **Additions**: _2_
- **Breaking Removals**: _2_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered