[GitHubEnterprise-3.11] Update to 1.1.4-dff2b8597d2311abab3eaa64d211e5a3 from 1.1.4-c256b049ef785356819b2e239c64adbe Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 1e6fbc
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ └─┬/repos/{owner}/{repo}/stats/contributors
│   └─┬GET
│     └──[M] description (36231:20)
└─┬Components
  └─┬repository-ruleset
    └─┬conditions
      └──[-] type (72473:11)❌

Date: 01/10/24 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 0
components       | 1             | 1

❌  1 Breaking changes out of 2
INFO: Modifications: 1
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered