[GitHub] Update to 1.1.4-85662c80b53f38fb1fdf4e581c839168 from 1.1.4-808b83641f5a6cdecf73cd52f50366e7 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/issue-types/{issue_type_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         ├──[🔀] value (11732:19)
│ │         └──[➕] value (11732:19)
│ └─┬/orgs/{org}/issue-types
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬default
│           ├──[🔀] value (11683:19)
│           └──[➕] value (11683:19)
├─┬personal-access-token-request-approved
│ └─┬POST
│   ├──[🔀] summary (59381:16)
│   └─┬Extensions
│     └──[🔀] x-github (59439:9)
├─┬personal-access-token-request-denied
│ └─┬POST
│   ├──[🔀] summary (59577:16)
│   └─┬Extensions
│     └──[🔀] x-github (59635:9)
├─┬personal-access-token-request-cancelled
│ └─┬POST
│   ├──[🔀] summary (59446:16)
│   └─┬Extensions
│     └──[🔀] x-github (59505:9)
├─┬personal-access-token-request-created
│ └─┬POST
│   ├──[🔀] summary (59512:16)
│   └─┬Extensions
│     └──[🔀] x-github (59570:9)
└─┬Components
  ├──[➖] schemas (79913:7)❌
  ├──[➖] schemas (79936:7)❌
  ├──[➖] schemas (79891:7)❌
  ├──[➖] schemas (79868:7)❌
  ├─┬repository-rule-detailed
  │ ├──[➖] oneOf (92369:9)❌
  │ ├──[➖] oneOf (92372:9)❌
  │ ├──[➖] oneOf (92375:9)❌
  │ ├──[➖] oneOf (92378:9)❌
  │ ├─┬ONEOF
  │ │ └─┬ALLOF
  │ │   └──[🔀] $ref (79907:14)❌
  │ └─┬ONEOF
  │   └─┬ALLOF
  │     └──[🔀] $ref (79967:14)❌
  └─┬repository-rule-pull-request
    └─┬parameters
      └─┬allowed_merge_methods
        └─┬Schema
          ├──[➖] enum (79610:19)❌
          ├──[➖] enum (79608:19)❌
          └──[➖] enum (79609:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 0                |
| webhooks         | 8             | 0                |
| components       | 13            | 15               |

Date: 03/19/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _15_ out of _25_
- **Modifications**: _12_
- **Removals**: _11_
- **Additions**: _2_
- **Breaking Removals**: _11_
- **Breaking Modifications**: _2_

ERROR: breaking changes discovered