[GitHubAE] Update to 1.1.4 (hash: cbd87d3c7c7ad8ae59d7c5749c53f099) from 1.1.4 (hash: a4e17c0e4309494e07cadc673434db27) Detected Schema changes:
├──Paths
└─┬Components
  ├──[-] schemas (51498:7)❌
  └─┬code-scanning-alert-state
    └──[+] enum (51502:9)

Date: 06/24/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 0             | 0
components       | 2             | 1
❌ 1 Breaking changes out of 2

ERROR: breaking changes discovered