[GitHubEnterprise-3.6] Update to 1.1.4 (hash: 3e8262cc03476fece95c61c4732d692c) from 1.1.4 (hash: 6295230a678cee6715d7770a105bb1b0) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   ├──[M] summary (23872:16)
│ │   └──[M] description (23873:20)
│ ├─┬/user/starred/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └──[-] description (37937:20)
│ │ └─┬DELETE
│ │   └──[-] description (37998:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21491:22)
│ ├─┬/repos/{owner}/{repo}/git/matching-refs/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (23952:22)
│ ├─┬/repos/{owner}/{repo}/git/ref/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (23995:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21536:22)
│ ├─┬/repos/{owner}/{repo}/subscription
│ │ └─┬GET
│ │   └──[-] description (31618:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/statuses
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21715:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/status
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (21673:22)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └─┬GET
│ │   └──[M] description (20843:20)
│ ├─┬/repos/{owner}/{repo}/git/refs/{ref}
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (24154:22)
│ └─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│   └─┬GET
│     └─┬Parameters
│       └──[M] description (21607:22)
└─┬Components
  └──[-] parameters (81045:7)❌

Date: 06/14/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 14            | 0
components       | 1             | 1
❌ 1 Breaking changes out of 15

ERROR: breaking changes discovered