[GitHubEnterprise-3.15] Update to 1.1.4-304084ef72c17bb8078ef873b8a1f8e0 from 1.1.4-65326b80112b8870ab78f284d1043862 Detected Schema changes:
```
├─┬Paths
│ └─┬/orgs/{org}/memberships/{username}
│   └─┬PUT
│     └──[🔀] description (13700:20)
└─┬Components
  └─┬integration
    └─┬owner
      ├──[➖] oneOf (68097:7)❌
      ├──[➖] oneOf (67115:7)❌
      ├──[➕] anyOf (68127:13)
      └──[➕] anyOf (67116:7)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 4             | 2                |

Date: 01/17/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _5_
- **Modifications**: _1_
- **Removals**: _2_
- **Additions**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered