[GitHubEnterprise-3.13] Update to 1.1.4-21328c477fcf59892ec22f32ff4cf8b7 from 1.1.4-5345cfceb2528e8e91c8d7a675d048be Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│   └─┬POST
│     └─┬Extensions
│       └──[🔀] x-github (33071:9)
└─┬Components
  └─┬announcement
    └──[➖] properties (68190:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 1             | 1                |

Date: 02/12/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _2_
- **Modifications**: _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered