[GitHub] Update to 1.1.4-d8074bd9e0c6a1faac9d78d77016fd5e from 1.1.4-b1232502b094b2cf854385b7323bd958 Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/actions/runs/{run_id}/rerun
│   └─┬POST
│     └─┬Extensions
│       └──[🔀] x-github (21327:9)
└─┬Components
  ├─┬copilot-dotcom-pull-requests
  │ └─┬repositories
  │   └─┬Schema
  │     └─┬models
  │       └─┬Schema
  │         └─┬name
  │           └──[🔀] description (76359:36)
  ├─┬repository-rule
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (78730:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (79044:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (79273:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (79078:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (79316:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (78843:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (78760:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (79213:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (78771:14)❌
  │ └─┬ONEOF
  │   └──[🔀] $ref (79381:9)❌
  ├─┬copilot-ide-chat
  │ └─┬editors
  │   └─┬Schema
  │     └─┬models
  │       └─┬Schema
  │         └─┬name
  │           └──[🔀] description (76261:36)
  └─┬copilot-dotcom-chat
    └─┬models
      └─┬Schema
        └─┬name
          └──[🔀] description (76308:30)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 13            | 10               |

Date: 02/07/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _10_ out of _14_
- **Modifications**: _14_
- **Breaking Modifications**: _10_

ERROR: breaking changes discovered