[GitHub] Update to 1.1.4-ffc57be6cdf0e66d7c933d6f52367abe from 1.1.4-ee410229436a838f44c982a4ed9c9572 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (13143:3)❌
│ ├──[➖] path (13311:3)❌
│ └──[➖] path (13363:3)❌
└─┬Components
  ├──[➖] examples (208903:7)❌
  ├──[➖] examples (208892:7)❌
  ├──[➖] examples (208884:7)❌
  ├──[➖] examples (208874:7)❌
  ├──[➖] schemas (76442:7)❌
  ├──[➖] schemas (76484:7)❌
  ├─┬code-scanning-default-setup
  │ └─┬languages
  │   └─┬Schema
  │     └──[➖] enum (83747:15)❌
  └─┬code-scanning-default-setup-update
    └─┬languages
      └─┬Schema
        └──[➖] enum (83815:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 8             | 8                |
| paths            | 3             | 3                |

Date: 12/19/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _11_ out of _11_
- **Removals**: _11_
- **Breaking Removals**: _11_

ERROR: breaking changes discovered