[GitHubEnterprise-3.15] Update to 1.1.4-f49df43e53599bd6cc78c90ef4e8511d from 1.1.4-461f97fcd984db4523b5ea3d4c13bdc9 Detected Schema changes:
```
└─┬Components
  ├─┬code-scanning-default-setup-update
  │ └─┬languages
  │   └─┬Schema
  │     └──[➖] enum (82476:15)❌
  └─┬code-scanning-default-setup
    └─┬languages
      └─┬Schema
        └──[➖] enum (82421:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 2                |

Date: 12/20/24 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _2_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered