[GitHubEnterprise-3.14] Update to 1.1.4-b1c711111d09784b5c8eea125320b49b from 1.1.4-bfa60ec3e74b1fce4fd15feaad5f7d6c Detected Schema changes:
```
└─┬Components
  ├──[➖] schemas (92023:7)❌
  ├──[➖] schemas (92074:7)❌
  └─┬exemption-request
    ├─┬exemption_request_data
    │ └──[➖] oneOf (92023:7)❌
    ├─┬request_type
    │ └──[➖] enum (92149:13)❌
    └─┬metadata
      ├──[➖] anyOf (92043:7)❌
      ├──[➖] anyOf (92058:7)❌
      ├──[➖] anyOf (92074:7)❌
      ├──[➕] oneOf (92023:7)
      └──[➕] oneOf (92038:7)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 9             | 7                |

Date: 03/13/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _7_ out of _9_
- **Removals**: _7_
- **Additions**: _2_
- **Breaking Removals**: _7_

ERROR: breaking changes discovered