[GitHub] Update to 1.1.4-49e6f9eda2f9b53adb152deaeefd9f73 from 1.1.4-90291aa8f69083a3b160c871835515fc Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit a4d79f
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/contents/{path}
│   └─┬GET
│     └─┬Responses
│       └──[➖] codes (220927:7)❌
└─┬Components
  └─┬secret-scanning-alert-webhook
    └──[➖] properties (97513:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 1                |
| components       | 1             | 1                |

Date: 06/11/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _2_
- **Removals**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered