[GitHub] Update to 1.1.4-a5d0ef223e8ea4b0fd40cfba849d6268 from 1.1.4-1286a2730d7f8da9f91dca4d989b2f56 Detected Schema changes:
```
├─┬Paths
│ └─┬/assignments/{assignment_id}/accepted_assignments
│   └─┬GET
│     └──[🔀] operationId (1197:20)❌
└─┬Components
  └─┬webhook-pull-request-dequeued
    └─┬reason
      ├──[➖] enum (141322:13)❌
      ├──[➖] enum (141323:13)❌
      ├──[➖] enum (141319:13)❌
      ├──[➖] enum (141321:13)❌
      ├──[➖] enum (141314:13)❌
      ├──[➖] enum (141315:13)❌
      ├──[➖] enum (141316:13)❌
      ├──[➖] enum (141317:13)❌
      ├──[➖] enum (141318:13)❌
      ├──[➖] enum (141320:13)❌
      ├──[➖] enum (141312:13)❌
      └──[➖] enum (141313:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 1                |
| components       | 12            | 12               |

Date: 09/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _13_ out of _13_
- **Modifications**: _1_
- **Removals**: _12_
- **Breaking Removals**: _12_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered