[GitHub] Update to 1.1.4-ce91e6978e30e8f90bf45dbfcabf7a73 from 1.1.4-b1dedbe8ed382d28f27f8d1f392b8762 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └──[M] description (24955:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (24987:20)
│ │ └─┬DELETE
│ │   └──[M] description (25029:20)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     ├──[M] description (24901:20)
│     ├─┬Responses
│     │ └─┬200
│     │   └─┬application/json
│     │     └──[-] examples (223184:7)❌
│     └─┬Requestbody
│       └─┬application/json
│         ├──[-] examples (24932:17)❌
│         └─┬example-single-branch
│           └──[-] value (24929:19)
└─┬Components
  ├──[-] examples (223184:7)❌
  ├─┬deployment-branch-policy
  │ ├──[M] description (77237:20)
  │ ├──[-] properties (77264:9)❌
  │ ├─┬id
  │ │ └──[M] description (77241:24)
  │ └─┬name
  │   └──[M] description (77250:24)
  ├─┬deployment-branch-policy-name-pattern-with-type
  │ ├──[M] title (77256:14)
  │ ├──[-] properties (77285:9)❌
  │ └─┬name
  │   └──[M] description (77260:24)
  ├─┬code-scanning-codeql-database
  │ └─┬commit_oid
  │   └──[M] description (74669:24)
  └─┬repository-ruleset-bypass-actor
    └─┬actor_id
      └──[M] description (68530:24)

Date: 10/10/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 7             | 2
components       | 10            | 3
❌  5 Breaking changes out of 17
INFO: Modifications: 11
INFO: Removals: 6
INFO: Breaking Removals: 5

ERROR: breaking changes discovered