[GitHubEnterprise-3.9] Update to 1.1.4-62ea669619da72a8d1d18c55da7c930c from 1.1.4-f42c44cfeb1393d6f9230ebb01f15184 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (223511:20)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (75147:14)❌
├─┬user-deleted
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (59140:9)
├─┬user-created
│ └─┬POST
│   └─┬Extensions
│     └──[M] x-github (59070:9)
└─┬Components
  └──[-] schemas (75147:7)❌

Date: 09/28/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 2             | 1
webhooks         | 2             | 0
components       | 1             | 1
❌  2 Breaking changes out of 5
INFO: Modifications: 4
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered