[GitHubAE] Update to 1.1.4-e5bec81388da5f745e268877188ddc15 from 1.1.4-c6744147e855e41e495357d212c83466 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 0e7cef                                                                                 SPEC: extracted 2 commits from history                                                                                 DONE: completed
WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [47722:7]

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/check-suites/preferences
│ │ └─┬PATCH
│ │   └──[M] description (15962:20)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
│ │ └─┬GET
│ │   └──[M] description (16027:20)
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}
│ │ └─┬GET
│ │   ├──[M] description (26448:20)
│ │   └─┬Responses
│ │     └─┬200
│ │       └──[M] description (26462:24)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
│ │ ├─┬GET
│ │ │ └──[M] description (15524:20)
│ │ └─┬PATCH
│ │   └──[M] description (15555:20)
│ ├─┬/repos/{owner}/{repo}/check-suites
│ │ └─┬POST
│ │   └──[M] description (15906:20)
│ ├─┬/feeds
│ │ └─┬GET
│ │   └──[M] description (3242:20)
│ ├─┬/repos/{owner}/{repo}/check-runs
│ │ └─┬POST
│ │   └──[M] description (15222:20)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
│ │ └─┬GET
│ │   └──[M] description (15817:20)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
│ │ └─┬POST
│ │   └──[M] description (16119:20)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
│ │ └─┬POST
│ │   └──[M] description (15857:20)
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/assets
│ │ └─┬POST
│ │   └──[M] description (26604:20)
│ ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
│ │ └─┬GET
│ │   └──[M] description (16059:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│ │ └─┬GET
│ │   └──[M] description (17833:20)
│ ├─┬/notifications/threads/{thread_id}
│ │ └──[-] delete (4761:7)❌
│ └─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│   └─┬GET
│     └──[M] description (17766:20)
└─┬Components
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_repository
  │     └──[+] properties (98660:17)
  ├─┬webhook-team-added-to-repository
  │ └─┬repository
  │   └──[+] properties (172620:13)
  ├─┬repository-webhooks
  │ └──[+] properties (65803:9)
  ├─┬webhook-team-deleted
  │ └─┬repository
  │   └──[+] properties (173825:13)
  ├─┬webhook-team-edited
  │ └─┬repository
  │   └──[+] properties (174492:13)
  ├─┬webhook-issues-opened
  │ └─┬changes
  │   └─┬old_repository
  │     └──[+] properties (94316:17)
  ├─┬webhook-push
  │ └─┬repository
  │   └──[+] properties (165725:13)
  ├─┬webhook-team-created
  │ └─┬repository
  │   └──[+] properties (173222:13)
  └─┬webhook-team-removed-from-repository
    └─┬repository
      └──[+] properties (175096:13)

Date: 12/20/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 17            | 1
components       | 9             | 0

❌  1 Breaking changes out of 26
INFO: Modifications: 16
INFO: Removals: 1
INFO: Additions: 9
INFO: Breaking Removals: 1

ERROR: breaking changes discovered