[GitHubEnterprise-3.10] Update to 1.1.4-7366cedae96851b8b60702dce4a27ae9 from 1.1.4-84d59b3b8ef8925925736276b817dfe3 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit f93bcb
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/markdown/raw
│ │ └─┬POST
│ │   └──Requestbody
│ ├─┬/users/{username}/repos
│ │ └─┬GET
│ │   └──[M] description (43852:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └──[M] description (13595:20)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (219441:7)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └──[M] description (36083:20)
│ └─┬/user/repos
│   └─┬POST
│     └──[M] description (42011:20)
└─┬Components
  ├──[-] schemas (81617:7)❌
  ├──[-] schemas (81631:7)❌
  ├──[-] schemas (81589:7)❌
  ├──[-] schemas (81603:7)❌
  ├──[-] schemas (81661:7)❌
  ├──[-] schemas (81563:7)❌
  ├──[-] schemas (81646:7)❌
  ├──[-] schemas (81576:7)❌
  ├─┬secret-scanning-location
  │ ├─┬type
  │ │ ├──[-] enum (81685:13)❌
  │ │ ├──[-] enum (81688:13)❌
  │ │ ├──[-] enum (81691:13)❌
  │ │ ├──[-] enum (81686:13)❌
  │ │ ├──[-] enum (81687:13)❌
  │ │ ├──[-] enum (81689:13)❌
  │ │ ├──[-] enum (81690:13)❌
  │ │ ├──[-] enum (81692:13)❌
  │ │ └──[M] description (81567:24)
  │ └─┬details
  │   ├──[-] oneOf (81646:7)❌
  │   ├──[-] oneOf (81474:7)❌
  │   ├──[-] oneOf (81550:7)❌
  │   ├──[-] oneOf (81576:7)❌
  │   ├──[-] oneOf (81524:7)❌
  │   ├──[-] oneOf (81617:7)❌
  │   ├──[-] oneOf (81631:7)❌
  │   ├──[-] oneOf (81589:7)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (81532:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (81469:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (81545:20)❌
  │   └─┬ONEOF
  │     └──[M] $ref (81519:20)❌
  ├─┬api-overview
  │ └─┬domains
  │   └──[-] properties (67556:13)❌
  ├─┬minimal-repository
  │ └─┬size
  │   └──[M] description (67830:24)
  ├─┬repository
  │ └─┬size
  │   └──[M] description (63501:24)
  ├─┬full-repository
  │ └─┬size
  │   └──[M] description (69873:24)
  └─┬repository-webhooks
    └─┬size
      └──[M] description (84573:24)

Date: 12/02/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 0
components       | 34            | 29

❌  29 Breaking changes out of 39
INFO: Modifications: 14
INFO: Removals: 25
INFO: Breaking Removals: 25
INFO: Breaking Modifications: 4

ERROR: breaking changes discovered