[GitHub] Update to 1.1.4-82b1087a8dddd5516c99b2197699c7e0 from 1.1.4-4bfe6378be3ffa1aed95dac111e07ebb Detected Schema changes:
```
├──[➖] webhooks (52958:5)❌
└─┬Components
  ├──[➖] schemas (109675:7)❌
  └─┬repository-rule-pull-request
    └─┬parameters
      └──[➖] properties (79691:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 2                |

Date: 03/24/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _2_ out of _2_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered