[GitHubEnterprise-3.8] Update to 1.1.4 (hash: 64934f5a0b4d81fb1ac771afce68c358current=a150d802e65a9c59e61343becc4b268e) from 1.1.4 (hash: ) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (24531:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[-] codes (216908:7)❌
│ ├─┬/repos/{owner}/{repo}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (29258:20)
│ │ └─┬POST
│ │   └──[-] description (29294:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (18194:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (28546:20)
│ │ ├─┬POST
│ │ │ └──[-] description (28587:20)
│ │ └─┬DELETE
│ │   └──[-] description (28767:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
│ │ ├─┬GET
│ │ │ └──[-] description (29845:20)
│ │ └─┬DELETE
│ │   └──[-] description (29935:20)
│ ├─┬/users/{username}/projects
│ │ └─┬GET
│ │   └──[-] description (41388:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (9266:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ ├─┬GET
│ │ │ └──[-] description (12441:20)
│ │ └─┬DELETE
│ │   └──[-] description (12488:20)
│ ├─┬/user/memberships/orgs
│ │ └─┬GET
│ │   └──[-] description (39538:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (34810:20)
│ ├─┬/projects/columns/{column_id}/cards
│ │ └─┬GET
│ │   └──[-] description (14998:20)
│ ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
│ │ └─┬GET
│ │   └──[-] description (28035:20)
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └─┬GET
│ │   ├──[-] description (34332:20)
│ │   └─┬Responses
│ │     └──[-] codes (216896:7)❌
│ ├─┬/projects/columns/{column_id}
│ │ ├─┬GET
│ │ │ └──[-] description (14887:20)
│ │ └─┬DELETE
│ │   └──[-] description (14972:20)
│ ├─┬/projects/{project_id}/columns
│ │ ├─┬GET
│ │ │ └──[-] description (15575:20)
│ │ └─┬POST
│ │   └──[-] description (15614:20)
│ ├─┬/repos/{owner}/{repo}/labels/{name}
│ │ ├─┬GET
│ │ │ └──[-] description (29363:20)
│ │ ├─┬DELETE
│ │ │ └──[-] description (29457:20)
│ │ └─┬PATCH
│ │   └──[-] description (29397:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
│ │ └─┬GET
│ │   └──[-] description (29070:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
│ │ └─┬GET
│ │   └──[-] description (28508:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
│ │ └─┬GET
│ │   └──[-] description (29959:20)
│ ├─┬/user/memberships/orgs/{org}
│ │ ├─┬GET
│ │ │ └──[-] description (39589:20)
│ │ └─┬PATCH
│ │   └──[-] description (39623:20)
│ ├─┬/repos/{owner}/{repo}/milestones
│ │ ├─┬GET
│ │ │ └──[-] description (29707:20)
│ │ └─┬POST
│ │   └──[-] description (29774:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ ├─┬GET
│ │ │ └──[-] description (14642:20)
│ │ └─┬DELETE
│ │   └──[-] description (14736:20)
│ ├─┬/repos/{owner}/{repo}/issues/events
│ │ └─┬GET
│ │   └──[-] description (27998:20)
│ └─┬/orgs/{org}/dependabot/secrets/{secret_name}
│   └─┬PUT
│     └──[M] description (10360:20)
└─┬Components
  └─┬api-overview
    └──[-] properties (63766:9)❌

Date: 06/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 38            | 2
components       | 1             | 1
❌ 3 Breaking changes out of 39

ERROR: breaking changes discovered