[GitHub] Update to 1.1.4-808b83641f5a6cdecf73cd52f50366e7 from 1.1.4-6b88df041143c890905098eb26e5a9a4 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (11629:3)❌
│ ├──[➖] path (11707:3)❌
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[➖] parameters (11836:15)❌
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[➖] parameters (34157:15)❌
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (34305:17)❌
│ ├─┬/orgs/{org}/properties/schema
│ │ └─┬PATCH
│ │   └──[🔀] description (14275:20)
│ └─┬/repos/{owner}/{repo}/issues/{issue_number}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (34921:17)❌
└─┬Components
  ├──[➖] parameters (230724:7)❌
  ├──[➖] examples (210107:7)❌
  ├──[➖] examples (210121:7)❌
  ├──[➖] schemas (77517:7)❌
  ├──[➖] schemas (72410:7)❌
  ├──[➖] schemas (77554:7)❌
  ├─┬webhook-issues-unlocked
  │ └─┬issue
  │   └──[➖] properties (133061:13)❌
  ├─┬custom-property-set-payload
  │ └──[➖] properties (78576:9)❌
  ├─┬webhook-issues-locked
  │ └─┬issue
  │   └──[➖] properties (126247:13)❌
  ├─┬webhook-issues-closed
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (121232:15)❌
  ├─┬issue-search-result-item
  │ └──[➖] properties (93834:9)❌
  ├─┬webhook-issue-comment-deleted
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (118767:15)❌
  ├─┬webhook-issues-reopened
  │ └─┬issue
  │   └──[➖] properties (130671:13)❌
  ├─┬webhook-issue-comment-edited
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (119987:15)❌
  ├─┬webhooks_issue_2
  │ └──[➖] properties (99910:9)❌
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_issue
  │     └──[➖] properties (131531:17)❌
  ├─┬webhook-issues-milestoned
  │ └─┬issue
  │   └──[➖] properties (127212:13)❌
  ├─┬webhook-issues-demilestoned
  │ └─┬issue
  │   └──[➖] properties (123321:13)❌
  ├─┬issue
  │ └──[➖] properties (72710:9)❌
  ├─┬webhook-issues-labeled
  │ └─┬issue
  │   └──[➖] properties (125254:13)❌
  ├─┬app-permissions
  │ └─┬dependabot_secrets
  │   └──[🔀] description (69237:24)
  ├─┬webhook-issue-comment-created
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (117554:15)❌
  ├─┬webhooks_issue
  │ └──[➖] properties (98828:9)❌
  ├─┬webhook-issues-deleted
  │ └─┬issue
  │   └──[➖] properties (122336:13)❌
  ├─┬webhook-issues-opened
  │ └─┬issue
  │   └──[➖] properties (129578:13)❌
  └─┬webhook-issues-edited
    └─┬issue
      └──[➖] properties (124285:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 7             | 6                |
| components       | 26            | 29               |

Date: 03/18/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _35_ out of _33_
- **Modifications**: _2_
- **Removals**: _31_
- **Breaking Removals**: _31_

ERROR: breaking changes discovered