[GitHub] Update to 1.1.4-7147a5168a72455e5f4fcbbf004aee1b from 1.1.4-ba2ca3d90a48285fabb706f923b03b78 Detected Schema changes:
```
├─┬Paths
│ ├─┬/projects/columns/cards/{card_id}
│ │ ├─┬GET
│ │ │ ├──[🔀] description (17668:20)
│ │ │ ├──[➖] deprecated (17713:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (17696:9)
│ │ ├─┬DELETE
│ │ │ ├──[🔀] description (17762:20)
│ │ │ ├──[➖] deprecated (17825:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (17796:9)
│ │ └─┬PATCH
│ │   ├──[➖] description (17716:20)
│ │   ├──[➖] deprecated (17779:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (17756:9)
│ ├─┬/repos/{owner}/{repo}/projects
│ │ ├─┬GET
│ │ │ ├──[🔀] description (37178:20)
│ │ │ ├──[➖] deprecated (37346:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (37230:9)
│ │ └─┬POST
│ │   ├──[🔀] description (37236:20)
│ │   ├──[➖] deprecated (37409:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (37290:9)
│ ├─┬/projects/columns/{column_id}/cards
│ │ ├─┬GET
│ │ │ ├──[🔀] description (18024:20)
│ │ │ ├──[➖] deprecated (18127:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (18068:9)
│ │ └─┬POST
│ │   ├──[➖] description (18130:20)
│ │   ├──[➖] deprecated (18233:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18168:9)
│ ├─┬/users/{username}/projects
│ │ └─┬GET
│ │   ├──[🔀] description (50306:20)
│ │   ├──[➖] deprecated (50474:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (50346:9)
│ ├─┬/projects/columns/{column_id}
│ │ ├─┬GET
│ │ │ ├──[🔀] description (17913:20)
│ │ │ ├──[➖] deprecated (17982:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (17941:9)
│ │ ├─┬DELETE
│ │ │ ├──[🔀] description (17998:20)
│ │ │ ├──[➖] deprecated (18070:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (18017:9)
│ │ └─┬PATCH
│ │   ├──[➖] description (17985:20)
│ │   ├──[➖] deprecated (18039:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (17992:9)
│ ├─┬/projects/{project_id}/collaborators/{username}
│ │ ├─┬PUT
│ │ │ ├──[🔀] description (18473:20)
│ │ │ ├──[➖] deprecated (18612:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (18522:9)
│ │ └─┬DELETE
│ │   ├──[🔀] description (18528:20)
│ │   ├──[➖] deprecated (18648:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18553:9)
│ ├─┬/orgs/{org}/projects
│ │ ├─┬GET
│ │ │ ├──[🔀] description (14026:20)
│ │ │ ├──[➖] deprecated (14077:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (14069:9)
│ │ └─┬POST
│ │   ├──[🔀] description (14075:20)
│ │   ├──[➖] deprecated (14139:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (14128:9)
│ ├─┬/projects/{project_id}/collaborators/{username}/permission
│ │ └─┬GET
│ │   ├──[🔀] description (18560:20)
│ │   ├──[➖] deprecated (18692:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18594:9)
│ ├─┬/projects/{project_id}/collaborators
│ │ └─┬GET
│ │   ├──[🔀] description (18409:20)
│ │   ├──[➖] deprecated (18551:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18466:9)
│ ├─┬/projects/{project_id}/columns
│ │ ├─┬GET
│ │ │ ├──[🔀] description (18601:20)
│ │ │ ├──[➖] deprecated (18738:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (18634:9)
│ │ └─┬POST
│ │   ├──[🔀] description (18640:20)
│ │   ├──[➖] deprecated (18804:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18694:9)
│ ├─┬/user/projects
│ │ └─┬POST
│ │   ├──[🔀] description (48240:20)
│ │   ├──[➖] deprecated (48419:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (48297:9)
│ ├─┬/projects/{project_id}
│ │ ├─┬GET
│ │ │ ├──[🔀] description (18234:20)
│ │ │ ├──[➖] deprecated (18337:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (18262:9)
│ │ ├─┬DELETE
│ │ │ ├──[🔀] description (18365:20)
│ │ │ ├──[➖] deprecated (18486:19)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (18402:9)
│ │ └─┬PATCH
│ │   ├──[🔀] description (18268:20)
│ │   ├──[➖] deprecated (18438:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18359:9)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] required (6890:17)❌
│ │         └──[➖] required (6891:17)❌
│ ├─┬/projects/columns/{column_id}/moves
│ │ └─┬POST
│ │   ├──[➖] description (18237:20)
│ │   ├──[➖] deprecated (18298:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (18227:9)
│ ├─┬/projects/columns/cards/{card_id}/moves
│ │ └─┬POST
│ │   ├──[➖] description (17829:20)
│ │   ├──[➖] deprecated (17941:19)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (17906:9)
│ └─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[➖] required (21564:17)❌
│           └──[➖] required (21565:17)❌
└─┬Components
  ├─┬webhook-status
  │ └─┬commit
  │   └─┬commit
  │     └─┬verification
  │       └──[➖] required (195207:21)❌
  ├─┬git-commit
  │ └─┬verification
  │   └──[➖] required (87936:13)❌
  ├─┬verification
  │ └──[➖] required (83438:9)❌
  └─┬timeline-committed-event
    └─┬verification
      └──[➖] required (89624:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 79            | 4                |
| components       | 4             | 4                |

Date: 01/30/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _8_ out of _83_
- **Modifications**: _45_
- **Removals**: _38_
- **Breaking Removals**: _8_

ERROR: breaking changes discovered