[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 52493f43afda358633e59af7e5d1f81d) from 1.1.4 (hash: 4a9d3a6848fedb4280953ce81c421340) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/status
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (24656:22)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   ├──[M] summary (27154:16)
│ │   └──[M] description (27155:20)
│ ├─┬/repos/{owner}/{repo}/git/ref/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (27277:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (24519:22)
│ ├─┬/user/starred/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └──[-] description (42276:20)
│ │ └─┬DELETE
│ │   └──[-] description (42337:20)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └─┬GET
│ │   └──[M] description (23826:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (24474:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/statuses
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (24698:22)
│ ├─┬/repos/{owner}/{repo}/git/refs/{ref}
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (27436:22)
│ ├─┬/repos/{owner}/{repo}/subscription
│ │ └─┬GET
│ │   └──[-] description (35018:20)
│ ├─┬/repos/{owner}/{repo}/git/matching-refs/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (27234:22)
│ └─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│   └─┬GET
│     └─┬Parameters
│       └──[M] description (24590:22)
└─┬Components
  └──[-] parameters (220671:7)❌

Date: 06/14/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 14            | 0
components       | 1             | 1
❌ 1 Breaking changes out of 15

ERROR: breaking changes discovered