[GitHubEnterprise-3.8] Update to 1.1.4-a1241ea3fca69989bd1d1d65cb92e637 from 1.1.4-73eca07963c2ba713c2efb7d158bfed3 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 8295fe
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

└─┬Paths
  └─┬/repos/{owner}/{repo}/autolinks
    └─┬GET
      ├──[+] parameters (218268:13)❌
      ├──[M] summary (18293:16)
      ├──[M] description (18294:20)
      └─┬External Docs
        └──[M] url (18303:14)

Date: 02/02/24 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 1

❌  1 Breaking changes out of 4
INFO: Modifications: 3
INFO: Additions: 1
INFO: Breaking Additions: 1

ERROR: breaking changes discovered