[GitHubEnterprise-3.13] Update to 1.1.4-846745eeb2646f15a6b0f4da036bfed8 from 1.1.4-09460ffde7c51e6470752d5d41c06e16 Detected Schema changes:
```
├─┬personal-access-token-request-cancelled
│ └─┬POST
│   ├──[🔀] summary (55842:16)
│   └─┬Extensions
│     └──[🔀] x-github (55901:9)
├─┬personal-access-token-request-approved
│ └─┬POST
│   ├──[🔀] summary (55777:16)
│   └─┬Extensions
│     └──[🔀] x-github (55835:9)
├─┬personal-access-token-request-created
│ └─┬POST
│   ├──[🔀] summary (55908:16)
│   └─┬Extensions
│     └──[🔀] x-github (55966:9)
├─┬personal-access-token-request-denied
│ └─┬POST
│   ├──[🔀] summary (55973:16)
│   └─┬Extensions
│     └──[🔀] x-github (56031:9)
└─┬Components
  └─┬repository-rule-pull-request
    └─┬parameters
      └─┬allowed_merge_methods
        └─┬Schema
          ├──[➖] enum (75385:19)❌
          ├──[➖] enum (75386:19)❌
          └──[➖] enum (75387:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| webhooks         | 8             | 0                |
| components       | 3             | 3                |

Date: 03/20/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _11_
- **Modifications**: _8_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered