[GitHub] Update to 1.1.4-258d33610c11c1d10d29617d894e1ce8 from 1.1.4-1f428455b4cea06755dbb12f469fc171 Detected Schema changes:
```
├─┬Paths
│ ├─┬/networks/{owner}/{repo}/events
│ │ └─┬GET
│ │   └──[➖] description (3372:20)
│ ├─┬/users/{username}/received_events
│ │ └─┬GET
│ │   └──[🔀] description (46830:20)
│ ├─┬/events
│ │ └─┬GET
│ │   └──[🔀] description (1680:20)
│ ├─┬/users/{username}/received_events/public
│ │ └─┬GET
│ │   └──[➖] description (46878:20)
│ ├─┬/users/{username}/events/public
│ │ └─┬GET
│ │   └──[➖] description (46128:20)
│ ├─┬/users/{username}/events
│ │ └─┬GET
│ │   └──[🔀] description (46053:20)
│ ├─┬/users/{username}/events/orgs/{org}
│ │ └─┬GET
│ │   └──[🔀] description (46085:20)
│ └─┬/orgs/{org}/events
│   └─┬GET
│     └──[➖] description (8426:20)
└─┬Components
  └─┬pull-request-review
    └─┬id
      └──[➖] format (86490:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 0                |
| components       | 1             | 1                |

Date: 08/02/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _1_ out of _9_
- **Modifications**: _4_
- **Removals**: _5_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered