[GitHubEnterprise-3.6] Update to 1.1.4-8011f62bad53ba17465a0849d778d468 from 1.1.4-35a83436c6502d98ede06021b93592b9 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (24766:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24777:9)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-extra-repository-information
│ │           ├──[M] value (78300:9)
│ │           ├──[M] value (78300:9)
│ │           ├──[M] value (78300:9)
│ │           ├──[M] value (78300:9)
│ │           ├──[M] value (78300:9)
│ │           ├──[M] value (78300:9)
│ │           ├──[M] value (78300:9)
│ │           └──[+] value (78300:9)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[-] codes (80750:7)❌
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (24579:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (24595:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (24610:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24648:9)
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (24290:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (24314:9)
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (24328:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24413:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-repository-permissions
│ │           ├──[M] value (66638:9)
│ │           ├──[M] value (66638:9)
│ │           ├──[M] value (66638:9)
│ │           ├──[M] value (66638:9)
│ │           ├──[M] value (66638:9)
│ │           ├──[M] value (66638:9)
│ │           ├──[M] value (66638:9)
│ │           └──[+] value (66638:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (24793:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24804:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (24662:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24691:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (24427:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (24445:9)
│ │ ├─┬DELETE
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (24552:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (24563:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (24460:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24540:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (24738:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24752:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (24704:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (24725:9)
│ └─┬/repos/{owner}/{repo}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default-response
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             ├──[M] value (67099:9)
│             └──[+] value (67099:9)
└─┬Components
  ├─┬job
  │ └─┬status
  │   └──[-] enum (48105:13)❌
  └─┬team-repository
    └──[+] properties (47041:9)

Date: 11/06/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 82            | 1
components       | 2             | 1
❌  2 Breaking changes out of 84
INFO: Modifications: 78
INFO: Removals: 2
INFO: Additions: 4
INFO: Breaking Removals: 2

ERROR: breaking changes discovered