[GitHubEnterprise-3.10] Update to 1.1.4-3e284339623b593c8f10617b72635c64 from 1.1.4-005dd1928c9baa727341c41207d49c50 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 288259
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├──[-] path (32058:3)❌
│ ├──[+] path (31897:3)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
│ │ └─┬POST
│ │   └──[M] description (33849:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[M] description (28889:20)
│ │ └─┬POST
│ │   └──[M] description (28988:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └──[M] description (24741:20)
│ ├─┬/gists/{gist_id}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5924:20)
│ │ └─┬PATCH
│ │   └──[-] description (5963:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (32498:20)
│ │ └─┬PATCH
│ │   └──[M] description (32528:20)
│ ├─┬/gitignore/templates/{name}
│ │ └─┬GET
│ │   └──[M] description (6287:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └──[M] description (34021:20)
│ ├─┬/issues
│ │ └─┬GET
│ │   └──[M] description (6400:20)
│ ├─┬/users/{username}/starred
│ │ └─┬GET
│ │   └──[M] description (44026:20)
│ ├─┬/gists/{gist_id}/comments
│ │ ├─┬GET
│ │ │ └──[-] description (5815:20)
│ │ └─┬POST
│ │   └──[-] description (5860:20)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └──[M] description (25115:20)
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (24272:20)
│ │ └─┬PATCH
│ │   └──[-] description (24310:20)
│ ├─┬/repos/{owner}/{repo}/stargazers
│ │ └─┬GET
│ │   └──[M] description (35132:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (33057:20)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └──[M] description (40821:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[M] description (32247:20)
│ │ └─┬POST
│ │   └──[M] description (32339:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}
│ │ ├─┬GET
│ │ │ └──[M] description (33637:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (33668:20)
│ │ └─┬DELETE
│ │   └──[M] description (33716:20)
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └──[M] description (33979:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └──[M] description (29490:20)
│ │ └─┬PATCH
│ │   └──[M] description (29537:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
│ │ └─┬PUT
│ │   └──[M] description (33790:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └──[M] description (29113:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (33115:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments
│ │ └─┬GET
│ │   └──[M] description (33751:20)
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[M] description (11565:20)
│ ├─┬/repos/{owner}/{repo}/comments
│ │ └─┬GET
│ │   └──[M] description (24169:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments
│ │ └─┬GET
│ │   └──[M] description (32443:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (29814:20)
│ │ └─┬POST
│ │   └──[M] description (29857:20)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └──[M] description (30981:20)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (24595:20)
│ │ └─┬POST
│ │   └──[M] description (24631:20)
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └─┬GET
│ │   └──[M] description (25024:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (32867:20)
│ │ └─┬POST
│ │   ├──[M] description (32914:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬position
│ │           └──[M] description (32954:32)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └──[-] description (6249:20)
│ ├─┬/repos/{owner}/{repo}/git/blobs/{file_sha}
│ │ └─┬GET
│ │   └──[M] description (27391:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├─┬GET
│ │ │ └──[M] description (32743:20)
│ │ └─┬PATCH
│ │   └──[M] description (32795:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ ├─┬GET
│ │ │ └──[M] description (33482:20)
│ │ └─┬POST
│ │   ├──[M] description (33517:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬comments
│ │           └─┬Schema
│ │             └─┬position
│ │               └──[M] description (33577:38)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[M] description (33154:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5649:20)
│ │ └─┬PATCH
│ │   └──[M] description (5681:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (29166:20)
│ │ └─┬PATCH
│ │   └──[M] description (29197:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (23429:20)
│ └─┬/user/starred
│   └─┬GET
│     └──[M] description (42661:20)
└─┬Components
  ├─┬webhook-github-app-authorization-revoked
  │ ├──[+] properties (98673:9)
  │ ├──[+] properties (98675:9)
  │ ├──[+] properties (98677:9)
  │ └──[+] properties (98679:9)
  ├─┬page-deployment
  │ └─┬status_url
  │   └──[M] examples (79752:13)
  └─┬secret-scanning-alert-webhook
    └──[-] properties (86623:9)❌

Date: 01/25/24 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 60            | 1
components       | 6             | 1

❌  2 Breaking changes out of 66
INFO: Modifications: 51
INFO: Removals: 10
INFO: Additions: 5
INFO: Breaking Removals: 2

ERROR: breaking changes discovered