[GitHubEnterprise-3.15] Update to 1.1.4-8ccdb4a501a9f3713872e86b010424b2 from 1.1.4-0e6a4a1bd0678c8ca272e91b4354bf3a Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│ │ └─┬POST
│ │   └──[🔀] description (30606:20)
│ ├─┬/orgs/{org}/personal-access-tokens
│ │ └─┬GET
│ │   └──[➖] parameters (217846:13)❌
│ └─┬/orgs/{org}/personal-access-token-requests
│   └─┬GET
│     └──[➖] parameters (217846:13)❌
└─┬Components
  ├──[➖] parameters (217846:7)❌
  └─┬hook-delivery-item
    ├─┬id
    │ └──[➖] format (68341:19)❌
    ├─┬repository_id
    │ └──[➖] format (68402:19)❌
    └─┬installation_id
      └──[➖] format (68394:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 2                |
| components       | 4             | 4                |

Date: 03/12/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _7_
- **Modifications**: _1_
- **Removals**: _6_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered