[GitHubEnterprise-3.6] Update to 1.1.4 (hash: ed4f169289a64f779c83855c01ccdfe1) from 1.1.4 (hash: 6c694fd5f47dc40f5f613ed4789d2d87) Detected Schema changes:
├─┬Paths
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └──[M] description (32327:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (23310:14)
│ ├─┬/projects/{project_id}/collaborators/{username}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (14066:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (8675:20)
│ │ └─┬PUT
│ │   └──[M] description (8717:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (15283:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (16376:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (16407:20)
│ │ └─┬DELETE
│ │   └──[M] description (16535:20)
│ ├─┬/repos/{owner}/{repo}/tags/protection/{tag_protection_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (31891:14)
│ ├─┬/orgs/{org}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (8392:20)
│ ├─┬/enterprise/stats/all
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3240:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18733:14)
│ ├─┬/orgs/{org}/external-groups
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9455:14)
│ ├─┬/projects/columns/cards/{card_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (13239:14)
│ ├─┬/orgs/{org}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (8082:20)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (81391:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (32406:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (32437:20)
│ │ └─┬DELETE
│ │   └──[M] description (32568:20)
│ ├─┬/orgs/{org}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7339:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7372:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (28167:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (8207:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8281:20)
│ │ ├─┬POST
│ │ │ └──[M] description (8232:20)
│ │ └─┬DELETE
│ │   └──[M] description (8332:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (15944:20)
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (4693:14)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (23364:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (23396:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (23438:14)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6382:14)
│ ├─┬/orgs/{org}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (8437:20)
│ ├─┬/
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (126:14)
│ ├─┬/repos/{owner}/{repo}/releases/generate-notes
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (30522:14)
│ ├─┬/enterprises/{enterprise}/settings/billing/advanced-security
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (4990:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/access
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (15043:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (15077:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (15382:20)
│ │ └─┬DELETE
│ │   └──[M] description (15414:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (32373:20)
│ ├─┬/orgs/{org}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (8050:20)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (4235:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (4277:14)
│ ├─┬/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}
│ │ └─┬GET
│ │   └──[M] description (14715:20)
│ ├─┬/enterprises/{enterprise}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (3847:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (3876:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (28068:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (28105:14)
│ ├─┬/orgs/{org}/external-group/{group_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9424:14)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (23908:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (15600:20)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   ├──[M] description (14908:20)
│ │   └─┬External Docs
│ │     └──[M] url (14916:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (8359:20)
│ ├─┬/orgs/{org}/audit-log
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (8846:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18496:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (8768:20)
│ │ └─┬DELETE
│ │   └──[M] description (8800:20)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (15111:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (15145:14)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (4015:14)
│ ├─┬/repos/{owner}/{repo}/tags/protection
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (31805:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (31840:14)
│ ├─┬/setup/api/start
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (34293:14)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7779:14)
│ ├─┬/organizations/{organization_id}/custom_roles
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6819:14)
│ ├─┬/repos/{owner}/{repo}/zipball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (32147:14)
│ ├─┬/orgs/{org}/actions/permissions/workflow
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7406:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7437:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (16344:20)
│ ├─┬/repos/{owner}/{repo}/tarball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (31920:14)
│ ├─┬/enterprise/stats/pulls
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3460:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (15440:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (15518:20)
│ │ ├─┬POST
│ │ │ └──[M] description (15467:20)
│ │ └─┬DELETE
│ │   └──[M] description (15571:20)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (8005:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (15349:20)
│ ├─┬/orgs/{org}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (8114:20)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7825:14)
│ ├─┬/enterprise/stats/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3349:14)
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27821:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27936:14)
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (27853:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (28038:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (16298:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (30234:14)
│ ├─┬/projects/columns/{column_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (13484:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (15316:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (8467:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8497:20)
│ │ └─┬DELETE
│ │   └──[M] description (8651:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/external-groups
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (12567:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (12645:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (12597:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (8153:20)
│ │ └─┬DELETE
│ │   └──[M] description (8183:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (15239:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (16752:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18269:14)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (16259:14)
│ └─┬/orgs/{org}/teams/{team_slug}/memberships/{username}
│   └─┬GET
│     └──[M] description (12709:20)
└─┬Components
  └──[-] responses (81648:7)❌

Date: 07/27/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 104           | 0
components       | 1             | 1
❌  1 Breaking changes out of 105
INFO: Modifications: 104
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered