[GitHubEnterprise-3.8] Update to 1.1.4 (hash: 5dffbf60e375d826d728a6ff4e38ff44) from 1.1.4 (hash: a7b6bd687a89fabdd71b7185223b8ae3) Detected Schema changes:
└─┬Components
  ├──[-] schemas (61370:7)❌
  └─┬code-scanning-alert-state
    └──[+] enum (61374:9)

Date: 06/24/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 1
❌ 1 Breaking changes out of 2

ERROR: breaking changes discovered