[GitHub] Update to 1.1.4-8710a65416e46eef61e45d68de6a808a from 1.1.4-7c1a2eeb274057b6031d98c8b73d3185 Detected Schema changes:
├──secret-scanning-alert-location-created
└─┬Components
  └─┬webhook-issues-opened
    └─┬changes
      └─┬old_repository
        ├──[-] properties (113837:17)❌
        └──[-] properties (114109:17)❌

Date: 10/03/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌  2 Breaking changes out of 2
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered