[GitHubEnterprise-3.8] Update to 1.1.4-5b46b7479f18cd86a95c59be9d082347 from 1.1.4-35b6a0828d12ef6d0768c3bfaf7efcd7 Detected Schema changes:
├──ping
└─┬Components
  └─┬webhook-issues-opened
    └─┬changes
      └─┬old_repository
        ├──[-] properties (107841:17)❌
        └──[-] properties (108113:17)❌

Date: 10/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌  2 Breaking changes out of 2
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered