[GitHub] Update to 1.1.4-55d97765ea3cb2894a2648379d436234 from 1.1.4-82b1087a8dddd5516c99b2197699c7e0 Detected Schema changes:
```
├──[➖] webhooks (57006:5)❌
├──[➖] webhooks (57338:5)❌
├─┬Paths
│ ├──[➕] path (9815:3)
│ ├──[➕] path (16246:3)
│ └─┬/repos/{owner}/{repo}/commits/{commit_sha}/pulls
│   └─┬GET
│     └──[🔀] description (28779:20)
└─┬Components
  ├──[➕] examples (209751:7)
  ├──[➖] schemas (132150:7)❌
  ├──[➖] schemas (133224:7)❌
  └──[➕] schemas (77080:7)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 3             | 0                |
| components       | 4             | 2                |

Date: 03/27/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _2_ out of _7_
- **Modifications**: _1_
- **Removals**: _4_
- **Additions**: _4_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered