[GitHub] Update to 1.1.4-12b8dbc76c459480c3e846bc22d32615 from 1.1.4-bd1a2cde4ef1f12a463c3206d4665fb8 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 6090ee
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/orgs/{org}/teams/{team_slug}/repos
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/orgs/{org}/migrations/{migration_id}/repositories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/users/{username}/subscriptions
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/teams/{team_id}/repos
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (6264:17)❌
│ ├─┬/orgs/{org}/personal-access-tokens/{pat_id}/repositories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/user/migrations/{migration_id}/repositories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/repos/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default-response
│ │ │         └──[🔀] value (205252:9)
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬security_and_analysis
│ │           └──[➖] properties (16127:21)❌
│ ├─┬/orgs/{org}/personal-access-token-requests/{pat_request_id}/repositories
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (6466:17)❌
│ ├─┬/user/subscriptions
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ ├─┬/users/{username}/repos
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (203022:7)
│ └─┬/orgs/{org}/repos
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (203022:7)
└─┬Components
  ├─┬code-security-configuration
  │ └──[➖] properties (71064:9)❌
  └─┬security-and-analysis
    └──[➖] properties (69548:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 2             | 2                |
| paths            | 14            | 3                |

Date: 07/11/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _5_ out of _16_
- **Modifications**: _11_
- **Removals**: _5_
- **Breaking Removals**: _5_

ERROR: breaking changes discovered