[GitHubEnterprise-3.11] Update to 1.1.4-d360d5f2a68d74d272a599d869bd1480 from 1.1.4-a2af7631437bba6d1a0f12872eaf5a11 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit fb0803
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ └─┬/repos/{owner}/{repo}/autolinks
│   └─┬GET
│     ├──[+] parameters (227568:13)❌
│     ├──[M] summary (20671:16)
│     ├──[M] description (20672:20)
│     └─┬External Docs
│       └──[M] url (20681:14)
└─┬Components
  └──[-] schemas (72668:7)❌

Date: 02/02/24 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 1
components       | 1             | 1

❌  2 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 1
INFO: Additions: 1
INFO: Breaking Removals: 1
INFO: Breaking Additions: 1

ERROR: breaking changes discovered