[GitHubEnterprise-3.15] Update to 1.1.4-2766a6279db0f2ed943b5c4abdd093c7 from 1.1.4-64f3614e3a2420f2e1d792c6db1487f6 Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/dependabot/alerts/{alert_number}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (207388:9)
│             ├──[🔀] value (207388:9)
│             ├──[🔀] value (207388:9)
│             ├──[🔀] value (207388:9)
│             ├──[🔀] value (207388:9)
│             ├──[🔀] value (207388:9)
│             ├──[🔀] value (207388:9)
│             ├──[➕] value (207388:9)
│             ├──[➕] value (207388:9)
│             ├──[➕] value (207388:9)
│             ├──[➕] value (207388:9)
│             └──[➕] value (207388:9)
└─┬Components
  ├──[➖] schemas (67810:7)❌
  └─┬global-advisory
    └─┬epss
      └──[🔀] $ref (67999:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 0                |
| components       | 2             | 2                |

Date: 01/25/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _14_
- **Modifications**: _8_
- **Removals**: _1_
- **Additions**: _5_
- **Breaking Removals**: _1_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered