[GitHub] Update to 1.1.4-5075008eed1820f9dc6dd28e7a1fe112 from 1.1.4-b74686f5a7ae762bfa3ad480e80383fb Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/codeql/databases
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (220244:7)
│ └─┬/repos/{owner}/{repo}/code-scanning/codeql/databases/{language}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             ├──[M] value (220300:9)
│             └──[-] value (220308:9)
├──check-run-completed
├──ping
└─┬Components
  └─┬code-scanning-codeql-database
    └──[-] properties (74665:9)❌

Date: 10/06/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 11            | 0
components       | 1             | 1
❌  1 Breaking changes out of 12
INFO: Modifications: 10
INFO: Removals: 2
INFO: Breaking Removals: 1

ERROR: breaking changes discovered