[GitHubAE] Update to 1.1.4-a0193cc447e66879f2e294bf7f90f620 from 1.1.4-3f4c3c9fd63eb631505ac6fba7a948c3 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ └─┬POST
│ │   ├──[M] description (19212:20)
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └──[-] examples (192360:7)❌
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       ├──[-] examples (19243:17)❌
│ │       └─┬example-single-branch
│ │         └──[-] value (19240:19)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│   ├─┬GET
│   │ └──[M] description (19266:20)
│   ├─┬PUT
│   │ └──[M] description (19298:20)
│   └─┬DELETE
│     └──[M] description (19340:20)
├─┬check-run-requested-action
│ └──POST
└─┬Components
  ├──[-] examples (192360:7)❌
  ├─┬deployment-branch-policy-name-pattern-with-type
  │ ├──[M] title (58802:14)
  │ ├──[-] properties (58830:9)❌
  │ └─┬name
  │   └──[M] description (58806:24)
  └─┬deployment-branch-policy
    ├──[M] description (58783:20)
    ├──[-] properties (58809:9)❌
    ├─┬id
    │ └──[M] description (58787:24)
    └─┬name
      └──[M] description (58796:24)

Date: 10/10/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 7             | 2
components       | 8             | 3
❌  5 Breaking changes out of 15
INFO: Modifications: 9
INFO: Removals: 6
INFO: Breaking Removals: 5

ERROR: breaking changes discovered