[GitHub] Update to 1.1.4-46eadb305342d3e08e981c8d774b0cb1 from 1.1.4-2fa68ef1401ab1f8ecec407bb7c5d77b Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (4925:3)❌
│ ├──[➖] path (4784:3)❌
│ ├──[➖] path (5066:3)❌
│ ├──[➖] path (5001:3)❌
│ ├──[➖] path (5108:3)❌
│ ├──[➖] path (5910:3)❌
│ ├──[➖] path (4963:3)❌
│ ├──[➖] path (5028:3)❌
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (5860:17)❌
│ └─┬/orgs/{org}/actions/runner-groups
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (5745:17)❌
└─┬Components
  ├──[➖] parameters (229018:7)❌
  ├──[➖] examples (206478:7)❌
  ├──[➖] examples (206519:7)❌
  ├──[➖] examples (206541:7)❌
  ├──[➖] examples (206548:7)❌
  ├──[➖] examples (206553:7)❌
  ├──[➖] schemas (74273:7)❌
  ├──[➖] schemas (74107:7)❌
  ├──[➖] schemas (74234:7)❌
  ├──[➖] schemas (74068:7)❌
  ├──[➖] schemas (74137:7)❌
  ├──[➖] schemas (74157:7)❌
  ├─┬integration
  │ └─┬owner
  │   ├──[➕] anyOf (67446:13)
  │   ├──[➕] anyOf (67030:7)
  │   ├──[➖] oneOf (67924:7)❌
  │   └──[➖] oneOf (67537:7)❌
  └─┬runner-groups-org
    └──[➖] properties (74421:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 10            | 10               |
| components       | 17            | 15               |

Date: 01/17/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _25_ out of _27_
- **Removals**: _25_
- **Additions**: _2_
- **Breaking Removals**: _25_

ERROR: breaking changes discovered