[GitHub] Update to 1.1.4-d543c2cfa43a2dcdc9526a6061319dd0 from 1.1.4-c1e4d4617fb30b28dd9ff95dbcd32f2e Detected Schema changes:
```
├─┬Paths
│ ├─┬/gists
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           └──[➖] value (204305:9)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/scan-history
│ │ └─┬GET
│ │   └──[🔀] description (40213:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         ├──[🔀] value (204299:9)
│ │ │         └──[➖] value (204305:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬updateGist
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           ├──[🔀] value (204299:9)
│ │           └──[➖] value (204305:9)
│ └─┬/gists/{gist_id}/{sha}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             ├──[🔀] value (204299:9)
│             └──[➖] value (204305:9)
└─┬Components
  ├─┬base-gist
  │ └──[➖] properties (71527:9)❌
  └─┬gist-simple
    ├──[➖] properties (71947:9)❌
    └─┬fork_of
      └──[➖] properties (71855:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 81            | 0                |
| components       | 3             | 3                |

Date: 01/07/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _84_
- **Modifications**: _77_
- **Removals**: _7_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered