[GitHubEnterprise-3.8] Update to 1.1.4-da7a20bc0b5c841bbe3be873f6743713 from 1.1.4-7cba10c0c2f8c46f83e2eb785b1234ac Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 527329
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├──[-] path (29933:3)❌
│ ├──[+] path (29772:3)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (30984:20)
│ ├─┬/repos/{owner}/{repo}/git/blobs/{file_sha}
│ │ └─┬GET
│ │   └──[M] description (25266:20)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └──[M] description (38576:20)
│ ├─┬/gists/{gist_id}/comments
│ │ ├─┬GET
│ │ │ └──[-] description (5698:20)
│ │ └─┬POST
│ │   └──[-] description (5743:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (30742:20)
│ │ └─┬POST
│ │   ├──[M] description (30789:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬position
│ │           └──[M] description (30829:32)
│ ├─┬/repos/{owner}/{repo}/stargazers
│ │ └─┬GET
│ │   └──[M] description (33001:20)
│ ├─┬/issues
│ │ └─┬GET
│ │   └──[M] description (6283:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └──[M] description (27365:20)
│ │ └─┬PATCH
│ │   └──[M] description (27412:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └──[M] description (22868:20)
│ ├─┬/gitignore/templates/{name}
│ │ └─┬GET
│ │   └──[M] description (6170:20)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └──[M] description (23242:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[M] description (26764:20)
│ │ └─┬POST
│ │   └──[M] description (26863:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (30373:20)
│ │ └─┬PATCH
│ │   └──[M] description (30403:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (30926:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └──[M] description (26988:20)
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (22399:20)
│ │ └─┬PATCH
│ │   └──[-] description (22437:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (21652:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
│ │ └─┬POST
│ │   └──[M] description (31718:20)
│ ├─┬/user/starred
│ │ └─┬GET
│ │   └──[M] description (39949:20)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └──[M] description (28856:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[M] description (30122:20)
│ │ └─┬POST
│ │   └──[M] description (30214:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (27689:20)
│ │ └─┬POST
│ │   └──[M] description (27732:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5532:20)
│ │ └─┬PATCH
│ │   └──[M] description (5564:20)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (22722:20)
│ │ └─┬POST
│ │   └──[M] description (22758:20)
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └─┬GET
│ │   └──[M] description (23151:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments
│ │ └─┬GET
│ │   └──[M] description (30318:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments
│ │ └─┬GET
│ │   └──[M] description (31620:20)
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └──[M] description (31848:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
│ │ └─┬PUT
│ │   └──[M] description (31659:20)
│ ├─┬/users/{username}/starred
│ │ └─┬GET
│ │   └──[M] description (40935:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}
│ │ ├─┬GET
│ │ │ └──[M] description (31506:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (31537:20)
│ │ └─┬DELETE
│ │   └──[M] description (31585:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (27041:20)
│ │ └─┬PATCH
│ │   └──[M] description (27072:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├─┬GET
│ │ │ └──[M] description (30618:20)
│ │ └─┬PATCH
│ │   └──[M] description (30670:20)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └──[-] description (6132:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ ├─┬GET
│ │ │ └──[M] description (31351:20)
│ │ └─┬POST
│ │   ├──[M] description (31386:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬comments
│ │           └─┬Schema
│ │             └─┬position
│ │               └──[M] description (31446:38)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └──[M] description (31890:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[M] description (31023:20)
│ ├─┬/repos/{owner}/{repo}/comments
│ │ └─┬GET
│ │   └──[M] description (22296:20)
│ ├─┬/gists/{gist_id}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5807:20)
│ │ └─┬PATCH
│ │   └──[-] description (5846:20)
│ └─┬/orgs/{org}/issues
│   └─┬GET
│     └──[M] description (10875:20)
└─┬Components
  ├─┬webhook-github-app-authorization-revoked
  │ ├──[+] properties (93336:9)
  │ ├──[+] properties (93338:9)
  │ ├──[+] properties (93340:9)
  │ └──[+] properties (93342:9)
  ├─┬page-deployment
  │ └─┬status_url
  │   └──[M] examples (74731:13)
  └─┬secret-scanning-alert-webhook
    └──[-] properties (81381:9)❌

Date: 01/24/24 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 60            | 1
components       | 6             | 1

❌  2 Breaking changes out of 66
INFO: Modifications: 51
INFO: Removals: 10
INFO: Additions: 5
INFO: Breaking Removals: 2

ERROR: breaking changes discovered