[GitHub] Update to 1.1.4-9ae695acfe1e0faf5891cec94cd6b0a4 from 1.1.4-1a5c27df40e2c66ac3dac2b39c0e601b Detected Schema changes:
├─┬Paths
│ ├──[-] path (9461:3)❌
│ ├──[-] path (9288:3)❌
│ ├──[-] path (9625:3)❌
│ ├──[-] path (9401:3)❌
│ ├──[-] path (9315:3)❌
│ ├──[-] path (9092:3)❌
│ ├──[-] path (9374:3)❌
│ ├──[-] path (9672:3)❌
│ ├──[-] path (9138:3)❌
│ ├─┬/orgs/{org}/codespaces/secrets/{secret_name}/repositories
│ │ └─┬PUT
│ │   └──[M] description (6332:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ └─┬POST
│ │   └──[M] description (32630:20)
│ ├─┬/search/users
│ │ └─┬GET
│ │   └──[M] description (37121:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ └─┬POST
│ │   └──[M] description (28067:20)
│ ├─┬/orgs/{org}/copilot/billing/selected_teams
│ │ ├─┬POST
│ │ │ ├──[M] summary (6559:16)
│ │ │ ├──[M] description (6560:20)
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (6577:14)
│ │ │ ├─┬Responses
│ │ │ │ └─┬422
│ │ │ │   └──[M] description (6629:24)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (6634:9)
│ │ └─┬DELETE
│ │   ├──[M] summary (6639:16)
│ │   ├──[M] description (6640:20)
│ │   ├─┬External Docs
│ │   │ └──[M] url (6657:14)
│ │   ├─┬Responses
│ │   │ └─┬422
│ │   │   └──[M] description (6709:24)
│ │   └─┬Extensions
│ │     └──[M] x-github (6714:9)
│ ├─┬/user/codespaces/secrets/{secret_name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (39439:20)
│ │ └─┬PUT
│ │   └──[M] description (39488:20)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ └─┬PUT
│ │   └──[M] description (22418:20)
│ ├─┬/orgs/{org}/copilot/billing
│ │ └─┬GET
│ │   ├──[M] summary (6456:16)
│ │   ├──[M] description (6457:20)
│ │   ├─┬External Docs
│ │   │ └──[M] url (6471:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (6493:9)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ └─┬POST
│ │   └──[M] description (32029:20)
│ ├─┬/search/topics
│ │ └─┬GET
│ │   └──[M] description (37060:20)
│ ├─┬/repos/{owner}/{repo}/codespaces/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (22201:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (22232:20)
│ │ └─┬DELETE
│ │   └──[M] description (22290:20)
│ ├─┬/orgs/{org}/members/{username}/copilot
│ │ └─┬GET
│ │   ├──[M] summary (8606:16)
│ │   ├──[M] description (8607:20)
│ │   ├─┬External Docs
│ │   │ └──[M] url (8618:14)
│ │   ├─┬Responses
│ │   │ └─┬422
│ │   │   └──[M] description (8641:24)
│ │   └─┬Extensions
│ │     └──[M] x-github (8644:9)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
│ │ └─┬POST
│ │   └──[M] description (32469:20)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ └─┬POST
│ │   └──[M] description (23045:20)
│ ├─┬/search/labels
│ │ └─┬GET
│ │   └──[M] description (36896:20)
│ ├─┬/user/codespaces/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (39306:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (39337:20)
│ │ └─┬DELETE
│ │   └──[M] description (39414:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ └─┬POST
│ │   └──[M] description (31347:20)
│ ├─┬/user/codespaces/secrets
│ │ └─┬GET
│ │   └──[M] description (39229:20)
│ ├─┬/search/code
│ │ └─┬GET
│ │   └──[M] description (36624:20)
│ ├─┬/repos/{owner}/{repo}/releases
│ │ └─┬POST
│ │   └──[M] description (33222:20)
│ ├─┬/search/issues
│ │ └─┬GET
│ │   └──[M] description (36801:20)
│ ├─┬/orgs/{org}/codespaces/secrets
│ │ └─┬GET
│ │   └──[M] description (6071:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/merge
│ │ └─┬PUT
│ │   └──[M] description (32335:20)
│ ├─┬/user/codespaces/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (39546:20)
│ │ └─┬DELETE
│ │   └──[M] description (39581:20)
│ ├─┬/orgs/{org}/codespaces/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (6145:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (6177:20)
│ │ └─┬DELETE
│ │   └──[M] description (6264:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions
│ │ └─┬POST
│ │   └──[M] description (11909:20)
│ ├─┬/orgs/{org}/copilot/billing/seats
│ │ └─┬GET
│ │   ├──[M] summary (6499:16)
│ │   ├──[M] description (6500:20)
│ │   ├─┬External Docs
│ │   │ └──[M] url (6512:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (6553:9)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (32171:20)
│ ├─┬/orgs/{org}/invitations
│ │ └─┬POST
│ │   └──[M] description (8123:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments
│ │ └─┬POST
│ │   └──[M] description (12114:20)
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/comments
│ │ └─┬POST
│ │   └──[M] description (37630:20)
│ ├─┬/codes_of_conduct/{key}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (209640:9)
│ ├─┬/gists/public
│ │ └─┬GET
│ │   └──[M] description (1746:20)
│ ├─┬/search/commits
│ │ └─┬GET
│ │   └──[M] description (36728:20)
│ ├─┬/repos/{owner}/{repo}/security-advisories/{ghsa_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       ├─┬add_credit
│ │       │ └──[M] summary (34894:26)
│ │       ├─┬update_vvrs
│ │       │ └──[M] summary (34901:26)
│ │       └─┬invalid_state_transition
│ │         └──[M] summary (34919:26)
│ ├─┬/orgs/{org}/copilot/billing/selected_users
│ │ ├─┬POST
│ │ │ ├──[M] summary (6720:16)
│ │ │ ├──[M] description (6721:20)
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (6738:14)
│ │ │ ├─┬Responses
│ │ │ │ └─┬422
│ │ │ │   └──[M] description (6790:24)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (6795:9)
│ │ └─┬DELETE
│ │   ├──[M] summary (6800:16)
│ │   ├──[M] description (6801:20)
│ │   ├─┬External Docs
│ │   │ └──[M] url (6818:14)
│ │   ├─┬Responses
│ │   │ └─┬422
│ │   │   └──[M] description (6870:24)
│ │   └─┬Extensions
│ │     └──[M] x-github (6876:9)
│ ├─┬/search/repositories
│ │ └─┬GET
│ │   └──[M] description (36979:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ └─┬POST
│ │   └──[M] description (28935:20)
│ ├─┬/teams/{team_id}/discussions
│ │ └─┬POST
│ │   └──[M] description (37415:20)
│ ├─┬/orgs/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (6386:20)
│ │ └─┬DELETE
│ │   └──[M] description (6421:20)
│ └─┬/repos/{owner}/{repo}/codespaces/secrets
│   └─┬GET
│     └──[M] description (22122:20)
├──ping
└─┬Components
  ├──[-] parameters (235908:7)❌
  ├──[-] examples (216593:7)❌
  ├──[-] examples (216528:7)❌
  ├──[-] examples (216534:7)❌
  ├──[-] schemas (69512:7)❌
  ├──[-] schemas (69500:7)❌
  ├─┬copilot-seat-details
  │ ├──[M] title (68367:14)
  │ └──[M] description (68368:20)
  ├─┬copilot-organization-details
  │ ├──[M] title (68044:14)
  │ └──[M] description (68045:20)
  ├─┬copilot-seat-breakdown
  │ ├──[M] title (68016:14)
  │ └──[M] description (68017:20)
  ├─┬team-discussion
  │ └─┬private
  │   └──[M] description (70906:24)
  └─┬code-of-conduct
    └─┬body
      └──[M] examples (63634:13)

Date: 11/17/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 89            | 9
components       | 14            | 6

❌  15 Breaking changes out of 103
INFO: Modifications: 88
INFO: Removals: 15
INFO: Breaking Removals: 15

ERROR: breaking changes discovered