[GitHubEnterprise-3.8] Update to 1.1.4 (hash: 2e55ce9f6b61b336b3609a6786f51677) from 1.1.4 (hash: 13a8f31e2aecef0685bc0fb8d6a55ee8) Detected Schema changes:
└─┬Components
  ├──[-] schemas (79857:7)❌
  ├──[-] schemas (79844:7)❌
  ├─┬webhook-secret-scanning-alert-resolved
  │ └─┬alert
  │   └──[M] $ref (181182:11)❌
  ├─┬webhook-secret-scanning-alert-reopened
  │ └─┬alert
  │   └──[M] $ref (76530:13)❌
  ├─┬webhook-secret-scanning-alert-revoked
  │ └─┬alert
  │   └──[M] $ref (76530:13)❌
  ├─┬webhook-secret-scanning-alert-location-created
  │ └─┬alert
  │   └──[M] $ref (76530:13)❌
  └─┬webhook-secret-scanning-alert-created
    └─┬alert
      └──[M] $ref (76530:13)❌

Date: 07/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 7             | 7
❌  7 Breaking changes out of 7
INFO: Modifications: 5
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 5

ERROR: breaking changes discovered