[GitHub] Update to 1.1.4-6f03f69310915cd2cc2ba810a95cb8af from 1.1.4-5bd2a30080267627618f4b33aa9b7f31 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 6971d9
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[🔀] description (34133:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[🔀] description (33025:20)
│ │ └─┬POST
│ │   └──[🔀] description (33129:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ └─┬PATCH
│ │   └──[🔀] description (33627:20)
│ └─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│   └─┬GET
│     └──[🔀] description (34086:20)
└─┬Components
  └─┬repository-ruleset-bypass-actor
    ├─┬actor_id
    │ └──[🔀] description (71593:24)
    ├─┬bypass_mode
    │ └──[🔀] description (71605:24)
    └─┬actor_type
      ├──[➖] enum (71600:13)❌
      └──[🔀] description (71602:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 0                |
| components       | 4             | 1                |

Date: 04/28/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _9_
- **Modifications**: _8_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered