[GitHub] Update to 1.1.4-28a997033a88fffc4459106785ce7992 from 1.1.4-a073e1a053477690d506f42cadb2ee51 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-security-configuration
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (216327:9)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205154:9)
│ │   │       ├──[🔀] value (205154:9)
│ │   │       ├──[🔀] value (205154:9)
│ │   │       ├──[🔀] value (205154:9)
│ │   │       ├──[🔀] value (205154:9)
│ │   │       ├──[🔀] value (205154:9)
│ │   │       └──[➖] value (205202:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (8004:17)❌
│ ├─┬/enterprises/{enterprise}/code-security/configurations
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       └──[➖] value (205113:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (1609:17)❌
│ ├─┬/enterprises/{enterprise}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (205066:9)
│ │ │         ├──[🔀] value (205066:9)
│ │ │         ├──[🔀] value (205066:9)
│ │ │         ├──[🔀] value (205066:9)
│ │ │         ├──[🔀] value (205066:9)
│ │ │         ├──[🔀] value (205066:9)
│ │ │         └──[➖] value (205113:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       ├──[🔀] value (205066:9)
│ │   │       └──[➖] value (205113:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (1851:17)❌
│ └─┬/orgs/{org}/code-security/configurations/{configuration_id}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         ├──[🔀] value (205154:9)
│   │         ├──[🔀] value (205154:9)
│   │         ├──[🔀] value (205154:9)
│   │         ├──[🔀] value (205154:9)
│   │         ├──[🔀] value (205154:9)
│   │         ├──[🔀] value (205154:9)
│   │         └──[➖] value (205202:9)
│   └─┬PATCH
│     ├─┬Responses
│     │ └─┬200
│     │   └─┬application/json
│     │     └─┬default
│     │       ├──[🔀] value (208485:9)
│     │       ├──[🔀] value (208485:9)
│     │       ├──[🔀] value (208485:9)
│     │       ├──[🔀] value (208485:9)
│     │       ├──[🔀] value (208485:9)
│     │       ├──[🔀] value (208485:9)
│     │       └──[➖] value (208534:9)
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[➖] properties (8340:17)❌
└─┬Components
  ├─┬code-security-configuration
  │ └──[➖] properties (71110:9)❌
  └─┬webhook-release-edited
    └─┬changes
      └──[➖] properties (193213:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 47            | 4                |
| components       | 2             | 2                |

Date: 03/04/25 | Commit: Original: etc/specs/GitHub/current.spec.yaml, Modified: etc/specs/GitHub/previous.spec.yaml,

- ❌ **BREAKING Changes**: _6_ out of _49_
- **Modifications**: _37_
- **Removals**: _12_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered