[GitHubEnterprise-3.15] Update to 1.1.4-531e13661f965ac04f0ddfe589e8a768 from 1.1.4-dafc4bb4ca8269335f6c4492394f88df Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-security-configuration
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (205806:9)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➕] properties (11489:17)
│ │         ├─┬secret_scanning_non_provider_patterns
│ │         │ ├──[➖] enum (11485:21)❌
│ │         │ ├──[➖] enum (11486:21)❌
│ │         │ ├──[➖] enum (11487:21)❌
│ │         │ ├──[🔀] type (11449:25)❌
│ │         │ ├──[🔀] description (11450:32)
│ │         │ ├──[➖] default (11488:28)❌
│ │         │ └──[➕] properties (11452:21)
│ │         ├─┬secret_scanning_delegated_bypass_options
│ │         │ ├──[➕] enum (11445:21)
│ │         │ ├──[➕] enum (11446:21)
│ │         │ ├──[➕] enum (11444:21)
│ │         │ ├──[🔀] type (11440:25)❌
│ │         │ ├──[🔀] description (11441:32)
│ │         │ ├──[➕] default (11447:28)❌
│ │         │ └──[➖] properties (11452:21)❌
│ │         ├─┬secret_scanning_validity_checks
│ │         │ └──[🔀] description (11433:32)
│ │         ├─┬secret_scanning_delegated_bypass
│ │         │ ├──[🔀] description (11491:32)
│ │         │ └──[➖] default (11447:28)❌
│ │         └─┬secret_scanning_push_protection
│ │           └──[🔀] description (11482:32)
│ └─┬/orgs/{org}/code-security/configurations/{configuration_id}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[➕] properties (11808:17)
│           ├─┬secret_scanning_delegated_bypass_options
│           │ ├──[➕] enum (11766:21)
│           │ ├──[➕] enum (11767:21)
│           │ ├──[➕] enum (11768:21)
│           │ ├──[🔀] type (11762:25)❌
│           │ ├──[🔀] description (11763:32)
│           │ └──[➖] properties (11765:21)❌
│           ├─┬secret_scanning_validity_checks
│           │ └──[🔀] description (11756:32)
│           ├─┬secret_scanning_delegated_bypass
│           │ └──[🔀] description (11810:32)
│           ├─┬secret_scanning_push_protection
│           │ └──[🔀] description (11802:32)
│           └─┬secret_scanning_non_provider_patterns
│             ├──[➖] enum (11797:21)❌
│             ├──[➖] enum (11798:21)❌
│             ├──[➖] enum (11799:21)❌
│             ├──[🔀] type (11770:25)❌
│             ├──[🔀] description (11771:32)
│             └──[➕] properties (11773:21)
└─┬Components
  └─┬code-security-configuration
    ├──[➕] properties (74835:9)
    ├─┬target_type
    │ ├──[➕] enum (74825:13)
    │ ├──[➕] enum (74826:13)
    │ ├──[➕] enum (74827:13)
    │ ├──[➖] enum (74722:13)❌
    │ ├──[➖] enum (74723:13)❌
    │ ├──[➖] enum (74724:13)❌
    │ └──[🔀] description (74823:24)
    ├─┬secret_scanning_delegated_bypass
    │ └──[🔀] description (74837:24)
    ├─┬updated_at
    │ ├──[➕] enum (74738:13)
    │ ├──[➕] enum (74739:13)
    │ ├──[➕] enum (74740:13)
    │ ├──[➖] format (74838:19)❌
    │ └──[➕] description (74736:24)
    ├─┬url
    │ ├──[🔀] format (74861:19)❌
    │ └──[➖] description (74828:24)
    ├─┬secret_scanning_non_provider_patterns
    │ ├──[➖] enum (74816:13)❌
    │ ├──[➖] enum (74817:13)❌
    │ ├──[➖] enum (74818:13)❌
    │ ├──[🔀] type (74800:17)❌
    │ ├──[🔀] description (74801:24)
    │ └──[➕] properties (74803:13)
    ├─┬secret_scanning_push_protection
    │ └──[🔀] description (74830:24)
    ├─┬secret_scanning_delegated_bypass_options
    │ ├──[➕] enum (74796:13)
    │ ├──[➕] enum (74797:13)
    │ ├──[➕] enum (74798:13)
    │ ├──[🔀] type (74793:17)❌
    │ ├──[🔀] description (74794:24)
    │ └──[➖] properties (74787:13)❌
    └─┬secret_scanning_validity_checks
      └──[🔀] description (74787:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 36            | 15               |
| components       | 30            | 11               |

Date: 03/06/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _26_ out of _66_
- **Modifications**: _24_
- **Removals**: _19_
- **Additions**: _23_
- **Breaking Removals**: _18_
- **Breaking Modifications**: _7_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered