[GitHubEnterprise-3.10] Update to 1.1.4-84d59b3b8ef8925925736276b817dfe3 from 1.1.4-7eb89baa0dcaa12110b20a25a50be8ff Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (63216:14)❌
│ │         └─┬default
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[M] value (220071:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           └──[-] value (208410:9)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/apps
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (63216:14)❌
│ │         └─┬default
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           └──[-] value (208410:9)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (15516:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/{protection_rule_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/user/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (63216:14)❌
│ │         └─┬default
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[M] value (208403:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           ├──[-] value (208410:9)
│ │           └──[-] value (208410:9)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬GET
│ │   └──[M] description (29497:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (225514:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (225514:20)
│ └─┬/app/installations/{installation_id}/access_tokens
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬default
│           └──[M] value (1974:19)
└─┬Components
  ├──[+] examples (208402:7)
  ├──[+] examples (220070:7)
  └─┬app-permissions
    ├──[-] properties (62284:9)❌
    └─┬organization_custom_roles
      └──[M] description (62278:24)

Date: 11/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 299           | 3
components       | 4             | 1

❌  4 Breaking changes out of 303
INFO: Modifications: 280
INFO: Removals: 21
INFO: Additions: 2
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 3

ERROR: breaking changes discovered