[GitHubEnterprise-3.14] Update to 1.1.4-401e653a83ab83c1b17a4df959fec270 from 1.1.4-92f924d1a2fb4647ad6d28e98d13ef05 Detected Schema changes:
```
├─┬Paths
│ └─┬/orgs/{org}/memberships/{username}
│   └─┬PUT
│     └──[🔀] description (12899:20)
└─┬Components
  └─┬integration
    └─┬owner
      ├──[➕] anyOf (67718:13)
      ├──[➕] anyOf (66718:7)
      ├──[➖] oneOf (67692:7)❌
      └──[➖] oneOf (66717:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 4             | 2                |

Date: 01/17/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _5_
- **Modifications**: _1_
- **Removals**: _2_
- **Additions**: _2_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered