[GitHub] Update to 1.1.4-ac26bea3c7b43c61995d720fd1312db2 from 1.1.4-cdf06887872e14c33e252a1a6bb7b705 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (234537:20)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (76868:14)❌
├──ping
└─┬Components
  ├──[-] schemas (76876:7)❌
  └─┬copilot-organization-details
    └──[-] properties (67150:9)❌

Date: 09/28/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 2             | 1
components       | 2             | 2
❌  3 Breaking changes out of 4
INFO: Modifications: 2
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered