[GitHubEnterprise-3.5] Update to 1.1.4 (hash: 85d26b63f5361f81d5f1840c12528e08current=56f1efe3867dfe4c8325ec0fad3707e6) from 1.1.4 (hash: ) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/issues/events
│ │ └─┬GET
│ │   └──[-] description (25294:20)
│ ├─┬/users/{username}/projects
│ │ └─┬GET
│ │   └──[-] description (37504:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
│ │ ├─┬GET
│ │ │ └──[-] description (27141:20)
│ │ └─┬DELETE
│ │   └──[-] description (27231:20)
│ ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
│ │ └─┬GET
│ │   └──[-] description (25331:20)
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └─┬GET
│ │   ├──[-] description (31514:20)
│ │   └─┬Responses
│ │     └──[-] codes (78826:7)❌
│ ├─┬/repos/{owner}/{repo}/milestones
│ │ ├─┬GET
│ │ │ └──[-] description (27003:20)
│ │ └─┬POST
│ │   └──[-] description (27070:20)
│ ├─┬/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (21944:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ ├─┬GET
│ │ │ └──[-] description (10977:20)
│ │ └─┬DELETE
│ │   └──[-] description (11024:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (8424:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (16061:20)
│ ├─┬/repos/{owner}/{repo}/labels/{name}
│ │ ├─┬GET
│ │ │ └──[-] description (26659:20)
│ │ ├─┬DELETE
│ │ │ └──[-] description (26753:20)
│ │ └─┬PATCH
│ │   └──[-] description (26693:20)
│ ├─┬/projects/{project_id}/columns
│ │ ├─┬GET
│ │ │ └──[-] description (13879:20)
│ │ └─┬POST
│ │   └──[-] description (13918:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[-] codes (78838:7)❌
│ ├─┬/repos/{owner}/{repo}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (26554:20)
│ │ └─┬POST
│ │   └──[-] description (26590:20)
│ ├─┬/user/memberships/orgs/{org}
│ │ ├─┬GET
│ │ │ └──[-] description (35881:20)
│ │ └─┬PATCH
│ │   └──[-] description (35915:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
│ │ └─┬GET
│ │   └──[-] description (26366:20)
│ ├─┬/user/memberships/orgs
│ │ └─┬GET
│ │   └──[-] description (35830:20)
│ ├─┬/orgs/{org}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (8974:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ ├─┬GET
│ │ │ └──[-] description (12946:20)
│ │ └─┬DELETE
│ │   └──[-] description (13040:20)
│ ├─┬/projects/columns/{column_id}
│ │ ├─┬GET
│ │ │ └──[-] description (13191:20)
│ │ └─┬DELETE
│ │   └──[-] description (13276:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (25842:20)
│ │ ├─┬POST
│ │ │ └──[-] description (25883:20)
│ │ └─┬DELETE
│ │   └──[-] description (26063:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
│ │ └─┬GET
│ │   └──[-] description (27255:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
│ │ └─┬GET
│ │   └──[-] description (25804:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (31988:20)
│ └─┬/projects/columns/{column_id}/cards
│   └─┬GET
│     └──[-] description (13302:20)
└─┬Components
  └─┬api-overview
    └──[-] properties (43105:9)❌

Date: 06/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.5/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.5/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 38            | 2
components       | 1             | 1
❌ 3 Breaking changes out of 39

ERROR: breaking changes discovered