[GitHub] Update to 1.1.4-569ed36cc004e0f3ecba0e072fcfa984 from 1.1.4-893e2fb0b8fad9258f8b3396ebcda9b9 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/insights/api/time-stats/{actor_type}/{actor_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └─┬Schema
│ │       ├──[➕] enum (226969:11)
│ │       ├──[➕] enum (226970:11)
│ │       ├──[➕] enum (226971:11)
│ │       ├──[➕] enum (226972:11)
│ │       ├──[➕] enum (226973:11)
│ │       ├──[➖] enum (226975:11)❌
│ │       ├──[➖] enum (226976:11)❌
│ │       ├──[➖] enum (226972:11)❌
│ │       ├──[➖] enum (226973:11)❌
│ │       └──[➖] enum (226974:11)❌
│ ├─┬/orgs/{org}/insights/api/summary-stats/{actor_type}/{actor_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └─┬Schema
│ │       ├──[➕] enum (226972:11)
│ │       ├──[➕] enum (226973:11)
│ │       ├──[➕] enum (226969:11)
│ │       ├──[➕] enum (226970:11)
│ │       ├──[➕] enum (226971:11)
│ │       ├──[➖] enum (226972:11)❌
│ │       ├──[➖] enum (226973:11)❌
│ │       ├──[➖] enum (226974:11)❌
│ │       ├──[➖] enum (226975:11)❌
│ │       └──[➖] enum (226976:11)❌
│ └─┬/orgs/{org}/insights/api/route-stats/{actor_type}/{actor_id}
│   └─┬GET
│     └─┬Parameters
│       └─┬Schema
│         ├──[➕] enum (226972:11)
│         ├──[➕] enum (226973:11)
│         ├──[➕] enum (226969:11)
│         ├──[➕] enum (226970:11)
│         ├──[➕] enum (226971:11)
│         ├──[➖] enum (226974:11)❌
│         ├──[➖] enum (226975:11)❌
│         ├──[➖] enum (226976:11)❌
│         ├──[➖] enum (226972:11)❌
│         └──[➖] enum (226973:11)❌
└─┬Components
  └─┬copilot-seat-details
    └─┬updated_at
      ├──[🔀] description (69252:24)
      └──[➖] deprecated (69252:23)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 30            | 15               |
| components       | 2             | 0                |

Date: 12/06/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _15_ out of _32_
- **Modifications**: _1_
- **Removals**: _16_
- **Additions**: _15_
- **Breaking Removals**: _15_

ERROR: breaking changes discovered