[GitHubAE] Update to 1.1.4-b989ff83ac81fa58b5ba441c3533ada9 from 1.1.4-4c5e05b63b9b55649d3117efa99d0e48 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 67baf0                                                                                 SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [47680:7]
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └─┬GET
│ │   └──[M] description (16744:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ └─┬GET
│ │   └──[M] description (16226:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (16322:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (16445:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──[M] description (16365:20)
│ └──/markdown/raw
├─┬project-created
│ └─┬POST
│   ├──[M] summary (40096:16)
│   └──[M] description (40102:20)
├─┬dependabot-alert-auto-dismissed
│ └─┬POST
│   └──[M] description (33895:20)
├─┬project-column-created
│ └─┬POST
│   ├──[M] summary (39832:16)
│   └──[M] description (39838:20)
├─┬project-card-edited
│ └─┬POST
│   ├──[M] summary (39633:16)
│   └──[M] description (39639:20)
├─┬project-reopened
│ └─┬POST
│   ├──[M] summary (40294:16)
│   └──[M] description (40300:20)
├─┬dependabot-alert-auto-reopened
│ └─┬POST
│   └──[M] description (33963:20)
├─┬project-column-moved
│ └─┬POST
│   ├──[M] summary (40030:16)
│   └──[M] description (40036:20)
├─┬project-card-created
│ └─┬POST
│   ├──[M] summary (39501:16)
│   └──[M] description (39507:20)
├─┬project-edited
│ └─┬POST
│   ├──[M] summary (40228:16)
│   └──[M] description (40234:20)
├─┬project-column-deleted
│ └─┬POST
│   ├──[M] summary (39898:16)
│   └──[M] description (39904:20)
├─┬project-card-converted
│ └─┬POST
│   ├──[M] summary (39435:16)
│   └──[M] description (39441:20)
├─┬project-closed
│ └─┬POST
│   ├──[M] summary (39766:16)
│   └──[M] description (39772:20)
├─┬project-column-edited
│ └─┬POST
│   ├──[M] summary (39964:16)
│   └──[M] description (39970:20)
├─┬project-deleted
│ └─┬POST
│   ├──[M] summary (40162:16)
│   └──[M] description (40168:20)
├─┬project-card-moved
│ └─┬POST
│   ├──[M] summary (39699:16)
│   └──[M] description (39705:20)
├─┬project-card-deleted
│ └─┬POST
│   ├──[M] summary (39567:16)
│   └──[M] description (39573:20)
└─┬Components
  ├─┬app-permissions
  │ ├──[-] properties (46547:9)❌
  │ ├──[-] properties (46561:9)❌
  │ ├──[-] properties (46778:9)❌
  │ ├──[-] properties (46785:9)❌
  │ ├──[-] properties (46792:9)❌
  │ ├──[-] properties (46799:9)❌
  │ ├──[-] properties (46806:9)❌
  │ ├──[-] properties (46701:9)❌
  │ ├──[-] properties (46813:9)❌
  │ └──[-] properties (46819:9)❌
  └─┬code-scanning-ref-full
    ├──[M] pattern (56990:16)❌
    └──[M] description (56987:20)

Date: 12/07/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 0
webhooks         | 30            | 0
components       | 12            | 11

❌  11 Breaking changes out of 47
INFO: Modifications: 37
INFO: Removals: 10
INFO: Breaking Removals: 10
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered