[GitHubEnterprise-3.8] Update to 1.1.4 (hash: 13a8f31e2aecef0685bc0fb8d6a55ee8) from 1.1.4 (hash: c66d9b12840f1e4e86ce503169ac056e) Detected Schema changes:
├─┬Paths
│ ├─┬/
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (128:14)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (18187:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (34564:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (34636:20)
│ │ └─┬PATCH
│ │   └──[M] description (34594:20)
│ ├─┬/repos/{owner}/{repo}/tags/protection
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33677:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (33712:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (16352:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (16386:14)
│ ├─┬/repos/{owner}/{repo}/actions/permissions/access
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (16283:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (16318:14)
│ ├─┬/enterprises/{enterprise}/settings/billing/advanced-security
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5193:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (16681:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (16759:20)
│ │ ├─┬POST
│ │ │ └──[M] description (16708:20)
│ │ └─┬DELETE
│ │   └──[M] description (16812:20)
│ ├─┬/setup/api/start
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (36362:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (17586:20)
│ ├─┬/user/ssh_signing_keys/{ssh_signing_key_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (40107:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (40144:14)
│ ├─┬/orgs/{org}/teams/{team_slug}/external-groups
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (13565:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (13643:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (13595:14)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (25061:14)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (25115:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (25147:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (25189:14)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/rerun-failed-jobs
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (17501:14)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (25667:14)
│ ├─┬/orgs/{org}/external-group/{group_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (10329:14)
│ ├─┬/orgs/{org}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (9194:20)
│ │ └─┬POST
│ │   └──[M] description (9238:20)
│ ├─┬/orgs/{org}/actions/variables/{name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (9425:20)
│ │ └─┬PUT
│ │   └──[M] description (9471:20)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/apps
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (19732:14)
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29827:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (29864:14)
│ ├─┬/orgs/{org}/announcement
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9596:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/users
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (20196:14)
│ ├─┬/repos/{owner}/{repo}/zipball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (34023:14)
│ ├─┬/orgs/{org}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (8443:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └──[M] description (34203:20)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (8568:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8642:20)
│ │ ├─┬POST
│ │ │ └──[M] description (8593:20)
│ │ └─┬DELETE
│ │   └──[M] description (8693:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (14271:14)
│ ├─┬/organizations/{organization_id}/custom_roles
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (7052:14)
│ ├─┬/repos/{owner}/{repo}/tarball/{ref}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (33792:14)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (32075:14)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (34249:20)
│ ├─┬/repos/{owner}/{repo}/releases/generate-notes
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (32375:14)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (4022:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (17618:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (17649:20)
│ │ └─┬DELETE
│ │   └──[M] description (17777:20)
│ ├─┬/orgs/{org}/actions/secrets/public-key
│ │ └─┬GET
│ │   └──[M] description (8798:20)
│ ├─┬/orgs/{org}/actions/permissions/workflow
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7767:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7798:14)
│ ├─┬/enterprise/stats/all
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3247:14)
│ ├─┬/enterprises/{enterprise}/code_security_and_analysis
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (5013:14)
│ ├─┬/orgs/{org}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (9310:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (9401:20)
│ │ └─┬PATCH
│ │   └──[M] description (9340:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (34468:20)
│ │ └─┬POST
│ │   └──[M] description (34512:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (16623:20)
│ │ └─┬DELETE
│ │   └──[M] description (16655:20)
│ ├─┬/orgs/{org}/{security_product}/{enablement}
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (14211:14)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (8366:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (17801:20)
│ │ └─┬POST
│ │   └──[M] description (17845:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (34282:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (34313:20)
│ │ └─┬DELETE
│ │   └──[M] description (34444:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (9129:20)
│ │ └─┬DELETE
│ │   └──[M] description (9161:20)
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (4700:14)
│ ├─┬/repos/{owner}/{repo}/tags/protection/{tag_protection_id}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (33763:14)
│ ├─┬/orgs/{org}/audit-log
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (9684:14)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (8514:20)
│ │ └─┬DELETE
│ │   └──[M] description (8544:20)
│ ├─┬/enterprise/stats/pulls
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3467:14)
│ ├─┬/orgs/{org}/actions/variables/{name}/repositories/{repository_id}
│ │ ├─┬PUT
│ │ │ └──[M] description (9520:20)
│ │ └─┬DELETE
│ │   └──[M] description (9553:20)
│ ├─┬/projects/{project_id}/collaborators/{username}
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (15098:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (16841:20)
│ ├─┬/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/{archive_format}
│ │ └─┬GET
│ │   └──[M] description (15753:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (16524:20)
│ ├─┬/orgs/{org}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (8753:20)
│ ├─┬/orgs/{org}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (8411:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}/repositories
│ │ ├─┬GET
│ │ │ └──[M] description (9036:20)
│ │ └─┬PUT
│ │   └──[M] description (9078:20)
│ ├─┬/orgs/{org}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (8475:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (16557:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (16480:20)
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (29926:14)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (17186:20)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (8720:20)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (6615:14)
│ ├─┬/orgs/{org}/teams/{team_slug}/memberships/{username}
│ │ └─┬GET
│ │   └──[M] description (13707:20)
│ ├─┬/orgs/{org}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (7700:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (7733:14)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (4242:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (4284:14)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └──[M] description (8828:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (8858:20)
│ │ └─┬DELETE
│ │   └──[M] description (9012:20)
│ ├─┬/user/ssh_signing_keys
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (39999:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (40043:14)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories/{repository_id}
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (8186:14)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   ├──[M] description (16048:20)
│ │   └─┬External Docs
│ │     └──[M] url (16056:14)
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[M] description (215937:20)
│ ├─┬/enterprises/{enterprise}/actions/permissions/selected-actions
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (3854:14)
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (3883:14)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (16590:20)
│ ├─┬/orgs/{org}/external-groups
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (10360:14)
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/protection/restrictions/teams
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (19959:14)
│ ├─┬/enterprise/stats/issues
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (3356:14)
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29580:14)
│ │ ├─┬PUT
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29695:14)
│ │ ├─┬POST
│ │ │ └─┬External Docs
│ │ │   └──[M] url (29612:14)
│ │ └─┬DELETE
│ │   └─┬External Docs
│ │     └──[M] url (29797:14)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/repositories
│ │ └─┬PUT
│ │   └─┬External Docs
│ │     └──[M] url (8140:14)
│ ├─┬/repos/{owner}/{repo}/actions/secrets
│ │ └─┬GET
│ │   └──[M] description (17540:20)
│ ├─┬/projects/columns/{column_id}
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (14516:14)
│ └─┬/repos/{owner}/{repo}/actions/variables/{name}
│   ├─┬GET
│   │ └──[M] description (17897:20)
│   ├─┬DELETE
│   │ └──[M] description (17969:20)
│   └─┬PATCH
│     └──[M] description (17927:20)
└─┬Components
  └──[-] responses (216250:7)❌

Date: 07/27/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 130           | 0
components       | 1             | 1
❌  1 Breaking changes out of 131
INFO: Modifications: 130
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered