[GitHub] Update to 1.1.4-fab1ddd37553337c5ed4418939293ccb from 1.1.4-12cb03fcf4474304824f71a72f6d6238 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/rulesets
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           └──[🔀] description (37319:32)
│ ├─┬/orgs/{org}/rulesets
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           └──[🔀] description (12617:32)
│ ├─┬/repos/{owner}/{repo}/rulesets/{ruleset_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           └──[🔀] description (37543:32)
│ └─┬/orgs/{org}/rulesets/{ruleset_id}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬target
│             └──[🔀] description (12837:32)
└─┬Components
  ├─┬repository-ruleset
  │ └─┬target
  │   └──[🔀] description (74766:24)
  └─┬repository-rule
    ├─┬ONEOF
    │ └──[🔀] $ref (74672:9)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74721:9)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74093:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74375:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74604:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74409:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74206:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74123:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74544:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74134:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74696:9)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74229:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74240:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74112:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74297:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74330:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74443:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74082:14)❌
    ├─┬ONEOF
    │ └──[🔀] $ref (74341:14)❌
    └─┬ONEOF
      ├──[🔀] title (74647:16)
      ├──[🔀] description (74648:22)
      ├─┬parameters
      │ ├──[➕] required (74671:15)❌
      │ ├──[➖] required (74673:15)❌
      │ ├──[➕] properties (74664:15)
      │ └──[➖] properties (74667:15)❌
      └─┬type
        ├──[➕] enum (74660:15)
        └──[➖] enum (74663:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 0                |
| components       | 28            | 23               |

Date: 09/11/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _23_ out of _32_
- **Modifications**: _26_
- **Removals**: _3_
- **Additions**: _3_
- **Breaking Removals**: _3_
- **Breaking Modifications**: _19_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered