[GitHubEnterprise-3.10] Update to 1.1.4-005dd1928c9baa727341c41207d49c50 from 1.1.4-c07b0de4f3982f5c42fa458767fa67d1 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 6f7ebe
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           └──[M] $ref (28435:19)❌
│ └─┬/repos/{owner}/{repo}/hooks
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬config
│             ├──[+] properties (28323:21)
│             └──[+] properties (28319:21)
└─┬Components
  └─┬hook
    └─┬config
      └──[M] $ref (77598:11)❌

Date: 01/13/24 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 1
components       | 1             | 1

❌  2 Breaking changes out of 4
INFO: Modifications: 2
INFO: Additions: 2
INFO: Breaking Modifications: 2

ERROR: breaking changes discovered