[GitHubEnterprise-3.11] Update to 1.1.4-7896308aac5721a0e0d051d14203a71b from 1.1.4-c4df960383e22391af612472d81b5566 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit ed64d5
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├──[-] path (32678:3)❌
│ ├──[+] path (32517:3)
│ ├─┬/repos/{owner}/{repo}/git/blobs/{file_sha}
│ │ └─┬GET
│ │   └──[M] description (28011:20)
│ ├─┬/issues
│ │ └─┬GET
│ │   └──[M] description (6604:20)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └──[-] description (6453:20)
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └──[M] description (34599:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (33677:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
│ │ └─┬PUT
│ │   └──[M] description (34410:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (33118:20)
│ │ └─┬PATCH
│ │   └──[M] description (33148:20)
│ ├─┬/users/{username}/starred
│ │ └─┬GET
│ │   └──[M] description (44980:20)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └──[M] description (41775:20)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (25212:20)
│ │ └─┬POST
│ │   └──[M] description (25248:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └──[M] description (30110:20)
│ │ └─┬PATCH
│ │   └──[M] description (30157:20)
│ ├─┬/gists/{gist_id}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (6128:20)
│ │ └─┬PATCH
│ │   └──[-] description (6167:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5853:20)
│ │ └─┬PATCH
│ │   └──[M] description (5885:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}
│ │ ├─┬GET
│ │ │ └──[M] description (34257:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (34288:20)
│ │ └─┬DELETE
│ │   └──[M] description (34336:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[M] description (33774:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments
│ │ └─┬GET
│ │   └──[M] description (34371:20)
│ ├─┬/gitignore/templates/{name}
│ │ └─┬GET
│ │   └──[M] description (6491:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └──[M] description (29733:20)
│ ├─┬/repos/{owner}/{repo}/comments
│ │ └─┬GET
│ │   └──[M] description (24786:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (30434:20)
│ │ └─┬POST
│ │   └──[M] description (30477:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[M] description (32867:20)
│ │ └─┬POST
│ │   └──[M] description (32959:20)
│ ├─┬/user/starred
│ │ └─┬GET
│ │   └──[M] description (43615:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └──[M] description (34641:20)
│ ├─┬/repos/{owner}/{repo}/stargazers
│ │ └─┬GET
│ │   └──[M] description (36086:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (29786:20)
│ │ └─┬PATCH
│ │   └──[M] description (29817:20)
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └─┬GET
│ │   └──[M] description (25641:20)
│ ├─┬/gists/{gist_id}/comments
│ │ ├─┬GET
│ │ │ └──[-] description (6019:20)
│ │ └─┬POST
│ │   └──[-] description (6064:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[M] description (29509:20)
│ │ └─┬POST
│ │   └──[M] description (29608:20)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └──[M] description (25732:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ ├─┬GET
│ │ │ └──[M] description (34102:20)
│ │ └─┬POST
│ │   ├──[M] description (34137:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬comments
│ │           └─┬Schema
│ │             └─┬position
│ │               └──[M] description (34197:38)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └──[M] description (25358:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
│ │ └─┬POST
│ │   └──[M] description (34469:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (33735:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (33487:20)
│ │ └─┬POST
│ │   ├──[M] description (33534:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬position
│ │           └──[M] description (33574:32)
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[M] description (11774:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments
│ │ └─┬GET
│ │   └──[M] description (33063:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (24046:20)
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (24889:20)
│ │ └─┬PATCH
│ │   └──[-] description (24927:20)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └──[M] description (31601:20)
│ └─┬/repos/{owner}/{repo}/pulls/{pull_number}
│   ├─┬GET
│   │ └──[M] description (33363:20)
│   └─┬PATCH
│     └──[M] description (33415:20)
└─┬Components
  ├─┬secret-scanning-alert-webhook
  │ └──[-] properties (88964:9)❌
  ├─┬page-deployment
  │ └─┬status_url
  │   └──[M] examples (82026:13)
  └─┬webhook-github-app-authorization-revoked
    ├──[+] properties (101058:9)
    ├──[+] properties (101060:9)
    ├──[+] properties (101062:9)
    └──[+] properties (101064:9)

Date: 01/25/24 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 60            | 1
components       | 6             | 1

❌  2 Breaking changes out of 66
INFO: Modifications: 51
INFO: Removals: 10
INFO: Additions: 5
INFO: Breaking Removals: 2

ERROR: breaking changes discovered