[GitHub] Update to 1.1.4-5a577f15b770f82145094bef33435130 from 1.1.4-863730273a226f6f485ea390e8766079 Detected Schema changes:
├──Paths
├──check-run-completed
└─┬Components
  ├──[-] schemas (69010:7)❌
  ├──[-] schemas (68990:7)❌
  ├─┬repository-rule
  │ ├──[-] oneOf (68820:7)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68711:14)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68722:14)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68666:14)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68779:14)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68809:14)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68922:14)❌
  │ ├─┬ONEOF
  │ │ └──[M] $ref (68636:14)❌
  │ └─┬ONEOF
  │   └──[M] $ref (68820:14)❌
  └─┬repository-rule-detailed
    ├──[-] oneOf (82091:9)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (81991:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (68820:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (68647:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (81991:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (81991:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (68809:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (68688:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (81991:14)❌
    ├─┬ONEOF
    │ └─┬ALLOF
    │   └──[M] $ref (68854:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (81991:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (68666:14)❌
    ├─┬ONEOF
    │ └─┬ALLOF
    │   └──[M] $ref (68711:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (68956:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (81991:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[M] $ref (81991:14)❌
    │ └─┬ALLOF
    │   └──[M] $ref (68636:14)❌
    └─┬ONEOF
      └─┬ALLOF
        └──[M] $ref (68922:14)❌

Date: 10/12/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 0             | 0
components       | 29            | 46
❌  46 Breaking changes out of 29
INFO: Modifications: 25
INFO: Removals: 4
INFO: Breaking Removals: 4
INFO: Breaking Modifications: 25

ERROR: breaking changes discovered