[GitHubAE] Update to 1.1.4 (hash: d020b34e05c305cccb8d37e80c27d949) from 1.1.4 (hash: 399de97e27391f2cc23286a97dfad2fa) Detected Schema changes:
├─┬Paths
│ ├─┬/app/installations
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/languages
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/gists/{gist_id}/commits
│ │ └──GET
│ ├─┬/
│ │ └──GET
│ ├─┬/markdown/raw
│ │ └──POST
│ ├─┬/licenses/{license}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/merge
│ │ ├──GET
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/merges
│ │ └──POST
│ ├─┬/app/installation-requests
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/projects/{project_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/user
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/teams/{team_id}/repos
│ │ └──GET
│ ├─┬/teams/{team_id}/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/installation
│ │ └──GET
│ ├─┬/orgs/{org}/audit-log
│ │ └──GET
│ ├─┬/users/{username}/gists
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/repos
│ │ └──GET
│ ├─┬/meta
│ │ └──GET
│ ├─┬/orgs/{org}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├──GET
│ │ └──POST
│ ├─┬/search/users
│ │ └──GET
│ ├─┬/search/topics
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/dispatches
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/update-branch
│ │ └──PUT
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/contributors
│ │ └──GET
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/users/{username}/installation
│ │ └──GET
│ ├─┬/user/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/codeowners/errors
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/users/{username}/projects
│ │ └──GET
│ ├─┬/gists
│ │ ├──GET
│ │ └──POST
│ ├─┬/app/installations/{installation_id}/suspended
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/gists/{gist_id}/star
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/keys
│ │ ├──GET
│ │ └──POST
│ ├─┬/user/orgs
│ │ └──GET
│ ├─┬/teams/{team_id}/projects
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/collaborators
│ │ └──GET
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/gitignore/templates
│ │ └──GET
│ ├─┬/app
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages/builds/latest
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/topics
│ │ ├──GET
│ │ └──PUT
│ ├─┬/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └──GET
│ ├─┬/emojis
│ │ └──GET
│ ├─┬/apps/{app_slug}
│ │ └──GET
│ ├─┬/codes_of_conduct/{key}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/search/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/branches/{branch}
│ │ └──GET
│ ├─┬/markdown
│ │ └──POST
│ ├─┬/app/installations/{installation_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/user/projects
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/deployments
│ │ ├──GET
│ │ └──POST
│ ├─┬/users
│ │ └──GET
│ ├─┬/search/commits
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/projects
│ │ └──GET
│ ├─┬/gists/public
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/orgs/{org}/issues
│ │ └──GET
│ ├─┬/orgs/{org}/code-scanning/alerts
│ │ └──GET
│ ├─┬/users/{username}/hovercard
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/tags
│ │ └──GET
│ ├─┬/rate_limit
│ │ └──GET
│ ├─┬/user/issues
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/gists/{gist_id}/{sha}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/deployments/{deployment_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/pulls
│ │ └──GET
│ ├─┬/gists/starred
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/teams/{team_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/codes_of_conduct
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/branches
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/gitignore/templates/{name}
│ │ └──GET
│ ├─┬/app-manifests/{code}/conversions
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/search/repositories
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └──GET
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/gists/{gist_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[+] additionalProperties (3577:37)
│ │         ├──[-] anyOf (3588:17)❌
│ │         ├──[-] anyOf (3586:17)❌
│ │         └─┬files
│ │           └──[M] additionalProperties (3561:21)
│ ├─┬/users/{username}/orgs
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├──GET
│ │ ├──PUT
│ │ ├──POST
│ │ └──DELETE
│ ├─┬/orgs/{org}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/keys/{key_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/users/{username}/repos
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits
│ │ └──GET
│ ├─┬/users/{username}
│ │ └──GET
│ ├─┬/orgs/{org}/repos
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/transfer
│ │ └──POST
│ ├─┬/search/labels
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/merge-upstream
│ │ └──POST
│ ├─┬/organizations
│ │ └──GET
│ ├─┬/gists/{gist_id}/forks
│ │ ├──GET
│ │ └──POST
│ ├─┬/zen
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/branches-where-head
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/orgs/{org}/teams/{team_slug}/teams
│ │ └──GET
│ ├─┬/octocat
│ │ └──GET
│ ├─┬/licenses
│ │ └──GET
│ ├─┬/search/code
│ │ └──GET
│ ├─┬/orgs/{org}/installations
│ │ └──GET
│ ├─┬/user/repos
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/license
│ │ └──GET
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └──POST
│ └─┬/orgs/{org}/installation
│   └──GET
└─┬check-run-requested-action
  └──POST

Date: 06/28/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 2
❌ 2 Breaking changes out of 4

ERROR: breaking changes discovered