[GitHubEnterprise-3.7] Update to 1.1.4-4d108d59b9e6aa7fd00cdf99eb5240fc from 1.1.4-6bb8ced52321c546adfb89050631db20 Detected Schema changes:
├─┬Paths
│ ├─┬/orgs/{org}/migrations
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬exclude
│ │           └──[M] description (10585:32)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         └──[M] value (206415:9)
│   └─┬PUT
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (206415:9)
├─┬ping
│ └──POST
└─┬Components
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (79989:28)
  ├─┬webhook-check-suite-requested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (80603:28)
  ├─┬environment
  │ └─┬protection_rules
  │   └─┬Schema
  │     └─┬ANYOF
  │       └──[+] properties (69750:17)
  ├─┬webhook-deployment-status-created
  │ └─┬check_run
  │   └─┬conclusion
  │     └──[M] description (87018:28)
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (81787:28)
  ├─┬full-repository
  │ └──[+] required (65064:9)❌
  ├─┬webhook-code-scanning-alert-fixed
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (82294:28)
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (81210:28)
  └─┬webhook-code-scanning-alert-appeared-in-branch
    └─┬alert
      └─┬dismissed_reason
        └──[M] description (81529:28)

Date: 10/05/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 0
components       | 9             | 1
❌  1 Breaking changes out of 12
INFO: Modifications: 10
INFO: Additions: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered