[GitHub] Update to 1.1.4-4f074e36604109b0a5cfe5fde6c79805 from 1.1.4-43512e093bc0645d14a6d505678dad79 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 524808
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

└─┬Components
  ├──[-] schemas (71467:7)❌
  ├──[-] schemas (71451:7)❌
  └─┬org-ruleset-conditions
    ├──[-] oneOf (71497:9)❌
    ├─┬ONEOF
    │ ├──[M] title (71466:16)
    │ ├──[M] description (71467:22)
    │ └─┬ALLOF
    │   └──[M] $ref (71435:14)❌
    └─┬ONEOF
      ├──[M] title (71460:16)
      ├──[M] description (71461:22)
      └─┬ALLOF
        └──[M] $ref (71409:14)❌

Date: 01/31/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 9             | 7

❌  7 Breaking changes out of 9
INFO: Modifications: 6
INFO: Removals: 3
INFO: Breaking Removals: 3
INFO: Breaking Modifications: 2

ERROR: breaking changes discovered