[GitHubEnterprise-3.13] Update to 1.1.4-8985016ac4b27cc23057fb31dee10264 from 1.1.4-446a3cd1fdbd8dda94d848b89bd8f6e2 Detected Schema changes:
```
└─┬Paths
  ├─┬/enterprises/{enterprise}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (214872:20)
  │     └─┬Schema
  │       └──[➕] enum (214882:11)
  ├─┬/repos/{owner}/{repo}/dependabot/alerts
  │ └─┬GET
  │   ├──[➕] parameters (214885:13)❌
  │   ├──[➕] parameters (27608:15)❌
  │   ├──[➕] parameters (214609:13)❌
  │   ├──[➕] parameters (214618:13)❌
  │   ├──[➕] parameters (27600:15)❌
  │   ├──[➕] parameters (214898:13)❌
  │   └─┬Parameters
  │     ├──[🔀] description (214872:20)
  │     └─┬Schema
  │       └──[➕] enum (214882:11)
  └─┬/orgs/{org}/dependabot/alerts
    └─┬GET
      └─┬Parameters
        ├──[🔀] description (214872:20)
        └─┬Schema
          └──[➕] enum (214882:11)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 6                |

Date: 01/21/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _12_
- **Modifications**: _3_
- **Additions**: _9_
- **Breaking Additions**: _6_

ERROR: breaking changes discovered