[GitHubAE] Update to 1.1.4 (hash: 55bc2b5ac90592f60e22cc43c3bcbdb5) from 1.1.4 (hash: c7522dcb916d70416a6b29950b73fbc6) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (184400:9)
│ └─┬/repos/{owner}/{repo}/actions/runs
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (184400:9)
├──secret-scanning-alert-location-created
└─┬Components
  ├─┬webhook-branch-protection-rule-created
  │ └─┬rule
  │   └──[-] properties (65754:13)❌
  ├─┬webhook-branch-protection-rule-deleted
  │ └─┬rule
  │   └──[-] properties (65907:13)❌
  └─┬webhook-branch-protection-rule-edited
    └─┬rule
      └──[-] properties (66131:13)❌

Date: 06/17/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 2             | 0
components       | 3             | 3
❌ 3 Breaking changes out of 5

ERROR: breaking changes discovered