[GitHubEnterprise-3.15] Update to 1.1.4-a52c4c09b475fc1c0194c7e656ee966d from 1.1.4-9c88bf9f401b8678777d4212dacc4985 Detected Schema changes:
```
├─┬Paths
│ ├─┬/search/issues
│ │ └─┬GET
│ │   └──[➖] parameters (218457:13)❌
│ ├─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬403
│ │       └──[🔀] description (218745:20)
│ └─┬/zen
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         ├──[➕] content (48400:15)
│         └──[➖] content (48401:15)❌
└─┬Components
  └──[➖] parameters (218457:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 2                |
| components       | 1             | 1                |

Date: 03/01/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _5_
- **Modifications**: _1_
- **Removals**: _3_
- **Additions**: _1_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered