[GitHubAE] Update to 1.1.4-ed5808c1d3a8b2350deb978276a97387 from 1.1.4-9f4d4c650bdcedb87ba86bd4ef652f7e Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 81ae8f
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[M] description (25245:20)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └──[-] description (4094:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └──[M] description (17725:20)
│ ├─┬/gists/{gist_id}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (3769:20)
│ │ └─┬PATCH
│ │   └──[-] description (3808:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments
│ │ └─┬GET
│ │   └──[M] description (25842:20)
│ ├─┬/user/starred
│ │ └─┬GET
│ │   └──[M] description (31585:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ ├─┬GET
│ │ │ └──[M] description (25573:20)
│ │ └─┬POST
│ │   ├──[M] description (25608:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬comments
│ │           └─┬Schema
│ │             └─┬position
│ │               └──[M] description (25668:38)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[M] description (24319:20)
│ │ └─┬POST
│ │   └──[M] description (24411:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └──[M] description (21757:20)
│ │ └─┬PATCH
│ │   └──[M] description (21804:20)
│ ├─┬/gitignore/templates/{name}
│ │ └─┬GET
│ │   └──[M] description (4132:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}
│ │ ├─┬GET
│ │ │ └──[M] description (25728:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (25759:20)
│ │ └─┬DELETE
│ │   └──[M] description (25807:20)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (17579:20)
│ │ └─┬POST
│ │   └──[M] description (17615:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (25206:20)
│ ├─┬/repos/{owner}/{repo}/git/blobs/{file_sha}
│ │ └─┬GET
│ │   └──[M] description (19625:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (16479:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[M] description (21123:20)
│ │ └─┬POST
│ │   └──[M] description (21222:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (24964:20)
│ │ └─┬POST
│ │   ├──[M] description (25011:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬position
│ │           └──[M] description (25051:32)
│ ├─┬/repos/{owner}/{repo}/stargazers
│ │ └─┬GET
│ │   └──[M] description (27065:20)
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[M] description (7212:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └──[M] description (21347:20)
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └──[M] description (26070:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └──[-] description (3494:20)
│ │ └─┬PATCH
│ │   └──[M] description (3526:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (24562:20)
│ │ └─┬PATCH
│ │   └──[M] description (24592:20)
│ ├─┬/users/{username}/starred
│ │ └─┬GET
│ │   └──[M] description (32401:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments
│ │ └─┬GET
│ │   └──[M] description (24507:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └──[M] description (26112:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (22081:20)
│ │ └─┬POST
│ │   └──[M] description (22124:20)
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └─┬GET
│ │   └──[M] description (18008:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
│ │ └─┬POST
│ │   └──[M] description (25940:20)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └──[M] description (23281:20)
│ ├─┬/issues
│ │ └─┬GET
│ │   └──[M] description (4245:20)
│ ├─┬/gists/{gist_id}/comments
│ │ ├─┬GET
│ │ │ └──[-] description (3660:20)
│ │ └─┬POST
│ │   └──[-] description (3705:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
│ │ └─┬PUT
│ │   └──[M] description (25881:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (25148:20)
│ ├─┬/repos/{owner}/{repo}/comments
│ │ └─┬GET
│ │   └──[M] description (17118:20)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └──[M] description (30431:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├─┬GET
│ │ │ └──[M] description (24840:20)
│ │ └─┬PATCH
│ │   └──[M] description (24892:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (21400:20)
│ │ └─┬PATCH
│ │   └──[M] description (21431:20)
│ └─┬/repos/{owner}/{repo}/comments/{comment_id}
│   ├─┬GET
│   │ └──[-] description (17221:20)
│   └─┬PATCH
│     └──[-] description (17259:20)
└─┬Components
  ├─┬secret-scanning-alert-webhook
  │ └──[-] properties (67664:9)❌
  └─┬webhook-github-app-authorization-revoked
    ├──[+] properties (79638:9)
    ├──[+] properties (79640:9)
    ├──[+] properties (79642:9)
    └──[+] properties (79644:9)

Date: 01/25/24 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 57            | 0
components       | 5             | 1

❌  1 Breaking changes out of 62
INFO: Modifications: 49
INFO: Removals: 9
INFO: Additions: 4
INFO: Breaking Removals: 1

ERROR: breaking changes discovered