[GitHubEnterprise-3.6] Update to 1.1.4-36c4d728215d3ca0692d176c31bf3a4d from 1.1.4-c825f39066ae2bb949dea996cb2e4b4b Detected Schema changes:
├─┬Paths
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └──[M] $ref (52443:14)❌
└─┬Components
  └──[-] schemas (52443:7)❌

Date: 09/30/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 1             | 1
components       | 1             | 1
❌  2 Breaking changes out of 2
INFO: Modifications: 1
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered