[GitHub] Update to 1.1.4-6427e6326d9646fc1b49f1e1dcf2d9db from 1.1.4-e19bc15f772c4b3caf0034592e8e59db Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit ec92be
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/app/hook/deliveries
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193833:7)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (193857:9)
│ │           └──[➖] value (193875:9)
│ ├─┬/app/hook/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (193857:9)
│ │           └──[➖] value (193875:9)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193833:7)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (193833:7)
│ └─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (193857:9)
│             └──[➖] value (193875:9)
└─┬Components
  ├─┬hook-delivery
  │ └──[➖] properties (63417:9)❌
  └─┬hook-delivery-item
    └──[➖] properties (63259:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 9             | 0                |
| components       | 2             | 2                |

Date: 05/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _11_
- **Modifications**: _6_
- **Removals**: _5_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered