[GitHubEnterprise-3.4] Update to 1.1.4 (hash: 0e65d7ec49097948096fee56b2da94c9) from 1.1.4 (hash: 794db5c2d8b19663f7ad576b0caa3050) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/statuses
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (20610:22)
│ ├─┬/user/starred/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └──[-] description (35962:20)
│ │ └─┬DELETE
│ │   └──[-] description (36023:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/status
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (20568:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (20502:22)
│ ├─┬/repos/{owner}/{repo}/git/refs/{ref}
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (22997:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (20431:22)
│ ├─┬/repos/{owner}/{repo}/git/ref/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (22838:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (20386:22)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   ├──[M] summary (22715:16)
│ │   └──[M] description (22716:20)
│ ├─┬/repos/{owner}/{repo}/git/matching-refs/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (22795:22)
│ ├─┬/repos/{owner}/{repo}/subscription
│ │ └─┬GET
│ │   └──[-] description (30451:20)
│ └─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│   └─┬GET
│     └──[M] description (19738:20)
└─┬Components
  └──[-] parameters (77010:7)❌

Date: 06/14/23 | Commit: New: etc/specs/GitHubEnterprise-3.4/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.4/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 14            | 0
components       | 1             | 1
❌ 1 Breaking changes out of 15

ERROR: breaking changes discovered