[GitHubEnterprise-3.8] Update to 1.1.4-2564814536b135e1729b19f8b0486fff from 1.1.4-a10350ad5557637772c2f25be0189a2c Detected Schema changes:
├─┬Paths
│ ├─┬/admin/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/admin/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (34259:20)
│ │ └─┬POST
│ │   └──[M] description (34307:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (16467:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (34362:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (34441:20)
│ │ └─┬PATCH
│ │   └──[M] description (34396:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (17822:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (17901:20)
│ │ └─┬PATCH
│ │   └──[M] description (17856:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (16583:20)
│ │ └─┬DELETE
│ │   └──[M] description (16617:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (16418:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (209209:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (209209:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (16541:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (17161:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (16503:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (16813:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (17720:20)
│ │ └─┬POST
│ │   └──[M] description (17767:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (218166:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (218166:20)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   └──[M] description (15983:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (16645:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (16727:20)
│ │ ├─┬POST
│ │ │ └──[M] description (16674:20)
│ │ └─┬DELETE
│ │   └──[M] description (16782:20)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│   └─┬POST
│     └─┬Parameters
│       └──[M] description (218166:20)
└─┬Components
  └─┬environment
    └─┬protection_rules
      └─┬Schema
        └─┬ANYOF
          └──[-] properties (71926:17)❌

Date: 09/26/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 48            | 0
components       | 1             | 1
❌  1 Breaking changes out of 49
INFO: Modifications: 48
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered