[GitHub] Update to 1.1.4-c6249831ad99957f8d160f21b8d426dd from 1.1.4-24f4c3ebacf1ca5821698e28d77d32d1 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/copilot/billing/seats
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (199332:9)
│ ├─┬/orgs/{org}/members/{username}/copilot
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (203430:9)
│ │           └──[➖] value (203448:9)
│ ├─┬/enterprises/{enterprise}/copilot/billing/seats
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (199332:9)
│ └─┬/orgs/{org}/copilot/billing
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (202912:9)
│             ├──[🔀] value (202912:9)
│             ├──[🔀] value (202912:9)
│             ├──[🔀] value (202912:9)
│             └──[➖] value (202929:9)
└─┬Components
  ├─┬copilot-organization-details
  │ └──[➖] properties (72221:9)❌
  └─┬copilot-seat-details
    └──[➖] properties (67568:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 9             | 0                |
| components       | 2             | 2                |

Date: 10/08/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _11_
- **Modifications**: _7_
- **Removals**: _4_
- **Breaking Removals**: _2_

ERROR: breaking changes discovered