[GitHubEnterprise-3.9] Update to 1.1.4-6a07c770b153662571e5bc77530deccb from 1.1.4-ca55fee682516827afc096c706b2f986 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit b02634
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├──[-] path (30938:3)❌
│ ├──[+] path (30777:3)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ └─┬GET
│ │   └──[M] description (24212:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/dismissals
│ │ └─┬PUT
│ │   └──[M] description (32670:20)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └──[M] description (29861:20)
│ ├─┬/users/{username}/starred
│ │ └─┬GET
│ │   └──[M] description (42891:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments
│ │ └─┬GET
│ │   └──[M] description (27993:20)
│ ├─┬/repos/{owner}/{repo}/stargazers
│ │ └─┬GET
│ │   └──[M] description (34012:20)
│ ├─┬/repos/{owner}/{repo}/git/blobs/{file_sha}
│ │ └─┬GET
│ │   └──[M] description (26271:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (31995:20)
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └─┬GET
│ │   └──[M] description (24121:20)
│ ├─┬/repos/{owner}/{repo}/comments
│ │ └─┬GET
│ │   └──[M] description (23266:20)
│ ├─┬/repos/{owner}/{repo}/readme/{dir}
│ │ └─┬GET
│ │   └──[M] description (32901:20)
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[M] description (11302:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/comments
│ │ └─┬GET
│ │   └──[M] description (32631:20)
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └──[M] description (32859:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}/events
│ │ └─┬POST
│ │   └──[M] description (32729:20)
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (28046:20)
│ │ └─┬PATCH
│ │   └──[M] description (28077:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (22526:20)
│ ├─┬/gists/{gist_id}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5830:20)
│ │ └─┬PATCH
│ │   └──[-] description (5869:20)
│ ├─┬/user/starred
│ │ └─┬GET
│ │   └──[M] description (41526:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └─┬GET
│ │   └──[M] description (32034:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[M] description (27769:20)
│ │ └─┬POST
│ │   └──[M] description (27868:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
│ │ └─┬POST
│ │   └──[M] description (31937:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (28694:20)
│ │ └─┬POST
│ │   └──[M] description (28737:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (31747:20)
│ │ └─┬POST
│ │   ├──[M] description (31794:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬position
│ │           └──[M] description (31834:32)
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/comments
│ │ ├─┬GET
│ │ │ └──[M] description (23692:20)
│ │ └─┬POST
│ │   └──[M] description (23728:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews
│ │ ├─┬GET
│ │ │ └──[M] description (32362:20)
│ │ └─┬POST
│ │   ├──[M] description (32397:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬comments
│ │           └─┬Schema
│ │             └─┬position
│ │               └──[M] description (32457:38)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/reviews/{review_id}
│ │ ├─┬GET
│ │ │ └──[M] description (32517:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (32548:20)
│ │ └─┬DELETE
│ │   └──[M] description (32596:20)
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├─┬GET
│ │ │ └──[M] description (31127:20)
│ │ └─┬POST
│ │   └──[M] description (31219:20)
│ ├─┬/gitignore/templates/{name}
│ │ └─┬GET
│ │   └──[M] description (6193:20)
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[-] description (23369:20)
│ │ └─┬PATCH
│ │   └──[-] description (23407:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
│ │ ├─┬GET
│ │ │ └──[M] description (31378:20)
│ │ └─┬PATCH
│ │   └──[M] description (31408:20)
│ ├─┬/gists/{gist_id}/comments
│ │ ├─┬GET
│ │ │ └──[-] description (5721:20)
│ │ └─┬POST
│ │   └──[-] description (5766:20)
│ ├─┬/repos/{owner}/{repo}/pulls/comments
│ │ └─┬GET
│ │   └──[M] description (31323:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └──[M] description (23838:20)
│ ├─┬/gists/{gist_id}
│ │ ├─┬GET
│ │ │ └──[-] description (5555:20)
│ │ └─┬PATCH
│ │   └──[M] description (5587:20)
│ ├─┬/gists/{gist_id}/{sha}
│ │ └─┬GET
│ │   └──[-] description (6155:20)
│ ├─┬/user/issues
│ │ └─┬GET
│ │   └──[M] description (39686:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├─┬GET
│ │ │ └──[M] description (31623:20)
│ │ └─┬PATCH
│ │   └──[M] description (31675:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├─┬GET
│ │ │ └──[M] description (28370:20)
│ │ └─┬PATCH
│ │   └──[M] description (28417:20)
│ └─┬/issues
│   └─┬GET
│     └──[M] description (6306:20)
└─┬Components
  ├─┬webhook-github-app-authorization-revoked
  │ ├──[+] properties (96613:9)
  │ ├──[+] properties (96615:9)
  │ ├──[+] properties (96617:9)
  │ └──[+] properties (96619:9)
  ├─┬secret-scanning-alert-webhook
  │ └──[-] properties (84608:9)❌
  └─┬page-deployment
    └─┬status_url
      └──[M] examples (77872:13)

Date: 01/24/24 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 60            | 1
components       | 6             | 1

❌  2 Breaking changes out of 66
INFO: Modifications: 51
INFO: Removals: 10
INFO: Additions: 5
INFO: Breaking Removals: 2

ERROR: breaking changes discovered