[GitHub] Update to 1.1.4-77f428b6792170784451c1bba9fcab99 from 1.1.4-08747ed797271fdcb119e705571bb8c5 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 7da73b
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/properties/values
│ │ └──[-] patch (31940:7)❌
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           └──[M] $ref (27605:19)❌
│ ├─┬/orgs/{org}/properties/schema
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (217260:7)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       └──[M] value (217260:7)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[M] value (10879:19)
│ └─┬/repos/{owner}/{repo}/hooks
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬config
│             ├──[+] properties (27493:21)
│             └──[+] properties (27489:21)
└─┬Components
  ├──[-] examples (227294:7)❌
  ├─┬hook
  │ └─┬config
  │   └──[M] $ref (79568:11)❌
  ├─┬full-repository
  │ └──[-] properties (70769:9)❌
  └─┬org-custom-property
    └──[-] properties (70212:9)❌

Date: 01/14/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 7             | 2
components       | 4             | 4

❌  6 Breaking changes out of 11
INFO: Modifications: 5
INFO: Removals: 4
INFO: Additions: 2
INFO: Breaking Removals: 4
INFO: Breaking Modifications: 2

ERROR: breaking changes discovered