[GitHubEnterprise-3.10] Update to 1.1.4-fc9b0342e7d3854aac2fabfcd852d60d from 1.1.4-d06a93798efe69da37d08944b288998b Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit ce06ef
                                                                                └─┬Paths
  └─┬/repos/{owner}/{repo}/autolinks
    └─┬GET
      ├──[+] parameters (224719:13)❌
      ├──[M] summary (20054:16)
      ├──[M] description (20055:20)
      └─┬External Docs
        └──[M] url (20064:14)

                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

Date: 02/02/24 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 1

❌  1 Breaking changes out of 4
INFO: Modifications: 3
INFO: Additions: 1
INFO: Breaking Additions: 1

ERROR: breaking changes discovered