[GitHubEnterprise-3.13] Update to 1.1.4-ffac604ed0c1f24261dd953b32c2fba3 from 1.1.4-802a0cd5a04204e42ef5ea0492e36a70 Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│   └─┬PATCH
│     ├─┬Responses
│     │ └──[➖] codes (216171:7)❌
│     └─┬Requestbody
│       └─┬application/json
│         ├─┬Schema
│         │ └──[➖] properties (25294:17)❌
│         └─┬default
│           ├──[🔀] value (25299:19)
│           ├──[🔀] value (25299:19)
│           ├──[🔀] value (25299:19)
│           └──[➖] value (25301:19)
└─┬Components
  └──[➖] schemas (80287:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 6             | 2                |
| components       | 1             | 1                |

Date: 03/08/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _7_
- **Modifications**: _3_
- **Removals**: _4_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered