[GitHubEnterprise-3.6] Update to 1.1.4 (hash: cf1b70572b1ab7333e61ca043fe8d580) from 1.1.4 (hash: 4112bd6573be1bd454259053402d8b3e) Detected Schema changes:
├─┬Paths
│ ├─┬/search/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/branches-where-head
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/tags
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/markdown
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/deployments
│ │ ├──GET
│ │ └──POST
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └──GET
│ ├─┬/zen
│ │ └──GET
│ ├─┬/authorizations
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/gists/{gist_id}/star
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/search/code
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/update-branch
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/compare/{basehead}
│ │ └──GET
│ ├─┬/teams/{team_id}/projects
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/branches/{branch}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/installation
│ │ └──GET
│ ├─┬/teams/{team_id}/repos
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └──GET
│ ├─┬/orgs/{org}/teams
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └──GET
│ ├─┬/app/installations
│ │ └──GET
│ ├─┬/user/projects
│ │ └──POST
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/licenses
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/branches
│ │ └──GET
│ ├─┬/user/issues
│ │ └──GET
│ ├─┬/markdown/raw
│ │ └──POST
│ ├─┬/users/{username}/repos
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/dispatches
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/comments/{comment_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/codeowners/errors
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/transfer
│ │ └──POST
│ ├─┬/applications/grants/{grant_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/projects/{project_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └──POST
│ ├─┬/orgs/{org}/installations
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/search/users
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/merges
│ │ └──POST
│ ├─┬/teams/{team_id}/discussions/{discussion_number}/comments/{comment_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/emojis
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/license
│ │ └──GET
│ ├─┬/orgs/{org}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └──POST
│ ├─┬/apps/{app_slug}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/keys/{key_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/replicas/caches
│ │ └──GET
│ ├─┬/search/topics
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/languages
│ │ └──GET
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/users/{username}/installation
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/merge-upstream
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/issues
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/commits
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pages
│ │ ├──GET
│ │ ├──PUT
│ │ ├──POST
│ │ └──DELETE
│ ├─┬/authorizations/clients/{client_id}
│ │ └──PUT
│ ├─┬/orgs/{org}/repos
│ │ ├─┬GET
│ │ │ └──[M] description (11190:20)
│ │ └──POST
│ ├─┬/gists/starred
│ │ └──GET
│ ├─┬/user/orgs
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/gists
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/projects
│ │ └──GET
│ ├─┬/licenses/{license}
│ │ └──GET
│ ├─┬/orgs/{org}/audit-log
│ │ └──GET
│ ├─┬/user/repos
│ │ ├──GET
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/repos
│ │ └──GET
│ ├─┬/codes_of_conduct/{key}
│ │ └──GET
│ ├─┬/users/{username}/hovercard
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/contributors
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/search/labels
│ │ └──GET
│ ├─┬/app/installation-requests
│ │ └──GET
│ ├─┬/organizations
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/app/installations/{installation_id}/suspended
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/teams/{team_id}/teams
│ │ └──GET
│ ├─┬/repositories
│ │ └──GET
│ ├─┬/teams/{team_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └──GET
│ ├─┬/octocat
│ │ └──GET
│ ├─┬/gitignore/templates
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/gists/public
│ │ └──GET
│ ├─┬/orgs/{org}/settings/billing/advanced-security
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/keys
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/topics
│ │ ├──GET
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}/projects
│ │ └──GET
│ ├─┬/orgs/{org}/code-scanning/alerts
│ │ └──GET
│ ├─┬/authorizations/{authorization_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └──PATCH
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └──GET
│ ├─┬/search/repositories
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/merge
│ │ ├──GET
│ │ └──PUT
│ ├─┬/applications/grants
│ │ └──GET
│ ├─┬/users/{username}/gists
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/branches/{branch}/rename
│ │ └──POST
│ ├─┬/app/installations/{installation_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/users
│ │ └──GET
│ ├─┬/gists/{gist_id}/{sha}
│ │ └──GET
│ ├─┬/users/{username}/orgs
│ │ └──GET
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/deployments/{deployment_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls
│ │ ├──GET
│ │ └──POST
│ ├─┬/authorizations/clients/{client_id}/{fingerprint}
│ │ └──PUT
│ ├─┬/repos/{owner}/{repo}/pages/builds/latest
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ ├──GET
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}
│ │ ├──GET
│ │ └──PATCH
│ ├─┬/repos/{owner}/{repo}/commits/{commit_sha}/pulls
│ │ └──GET
│ ├─┬/orgs/{org}/issues
│ │ └──GET
│ ├─┬/codes_of_conduct
│ │ └──GET
│ ├─┬/user/teams
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/collaborators
│ │ └──GET
│ ├─┬/app
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └──GET
│ ├─┬/gists/{gist_id}
│ │ ├──GET
│ │ ├──DELETE
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[+] additionalProperties (5382:37)
│ │         ├──[-] anyOf (5393:17)❌
│ │         ├──[-] anyOf (5391:17)❌
│ │         └─┬files
│ │           └──[M] additionalProperties (5366:21)
│ ├─┬/app-manifests/{code}/conversions
│ │ └──POST
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ ├──GET
│ │ ├──PUT
│ │ └──DELETE
│ ├─┬/gists/{gist_id}/commits
│ │ └──GET
│ ├─┬/search/commits
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/files
│ │ └──GET
│ ├─┬/orgs/{org}/projects
│ │ ├──GET
│ │ └──POST
│ ├─┬/users/{username}
│ │ └──GET
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └──GET
│ ├─┬/orgs/{org}/installation
│ │ └──GET
│ ├─┬/orgs/{org}/teams/{team_slug}/discussions/{discussion_number}/reactions/{reaction_id}
│ │ └──DELETE
│ ├─┬/meta
│ │ └──GET
│ ├─┬/gitignore/templates/{name}
│ │ └──GET
│ ├─┬/gists/{gist_id}/forks
│ │ ├──GET
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/pages/builds
│ │ ├──GET
│ │ └──POST
│ ├─┬/rate_limit
│ │ └──GET
│ ├─┬/user
│ │ ├──GET
│ │ └──PATCH
│ └─┬/
│   └──GET
└─┬Components
  └─┬minimal-repository
    └──[+] properties (44754:9)

Date: 06/28/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 2
components       | 1             | 0
❌ 2 Breaking changes out of 6

ERROR: breaking changes discovered