[GitHub] Update to 1.1.4-4d0175f50c5e15e911018fc5f4b5fee8 from 1.1.4-3eab7bc09a6d3be61aedace0f4ddc61d Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 3e215b
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├──[➖] path (22381:3)❌
│ ├──[➖] path (22551:3)❌
│ ├──[➖] path (22509:3)❌
│ └──[➕] path (12505:3)
├─┬Tags
│ └──[➖] enterprise-teams (90:3)❌
└─┬Components
  ├──[➖] examples (206216:7)❌
  ├──[➖] examples (206366:7)❌
  ├──[➖] schemas (77709:7)❌
  ├──[➖] schemas (77728:7)❌
  ├──[➖] schemas (77646:7)❌
  ├──[➖] schemas (77848:7)❌
  ├──[➖] schemas (77699:7)❌
  └──[➖] schemas (77658:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 3                |
| tags             | 1             | 1                |
| components       | 8             | 8                |

Date: 05/10/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _13_
- **Removals**: _12_
- **Additions**: _1_
- **Breaking Removals**: _12_

ERROR: breaking changes discovered