[GitHub] Update to 1.1.4-b1df7aeeba72bb96f2ca61a7edd34136 from 1.1.4-46eadb305342d3e08e981c8d774b0cb1 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (15655:3)❌
│ ├──[➖] path (15545:3)❌
│ ├──[➖] path (15775:3)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/sub_issues
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬sub_issue_id
│ │           └──[🔀] description (35149:32)
│ ├─┬/enterprises/{enterprise}/dependabot/alerts
│ │ └─┬GET
│ │   └──[➖] parameters (229136:13)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/sub_issue
│ │ └─┬DELETE
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬sub_issue_id
│ │           └──[🔀] description (35035:32)
│ ├─┬/orgs/{org}/dependabot/alerts
│ │ └─┬GET
│ │   └──[➖] parameters (229136:13)❌
│ └─┬/repos/{owner}/{repo}/dependabot/alerts
│   └─┬GET
│     └──[➖] parameters (229136:13)❌
├─┬Tags
│ └──[➖] hosted-compute (96:3)❌
└─┬Components
  ├──[➖] parameters (229136:7)❌
  ├──[➖] parameters (229876:7)❌
  ├──[➖] parameters (229883:7)❌
  ├──[➖] examples (211282:7)❌
  ├──[➖] examples (211309:7)❌
  ├──[➖] examples (211300:7)❌
  ├──[➖] schemas (79931:7)❌
  └──[➖] schemas (79973:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 6                |
| tags             | 1             | 1                |
| components       | 8             | 8                |

Date: 01/20/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _15_ out of _17_
- **Modifications**: _2_
- **Removals**: _15_
- **Breaking Removals**: _15_

ERROR: breaking changes discovered