[GitHubEnterprise-3.10] Update to 1.1.4-213496300af3b5fcd5021fed4cdca2d0 from 1.1.4-2319ab0751e6b9e88e61e92937ac4cfc Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 40f679                                                                                 SPEC: extracted 2 commits from history                                                                                 DONE: completed
WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [63317:7]

├─┬Paths
│ ├─┬/markdown/raw
│ │ └─┬POST
│ │   └──Requestbody
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (39673:32)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └──[M] description (19861:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (15561:20)
│ ├─┬/user/starred/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (42748:20)
│ ├─┬/teams/{team_id}/members/{username}
│ │ └─┬PUT
│ │   └──[M] description (39355:20)
│ ├─┬/users/{username}/site_admin
│ │ └─┬PUT
│ │   └──[M] description (43919:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ └─┬PUT
│ │   └──[M] description (13474:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (15413:32)
│ ├─┬/users/{username}
│ │ └─┬GET
│ │   └──[M] description (42933:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/jobs
│ │ └─┬GET
│ │   └──[M] description (18950:20)
│ ├─┬/user/following/{username}
│ │ └─┬PUT
│ │   └──[M] description (40418:20)
│ ├─┬/gists/{gist_id}/star
│ │ └─┬PUT
│ │   └──[M] description (6159:20)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (39834:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ └─┬PUT
│ │   └──[M] description (30262:20)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ └─┬PUT
│ │   └──[M] description (24007:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └──[M] description (18560:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs
│ │ └─┬GET
│ │   └──[M] description (18787:20)
│ └─┬/users/{username}/suspended
│   └─┬PUT
│     └──[M] description (44106:20)
├──secret-scanning-alert-location-created
└─┬Components
  ├─┬code-scanning-organization-alert-items
  │ └─┬rule
  │   └──[M] $ref (65057:13)❌
  └─┬code-scanning-alert-rule-summary
    └──[-] properties (65085:9)❌

Date: 12/16/23 | Commit: New: etc/specs/GitHubEnterprise-3.10/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.10/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 18            | 0
components       | 2             | 2

❌  2 Breaking changes out of 20
INFO: Modifications: 19
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered