[GitHubEnterprise-3.9] Update to 1.1.4 (hash: ef6250d64a7b98f4c7b1fca31893f33f) from 1.1.4 (hash: 098981175e8fbf0284572b5c5b4e6659) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/releases/assets/{asset_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33759:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33842:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (33791:14)
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}/assets
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (34137:14)
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (34197:14)
│ ├─┬/repos/{owner}/{repo}/releases
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (33617:14)
│ │ └──POST
│ ├─┬/repos/{owner}/{repo}/releases/{release_id}
│ │ ├─┬GET
│ │ │ └─┬External Docs
│ │ │   └──[M] url (34005:14)
│ │ ├─┬DELETE
│ │ │ └─┬External Docs
│ │ │   └──[M] url (34115:14)
│ │ └─┬PATCH
│ │   └─┬External Docs
│ │     └──[M] url (34036:14)
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   └──[M] description (27132:20)
│ ├─┬/repos/{owner}/{repo}/releases/tags/{tag}
│ │ └─┬GET
│ │   └─┬External Docs
│ │     └──[M] url (33967:14)
│ ├─┬/repos/{owner}/{repo}/git/commits
│ │ └─┬POST
│ │   └──[M] description (26963:20)
│ ├─┬/gists/{gist_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[-] additionalProperties (5636:37)
│ │         ├──[+] anyOf (5646:17)
│ │         ├──[+] anyOf (5644:17)
│ │         └─┬files
│ │           └──[M] additionalProperties (5620:21)
│ ├─┬/repos/{owner}/{repo}/releases/generate-notes
│ │ └─┬POST
│ │   └─┬External Docs
│ │     └──[M] url (33868:14)
│ └─┬/repos/{owner}/{repo}/releases/latest
│   └─┬GET
│     └─┬External Docs
│       └──[M] url (33939:14)
└─┬Components
  ├──[-] schemas (73390:7)❌
  ├─┬check-run
  │ └─┬pull_requests
  │   └──[-] description (72874:24)
  ├─┬code-scanning-default-setup-update
  │ └─┬query_suite
  │   └──[M] $ref (73405:11)❌
  └─┬workflow-run
    └─┬pull_requests
      └──[-] description (71253:24)

Date: 06/27/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 18            | 0
components       | 4             | 2
❌ 2 Breaking changes out of 22

ERROR: breaking changes discovered