[GitHubEnterprise-3.7] Update to 1.1.4 (hash: 902cb707c94a50998ee64fcc677689b6) from 1.1.4 (hash: 2a371a4f6cd046023d123d932b8186eb) Detected Schema changes:
├──Paths
└─┬Components
  ├──[-] schemas (77943:7)❌
  ├──[-] schemas (77930:7)❌
  ├─┬webhook-secret-scanning-alert-location-created
  │ └─┬alert
  │   └──[M] $ref (74353:13)❌
  ├─┬webhook-secret-scanning-alert-reopened
  │ └─┬alert
  │   └──[M] $ref (74353:13)❌
  ├─┬webhook-secret-scanning-alert-created
  │ └─┬alert
  │   └──[M] $ref (74353:13)❌
  ├─┬webhook-secret-scanning-alert-resolved
  │ └─┬alert
  │   └──[M] $ref (179268:11)❌
  └─┬webhook-secret-scanning-alert-revoked
    └─┬alert
      └──[M] $ref (74353:13)❌

Date: 07/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 0             | 0
components       | 7             | 7
❌  7 Breaking changes out of 7
INFO: Modifications: 5
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 5

ERROR: breaking changes discovered