[GitHubEnterprise-3.9] Update to 1.1.4-ac5f2a744766b192f47d36d4902a6550 from 1.1.4-b65de54831446d196d0701f96ddb91f6 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 4a50b0                                                                                 SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [61851:7]
├─┬Paths
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (14808:20)
│ ├─┬/user/following/{username}
│ │ └─┬PUT
│ │   └──[M] description (39287:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs
│ │ └─┬GET
│ │   └──[M] description (17963:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ └─┬PUT
│ │   └──[M] description (12742:20)
│ ├─┬/user/starred/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (41613:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └──[M] description (17736:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (14660:32)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ └─┬PUT
│ │   └──[M] description (23104:20)
│ ├─┬/users/{username}
│ │ └─┬GET
│ │   └──[M] description (41798:20)
│ ├─┬/users/{username}/site_admin
│ │ └─┬PUT
│ │   └──[M] description (42784:20)
│ ├─┬/users/{username}/suspended
│ │ └─┬PUT
│ │   └──[M] description (42971:20)
│ ├─┬/gists/{gist_id}/star
│ │ └─┬PUT
│ │   └──[M] description (6065:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └──[M] description (18993:20)
│ ├─┬/teams/{team_id}/members/{username}
│ │ └─┬PUT
│ │   └──[M] description (38224:20)
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (38542:32)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (38703:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/jobs
│ │ └─┬GET
│ │   └──[M] description (18082:20)
│ └─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│   └─┬PUT
│     └──[M] description (29142:20)
└─┬Components
  ├─┬code-scanning-alert-rule-summary
  │ └──[-] properties (63585:9)❌
  └─┬code-scanning-organization-alert-items
    └─┬rule
      └──[M] $ref (63557:13)❌

Date: 12/16/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 18            | 0
components       | 2             | 2

❌  2 Breaking changes out of 20
INFO: Modifications: 19
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered