[GitHubAE] Update to 1.1.4-9f4d4c650bdcedb87ba86bd4ef652f7e from 1.1.4-85b44e1fd5b2db48b1416de6372728c7 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 958aa5
                                                                                ├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           ├──[+] properties (20557:21)
│ │           └──[+] properties (20553:21)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬config
│             └──[M] $ref (20669:19)❌
└─┬Components
  └─┬hook
    └─┬config
      └──[M] $ref (59635:11)❌

                                                                                Date: 01/14/24 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
                                                                                Document Element | Total Changes | Breaking Changes
paths            | 3             | 1
components       | 1             | 1

                                                                                ❌  2 Breaking changes out of 4
                                                                                INFO: Modifications: 2
                                                                                INFO: Additions: 2
                                                                                INFO: Breaking Modifications: 2

                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

ERROR: breaking changes discovered