[GitHubEnterprise-3.13] Update to 1.1.4-b39b954044a7394ab4e5fe3ce2b56edc from 1.1.4-068189c2ddb887d39c830e1d08c2e36b Detected Schema changes:
```
└─┬Components
  └─┬repository-rule-pull-request
    └─┬parameters
      └──[➖] properties (75392:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 1             | 1                |

Date: 03/25/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _1_ out of _1_
- **Removals**: _1_
- **Breaking Removals**: _1_

ERROR: breaking changes discovered