[GitHub] Update to 1.1.4 (hash: 6823b660da89b3310f808a8c67057c2e) from 1.1.4 (hash: 8cc871b912e64c56497bb77d82de0f1f) Detected Schema changes:
├─┬Paths
│ ├──[-] path (30298:3)❌
│ ├──[+] path (29257:3)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └──[M] description (26254:20)
│ │ └─┬PATCH
│ │   └──[M] description (26285:20)
│ ├─┬/repos/{owner}/{repo}/contents/{path}
│ │ ├─┬PUT
│ │ │ └──[M] description (22938:20)
│ │ └─┬DELETE
│ │   └──[M] description (23072:20)
│ ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬actions
│ │           └──[M] description (19705:32)
│ ├─┬/orgs/{org}/outside_collaborators/{username}
│ │ └─┬DELETE
│ │   └─┬Responses
│ │     └─┬422
│ │       └─┬application/json
│ │         └─┬response-if-user-is-a-member-of-the-organization
│ │           └──[M] value (9035:21)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └──[M] description (26103:20)
│ │ └─┬PATCH
│ │   ├──[M] description (26134:20)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           └──[M] description (26157:32)
│ ├─┬/search/issues
│ │ └─┬GET
│ │   ├──[M] description (35938:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (35959:22)
│ │   └─┬Parameters
│ │     └──[M] description (35970:22)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └──[M] description (37728:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (37768:20)
│ │ └─┬DELETE
│ │   └──[M] description (37823:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ └─┬PUT
│ │   └──[M] description (24371:20)
│ ├─┬/user/codespaces/secrets/{secret_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬encrypted_value
│ │           └──[M] description (38498:32)
│ ├─┬/licenses
│ │ └─┬GET
│ │   └──[-] description (2510:20)
│ ├─┬/orgs/{org}/hooks
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           └──[M] description (7281:32)
│ ├─┬/search/labels
│ │ └─┬GET
│ │   ├──[M] description (36033:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (36057:22)
│ │   └─┬Parameters
│ │     └──[M] description (36065:22)
│ ├─┬/installation/token
│ │ └─┬DELETE
│ │   └──[M] description (2370:20)
│ ├─┬/repos/{owner}/{repo}/check-runs
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬actions
│ │           └──[M] description (19383:32)
│ ├─┬/search/topics
│ │ └─┬GET
│ │   ├──[M] description (36197:20)
│ │   └─┬Parameters
│ │     └──[M] description (36215:22)
│ ├─┬/licenses/{license}
│ │ └─┬GET
│ │   └──[-] description (2548:20)
│ ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/commits
│ │ └─┬GET
│ │   └──[M] description (31441:20)
│ ├─┬/advisories
│ │ └─┬GET
│ │   ├──[M] description (120:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (199:22)
│ │   └─┬Parameters
│ │     └──[M] description (184:22)
│ ├─┬/search/repositories
│ │ └─┬GET
│ │   ├──[M] description (36116:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (36134:22)
│ │   └─┬Parameters
│ │     └──[M] description (36145:22)
│ ├─┬/users/{username}
│ │ └─┬GET
│ │   └──[M] description (42364:20)
│ ├─┬/app/installations/{installation_id}
│ │ └─┬DELETE
│ │   └──[M] description (688:20)
│ ├─┬/search/users
│ │ └─┬GET
│ │   ├──[M] description (36258:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (36278:22)
│ │   └─┬Parameters
│ │     └──[M] description (36289:22)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           └──[M] description (7410:32)
│ ├─┬/search/code
│ │ └─┬GET
│ │   ├──[M] description (35761:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (35802:22)
│ │   └─┬Parameters
│ │     └──[M] description (35790:22)
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           └──[M] description (26029:32)
│ ├─┬/repos/{owner}/{repo}/check-suites
│ │ └─┬POST
│ │   └──[M] description (19887:20)
│ ├─┬/search/commits
│ │ └─┬GET
│ │   ├──[M] description (35865:20)
│ │   ├─┬Parameters
│ │   │ └──[M] description (35882:22)
│ │   └─┬Parameters
│ │     └──[M] description (35893:22)
│ └─┬/repos/{owner}/{repo}/pulls/{pull_number}/update-branch
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬expected_head_sha
│             └──[M] description (32265:32)
├─┬installation-unsuspend
│ └─┬POST
│   └──[M] summary (47821:16)
├─┬installation-new-permissions-accepted
│ └─┬POST
│   └──[M] summary (47506:16)
├─┬installation-repositories-removed
│ └─┬POST
│   └──[M] summary (47630:16)
├─┬push
│ └─┬POST
│   └──[M] summary (55360:16)
├─┬installation-suspend
│ └─┬POST
│   └──[M] summary (47693:16)
├─┬installation-repositories-added
│ └─┬POST
│   └──[M] summary (47568:16)
├─┬installation-target-renamed
│ └─┬POST
│   └──[M] summary (47756:16)
├─┬installation-deleted
│ └─┬POST
│   └──[M] summary (47443:16)
├─┬merge-queue-entry-created
│ └─┬POST
│   └──[-] tags (50137:9)
├─┬installation-created
│ └─┬POST
│   └──[M] summary (47381:16)
└─┬Components
  └─┬global-advisory
    └─┬nvd_published_at
      └──[M] description (59858:24)

Date: 08/17/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 1             | 0
paths            | 51            | 1
webhooks         | 10            | 0
❌  1 Breaking changes out of 62
INFO: Modifications: 57
INFO: Removals: 4
INFO: Additions: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered