[GitHubEnterprise-3.15] Update to 1.1.4-13765a979ded08b549109e71b65bcfcf from 1.1.4-6ea130cb5afd29dda26a543a1de89424 Detected Schema changes:
```
├─┬Paths
│ ├─┬/scim/v2/enterprises/{enterprise}/Users
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (41545:22)
│ └─┬/scim/v2/enterprises/{enterprise}/Groups
│   └─┬GET
│     └─┬Parameters
│       └──[🔀] description (41193:22)
└─┬Components
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └──[➖] properties (104030:13)❌
  ├─┬webhook-code-scanning-alert-created
  │ └─┬alert
  │   └──[➖] properties (104326:13)❌
  ├─┬code-scanning-alert-items
  │ └──[➖] properties (82181:9)❌
  ├─┬code-scanning-organization-alert-items
  │ └──[➖] properties (70771:9)❌
  └─┬code-scanning-alert
    └──[➖] properties (82290:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 2             | 0                |
| components       | 5             | 5                |

Date: 02/13/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _5_ out of _7_
- **Modifications**: _2_
- **Removals**: _5_
- **Breaking Removals**: _5_

ERROR: breaking changes discovered