[GitHub] Update to 1.1.4-ed43ce3c2a6bf973841dfa10ad4655d5 from 1.1.4-924650fabd10263aa71c7ec8a1f9544f Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 611b16
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └─┬POST
│ │   └──[🔀] description (22553:20)
│ └─┬/repos/{owner}/{repo}/pages
│   ├─┬GET
│   │ └─┬Responses
│   │   └─┬200
│   │     └─┬application/json
│   │       └─┬default
│   │         ├──[🔀] value (210438:9)
│   │         ├──[🔀] value (210438:9)
│   │         ├──[🔀] value (210438:9)
│   │         ├──[🔀] value (210438:9)
│   │         ├──[➖] value (210480:9)
│   │         └──[➖] value (210480:9)
│   └─┬POST
│     └─┬Responses
│       └─┬201
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (210438:9)
│             ├──[🔀] value (210438:9)
│             ├──[🔀] value (210438:9)
│             ├──[🔀] value (210438:9)
│             ├──[➖] value (210480:9)
│             └──[➖] value (210480:9)
└─┬Components
  ├──[➖] schemas (72192:7)❌
  ├─┬private-user
  │ └──[➖] properties (86909:9)❌
  ├─┬public-user
  │ └──[➖] properties (66867:9)❌
  ├─┬repository-rule
  │ ├──[➖] oneOf (72258:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71994:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71795:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71784:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (72129:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (72274:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71818:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71829:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71773:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71886:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (72250:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71915:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (72028:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71743:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71926:14)❌
  │ └─┬ONEOF
  │   └──[🔀] $ref (72227:9)❌
  └─┬repository-rule-detailed
    ├──[➖] oneOf (84842:9)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[🔀] $ref (84753:14)❌
    │ └─┬ALLOF
    │   └──[🔀] $ref (71773:14)❌
    ├─┬ONEOF
    │ └─┬ALLOF
    │   └──[🔀] $ref (71818:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[🔀] $ref (72062:14)❌
    │ └─┬ALLOF
    │   └──[🔀] $ref (84753:14)❌
    ├─┬ONEOF
    │ ├─┬ALLOF
    │ │ └──[🔀] $ref (84753:14)❌
    │ └─┬ALLOF
    │   └──[🔀] $ref (71743:14)❌
    └─┬ONEOF
      └─┬ALLOF
        └──[🔀] $ref (72028:14)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 13            | 0                |
| components       | 28            | 36               |

Date: 05/03/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _41_
- **Modifications**: _32_
- **Removals**: _9_
- **Breaking Removals**: _5_
- **Breaking Modifications**: _23_

ERROR: breaking changes discovered