[GitHubAE] Update to 1.1.4-dabccf38624f2b1c7063062e59b13705 from 1.1.4-b608479036d46de5aa2816f4316224a9 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (47560:14)❌
│ │         └─┬default
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[M] value (196898:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           └──[-] value (186036:9)
│ ├─┬/orgs/{org}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default-response
│ │ │         ├──[M] value (184564:9)
│ │ │         ├──[M] value (184564:9)
│ │ │         ├──[M] value (184564:9)
│ │ │         ├──[M] value (184564:9)
│ │ │         ├──[M] value (184564:9)
│ │ │         ├──[M] value (184564:9)
│ │ │         ├──[M] value (184564:9)
│ │ │         └──[-] value (184600:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[M] value (184564:9)
│ │   │       ├──[M] value (184564:9)
│ │   │       ├──[M] value (184564:9)
│ │   │       ├──[M] value (184564:9)
│ │   │       ├──[M] value (184564:9)
│ │   │       ├──[M] value (184564:9)
│ │   │       ├──[M] value (184564:9)
│ │   │       └──[-] value (184600:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[-] properties (5161:17)❌
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (9881:20)
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[M] value (1482:19)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (201087:20)
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (201087:20)
│ ├─┬/repos/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default-response
│ │ │         └──[M] value (186939:9)
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬security_and_analysis
│ │           └──[-] properties (11247:21)❌
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (201087:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (201087:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (201087:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (201087:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (201087:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (201087:20)
│ ├─┬/user/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (47560:14)❌
│ │         └─┬default
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           └──[-] value (186036:9)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬GET
│ │   └──[M] description (21732:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (47560:14)❌
│ │         └─┬default
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[M] value (185999:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           ├──[-] value (186036:9)
│ │           └──[-] value (186036:9)
│ └──/markdown/raw
└─┬Components
  ├──[+] examples (185998:7)
  ├──[+] examples (196897:7)
  ├─┬app-permissions
  │ └──[-] properties (46650:9)❌
  ├─┬organization-full
  │ └──[-] properties (51527:9)❌
  └─┬security-and-analysis
    └──[-] properties (50743:9)❌

Date: 11/29/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 303           | 5
components       | 5             | 3

❌  8 Breaking changes out of 308
INFO: Modifications: 279
INFO: Removals: 27
INFO: Additions: 2
INFO: Breaking Removals: 5
INFO: Breaking Modifications: 3

ERROR: breaking changes discovered