[GitHubEnterprise-3.7] Update to 1.1.4-8988d0a7b927e800801f548243c5f392 from 1.1.4-4e2a153d0943ec4d0ecafde3422b4940 Detected Schema changes:
└─┬Components
  └─┬webhook-issues-opened
    └─┬changes
      └─┬old_repository
        ├──[-] properties (105918:17)❌
        └──[-] properties (106190:17)❌

Date: 10/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌  2 Breaking changes out of 2
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered