[GitHubEnterprise-3.9] Update to 1.1.4-7e836cc43ddbdff23ebdfd412d0360e4 from 1.1.4-aebc75c87bb77e40af4a0ad253ea5784 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
│ │ └─┬POST
│ │   └──[M] description (17395:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (17310:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (17475:20)
│ │ └─┬DELETE
│ │   └──[M] description (17509:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels
│ │ ├─┬GET
│ │ │ └──[M] description (17537:20)
│ │ ├─┬PUT
│ │ │ └──[M] description (17619:20)
│ │ ├─┬POST
│ │ │ └──[M] description (17566:20)
│ │ └─┬DELETE
│ │   └──[M] description (17674:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/admin/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}/labels/{name}
│ │ └─┬DELETE
│ │   └──[M] description (17705:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └──[M] description (35339:20)
│ │ └─┬POST
│ │   └──[M] description (35387:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (18714:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (18793:20)
│ │ └─┬PATCH
│ │   └──[M] description (18748:20)
│ ├─┬/admin/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/actions/variables
│ │ ├─┬GET
│ │ │ └──[M] description (18612:20)
│ │ └─┬POST
│ │   └──[M] description (18659:20)
│ ├──/markdown/raw
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (212952:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (212952:9)
│ ├─┬/repos/{owner}/{repo}/actions/organization-variables
│ │ └─┬GET
│ │   └──[M] description (16977:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └──[M] description (35442:20)
│ │ ├─┬DELETE
│ │ │ └──[M] description (35521:20)
│ │ └─┬PATCH
│ │   └──[M] description (35476:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (17359:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (18053:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/actions/jobs/{job_id}/rerun
│ │ └─┬POST
│ │   └──[M] description (16777:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222152:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (222152:20)
│ └─┬/repos/{owner}/{repo}/actions/runners/remove-token
│   └─┬POST
│     └──[M] description (17433:20)
└─┬Components
  └─┬environment
    └─┬protection_rules
      └─┬Schema
        └─┬ANYOF
          └──[-] properties (75066:17)❌

Date: 09/26/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 49            | 0
components       | 1             | 1
❌  1 Breaking changes out of 50
INFO: Modifications: 49
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered