[GitHubAE] Update to 1.1.4-397de02fc724c7604f3b4c57f10fe5f6 from 1.1.4-4c4e1701d928399d4897fc32d297d17b Detected Schema changes:
├─┬check-run-completed
│ └──POST
└─┬Components
  └─┬webhook-issues-opened
    └─┬changes
      └─┬old_repository
        ├──[-] properties (94032:17)❌
        └──[-] properties (94304:17)❌

Date: 10/03/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
❌  2 Breaking changes out of 2
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered