[GitHub] Update to 1.1.4-7fb0426f383ed9712cce3fdba9572d5a from 1.1.4-b1df7aeeba72bb96f2ca61a7edd34136 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/dependabot/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (217903:7)
│ ├─┬/repos/{owner}/{repo}/dependabot/alerts/{alert_number}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (218084:9)
│ ├─┬/enterprises/{enterprise}/dependabot/alerts
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (204786:7)
│ ├─┬/orgs/{org}/settings/network-configurations/{network_configuration_id}
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[🔀] url (15667:14)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (15685:9)
│ │ ├─┬DELETE
│ │ │ ├─┬External Docs
│ │ │ │ └──[🔀] url (15763:14)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (15771:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[🔀] url (15700:14)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (15748:9)
│ ├─┬/orgs/{org}/settings/network-configurations
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[🔀] url (15557:14)
│ │ │ └─┬Extensions
│ │ │   └──[🔀] x-github (15586:9)
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[🔀] url (15601:14)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (15651:9)
│ ├─┬/orgs/{org}/settings/network-settings/{network_settings_id}
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[🔀] url (15787:14)
│ │   └─┬Extensions
│ │     └──[🔀] x-github (15805:9)
│ └─┬/orgs/{org}/dependabot/alerts
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (204786:7)
└─┬Components
  ├──[➖] schemas (67807:7)❌
  ├─┬dependabot-alert-security-advisory
  │ └──[➖] properties (71241:9)❌
  └─┬global-advisory
    └─┬epss
      └──[🔀] $ref (68117:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 16            | 0                |
| components       | 3             | 3                |

Date: 01/25/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _19_
- **Modifications**: _17_
- **Removals**: _2_
- **Breaking Removals**: _2_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered