[GitHubEnterprise-3.7] Update to 1.1.4-ffe2c50620e943ba34aa029e42846a6e from 1.1.4-7411d053a89a5c897c0b15d622338e4f Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (13230:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──Parameters
│ └─┬/repos/{owner}/{repo}/code-scanning/sarifs
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[-] additionalProperties (20897:37)❌
│           └─┬ref
│             └──[M] $ref (59483:13)❌
└─┬Components
  ├──[-] schemas (67792:7)❌
  └─┬code-scanning-ref
    └──[M] description (59484:20)

Date: 11/16/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 2
components       | 2             | 1

❌  3 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered