[GitHubEnterprise-3.13] Update to 1.1.4-09460ffde7c51e6470752d5d41c06e16 from 1.1.4-5c10b4ce18a4a421bdfbf1462d9c7578 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[➖] parameters (31512:15)❌
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (31660:17)❌
│ ├─┬/orgs/{org}/issues
│ │ └─┬GET
│ │   └──[➖] parameters (12675:15)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (32276:17)❌
│ └─┬/orgs/{org}/properties/schema
│   └─┬PATCH
│     └──[🔀] description (14512:20)
└─┬Components
  ├──[➖] schemas (70130:7)❌
  ├─┬webhook-issues-labeled
  │ └─┬issue
  │   └──[➖] properties (118916:13)❌
  ├─┬issue-search-result-item
  │ └──[➖] properties (87992:9)❌
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_issue
  │     └──[➖] properties (125193:17)❌
  ├─┬webhook-issue-comment-edited
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (113649:15)❌
  ├─┬webhook-issues-reopened
  │ └─┬issue
  │   └──[➖] properties (124333:13)❌
  ├─┬webhook-issues-unlocked
  │ └─┬issue
  │   └──[➖] properties (126723:13)❌
  ├─┬webhook-issues-demilestoned
  │ └─┬issue
  │   └──[➖] properties (116983:13)❌
  ├─┬webhooks_issue
  │ └──[➖] properties (92895:9)❌
  ├─┬webhook-issues-milestoned
  │ └─┬issue
  │   └──[➖] properties (120874:13)❌
  ├─┬webhook-issues-locked
  │ └─┬issue
  │   └──[➖] properties (119909:13)❌
  ├─┬webhook-issues-opened
  │ └─┬issue
  │   └──[➖] properties (123240:13)❌
  ├─┬webhook-issues-edited
  │ └─┬issue
  │   └──[➖] properties (117947:13)❌
  ├─┬issue
  │ └──[➖] properties (70430:9)❌
  ├─┬webhook-issues-deleted
  │ └─┬issue
  │   └──[➖] properties (115998:13)❌
  ├─┬webhooks_issue_2
  │ └──[➖] properties (93977:9)❌
  ├─┬webhook-issue-comment-deleted
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (112429:15)❌
  ├─┬webhook-issues-closed
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (114894:15)❌
  ├─┬app-permissions
  │ └─┬dependabot_secrets
  │   └──[🔀] description (65917:24)
  ├─┬custom-property-set-payload
  │ └──[➖] properties (74415:9)❌
  └─┬webhook-issue-comment-created
    └─┬issue
      └─┬ALLOF
        └──[➖] properties (111216:15)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 21            | 24               |

Date: 03/18/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _28_ out of _26_
- **Modifications**: _2_
- **Removals**: _24_
- **Breaking Removals**: _24_

ERROR: breaking changes discovered