[GitHubEnterprise-3.6] Update to 1.1.4-d29d4c055307506244ad6b0e78dbedd9 from 1.1.4-d96fe70af0fb11878cf98437786c3d00 Detected Schema changes:
└─┬Components
  └─┬user-role
    └─┬Schema
      └─┬value
        ├──[+] enum (57401:15)
        └──[-] enum (57401:15)❌

Date: 09/19/23 | Commit: New: etc/specs/GitHubEnterprise-3.6/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.6/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 1
❌  1 Breaking changes out of 2
INFO: Removals: 1
INFO: Additions: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered