[GitHubEnterprise-3.15] Update to 1.1.4-eebe824d504b8ef98e409bfc84091e66 from 1.1.4-35aa0c27af04ff30389730ec172a99ab Detected Schema changes:
```
├─┬personal-access-token-request-denied
│ └─┬POST
│   ├──[🔀] summary (57455:16)
│   └─┬Extensions
│     └──[🔀] x-github (57513:9)
├─┬personal-access-token-request-created
│ └─┬POST
│   ├──[🔀] summary (57390:16)
│   └─┬Extensions
│     └──[🔀] x-github (57448:9)
├─┬personal-access-token-request-approved
│ └─┬POST
│   ├──[🔀] summary (57259:16)
│   └─┬Extensions
│     └──[🔀] x-github (57317:9)
├─┬personal-access-token-request-cancelled
│ └─┬POST
│   ├──[🔀] summary (57324:16)
│   └─┬Extensions
│     └──[🔀] x-github (57383:9)
└─┬Components
  └─┬repository-rule-pull-request
    └─┬parameters
      └─┬allowed_merge_methods
        └─┬Schema
          ├──[➖] enum (77578:19)❌
          ├──[➖] enum (77579:19)❌
          └──[➖] enum (77580:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| webhooks         | 8             | 0                |
| components       | 3             | 3                |

Date: 03/20/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _11_
- **Modifications**: _8_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered