[GitHub] Update to 1.1.4-afc6e722cc5a6bed827aa47c96932184 from 1.1.4-71df6aeea9b73116fc9b87e18d680d1b Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 4865a8                                                                                 SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [62895:7]
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └─┬GET
│ │   └──[M] description (22224:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (21602:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──[M] description (21645:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (21725:20)
│ ├─┬/users/{username}/received_events
│ │ └─┬GET
│ │   └──[M] description (44754:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ └─┬GET
│ │   └──[M] description (21503:20)
│ └─┬/repos/{owner}/{repo}/code-scanning/default-setup
│   ├─┬GET
│   │ └──[M] description (22004:20)
│   └─┬PATCH
│     └──[M] description (22040:20)
├─┬project-column-deleted
│ └─┬POST
│   ├──[M] summary (53899:16)
│   └──[M] description (53905:20)
├─┬security-advisory-published
│ └─┬POST
│   └──[M] summary (59450:16)
├─┬project-column-created
│ └─┬POST
│   ├──[M] summary (53833:16)
│   └──[M] description (53839:20)
├─┬project-deleted
│ └─┬POST
│   ├──[M] summary (54163:16)
│   └──[M] description (54169:20)
├─┬project-card-converted
│ └─┬POST
│   ├──[M] summary (53436:16)
│   └──[M] description (53442:20)
├─┬security-advisory-updated
│ └─┬POST
│   ├──[M] summary (59512:16)
│   └──[M] description (59516:20)
├─┬project-edited
│ └─┬POST
│   ├──[M] summary (54229:16)
│   └──[M] description (54235:20)
├─┬dependabot-alert-auto-dismissed
│ └─┬POST
│   └──[M] description (46910:20)
├─┬security-advisory-withdrawn
│ └─┬POST
│   └──[M] summary (59575:16)
├─┬project-column-moved
│ └─┬POST
│   ├──[M] summary (54031:16)
│   └──[M] description (54037:20)
├─┬project-card-edited
│ └─┬POST
│   ├──[M] summary (53634:16)
│   └──[M] description (53640:20)
├─┬dependabot-alert-auto-reopened
│ └─┬POST
│   └──[M] description (46978:20)
├─┬project-reopened
│ └─┬POST
│   ├──[M] summary (54295:16)
│   └──[M] description (54301:20)
├─┬project-created
│ └─┬POST
│   ├──[M] summary (54097:16)
│   └──[M] description (54103:20)
├─┬project-card-moved
│ └─┬POST
│   ├──[M] summary (53700:16)
│   └──[M] description (53706:20)
├─┬project-closed
│ └─┬POST
│   ├──[M] summary (53767:16)
│   └──[M] description (53773:20)
├─┬project-card-deleted
│ └─┬POST
│   ├──[M] summary (53568:16)
│   └──[M] description (53574:20)
├─┬project-column-edited
│ └─┬POST
│   ├──[M] summary (53965:16)
│   └──[M] description (53971:20)
├─┬project-card-created
│ └─┬POST
│   ├──[M] summary (53502:16)
│   └──[M] description (53508:20)
└─┬Components
  ├─┬app-permissions
  │ ├──[-] properties (62418:9)❌
  │ ├──[-] properties (62432:9)❌
  │ ├──[-] properties (62685:9)❌
  │ ├──[-] properties (62692:9)❌
  │ ├──[-] properties (62699:9)❌
  │ ├──[-] properties (62706:9)❌
  │ ├──[-] properties (62713:9)❌
  │ ├──[-] properties (62608:9)❌
  │ ├──[-] properties (62720:9)❌
  │ └──[-] properties (62726:9)❌
  ├─┬org-ruleset-conditions
  │ └──[M] description (70713:20)
  ├─┬merge-group
  │ └──[M] description (88103:20)
  ├─┬actions-workflow-access-to-repository
  │ └─┬access_level
  │   └──[M] description (73628:24)
  └─┬code-scanning-ref-full
    ├──[M] pattern (76343:16)❌
    └──[M] description (76340:20)

Date: 12/08/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 8             | 0
webhooks         | 34            | 0
components       | 15            | 11

❌  11 Breaking changes out of 57
INFO: Modifications: 47
INFO: Removals: 10
INFO: Breaking Removals: 10
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered