[GitHub] Update to 1.1.4-2d60f44f2f6c4f1e645de34b84c95208 from 1.1.4-31d970a125b23e50df0d710a170852d6 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 383734
```
                                                                                ├─┬Paths
│ ├──[➖] path (1432:3)❌
│ ├──[➖] path (7052:3)❌
│ ├──[➖] path (12497:3)❌
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └──[🔀] description (7947:20)
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └─┬POST
│ │   └──[🔀] description (710:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └──[🔀] description (7984:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └──[🔀] description (7811:20)
│ │ └─┬PATCH
│ │   └──[🔀] description (7844:20)
│ ├─┬/orgs/{org}/hooks
│ │ ├─┬GET
│ │ │ └──[🔀] description (7530:20)
│ │ └─┬POST
│ │   └──[🔀] description (7568:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └──[🔀] description (8014:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └──[🔀] description (7901:20)
│ └─┬/orgs/{org}/hooks/{hook_id}
│   ├─┬GET
│   │ └──[🔀] description (7668:20)
│   ├─┬DELETE
│   │ └──[🔀] description (7785:20)
│   └─┬PATCH
│     └──[🔀] description (7702:20)
└─┬Components
  ├──[➖] examples (209997:7)❌
  ├──[➖] examples (213201:7)❌
  └──[➖] schemas (65207:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 15            | 3                |
| components       | 3             | 3                |

Date: 04/23/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _18_
- **Modifications**: _12_
- **Removals**: _6_
- **Breaking Removals**: _6_

                                                                                SPEC: extracted 2 commits from history
ERROR: breaking changes discovered