[GitHubEnterprise-3.9] Update to 1.1.4-68793563f5b3058c4114e4ca81510b06 from 1.1.4-01ecc0a12416efba06c34a65af99a699 Detected Schema changes:
├─┬Paths
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/public-key
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/variables/{name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬GET
│ │   └──[M] description (28377:20)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (61750:14)❌
│ │         └─┬default
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[M] value (217605:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           └──[-] value (206007:9)
│ ├─┬/app/installations/{installation_id}/access_tokens
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[M] value (1976:19)
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment-branch-policies/{branch_policy_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ ├─┬PUT
│ │ │ └─┬Parameters
│ │ │   └──[M] description (222982:20)
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (222982:20)
│ ├─┬/user/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (61750:14)❌
│ │         └─┬default
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           └──[-] value (206007:9)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         ├─┬Schema
│ │         │ └──[M] $ref (61750:14)❌
│ │         └─┬default
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[M] value (206000:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           ├──[-] value (206007:9)
│ │           └──[-] value (206007:9)
│ └─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│   └─┬GET
│     └──[M] description (14763:20)
└─┬Components
  ├──[+] examples (217604:7)
  ├──[+] examples (205999:7)
  └─┬app-permissions
    ├──[-] properties (60818:9)❌
    └─┬organization_custom_roles
      └──[M] description (60812:24)

Date: 11/29/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 294           | 3
components       | 4             | 1

❌  4 Breaking changes out of 298
INFO: Modifications: 275
INFO: Removals: 21
INFO: Additions: 2
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 3

ERROR: breaking changes discovered