[GitHub] Update to 1.1.4-b5681abce03354e41943d59e8d8bc4a6 from 1.1.4-258d33610c11c1d10d29617d894e1ce8 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (1677:3)❌
│ ├─┬/orgs/{org}/copilot/usage
│ │ └─┬GET
│ │   └──[🔀] description (7887:20)
│ ├─┬/repos/{owner}/{repo}/rulesets/{ruleset_id}
│ │ └─┬GET
│ │   └──[🔀] description (37168:20)
│ ├─┬/meta
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           ├──[🔀] value (200342:9)
│ │           └──[➖] value (200378:9)
│ ├─┬/user/repos
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├─┬squash_merge_commit_title
│ │         │ └──[🔀] description (45072:32)
│ │         └─┬merge_commit_title
│ │           └──[🔀] description (45094:32)
│ ├─┬/enterprises/{enterprise}/copilot/usage
│ │ └─┬GET
│ │   └──[🔀] description (1496:20)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (201468:7)
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           ├──[🔀] value (201567:9)
│ │           └──[➖] value (201609:9)
│ ├─┬/orgs/{org}/code-security/configurations/defaults
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (201526:7)
│ ├─┬/orgs/{org}/rulesets/{ruleset_id}
│ │ └─┬GET
│ │   └──[🔀] description (12615:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├─┬squash_merge_commit_title
│ │         │ └──[🔀] description (12324:32)
│ │         └─┬merge_commit_title
│ │           └──[🔀] description (12346:32)
│ └─┬/repos/{owner}/{repo}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├─┬merge_commit_title
│           │ └──[🔀] description (16102:32)
│           └─┬squash_merge_commit_title
│             └──[🔀] description (16080:32)
└─┬Components
  ├──[➕] schemas (66738:7)
  ├─┬api-overview
  │ └──[➖] properties (69458:9)❌
  └─┬copilot-seat-details
    └─┬assignee
      ├──[➕] oneOf (63846:7)
      ├──[➕] oneOf (66666:7)
      └─┬ONEOF
        └──[🔀] $ref (66738:14)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 37            | 1                |
| components       | 5             | 2                |

Date: 08/08/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _42_
- **Modifications**: _35_
- **Removals**: _4_
- **Additions**: _3_
- **Breaking Removals**: _2_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered