[GitHub] Update to 1.1.4-7b81f53085c7eb703517cc9edd6bed5e from 1.1.4-eb75ba12b8f78ce6cf7e307635ad5f13 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 959653
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ └─┬/orgs/{org}/invitations
│   └─┬GET
│     └──[🔀] description (8366:20)
└─┬Components
  ├─┬webhook-personal-access-token-request-created
  │ ├──[➕] required (127863:9)❌
  │ └──[➖] properties (127857:9)❌
  ├─┬webhook-personal-access-token-request-denied
  │ └──[➖] properties (127882:9)❌
  ├─┬webhook-personal-access-token-request-approved
  │ └──[➖] properties (127809:9)❌
  └─┬webhook-personal-access-token-request-cancelled
    └──[➖] properties (127833:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 5             | 5                |

Date: 05/29/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _5_ out of _6_
- **Modifications**: _1_
- **Removals**: _4_
- **Additions**: _1_
- **Breaking Removals**: _4_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered