[GitHubAE] Update to 1.1.4-a8cad12970f1ee84856b800561c6d2f3 from 1.1.4-a4b4de44e0d05ceb3ff58b2a46d305a4 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 11a31e
                                                                                └─┬Paths
  └─┬/repos/{owner}/{repo}/autolinks
    └─┬GET
      ├──[+] parameters (200803:13)❌
      ├──[M] summary (13235:16)
      ├──[M] description (13236:20)
      └─┬External Docs
        └──[M] url (13245:14)

                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

Date: 02/02/24 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 4             | 1

❌  1 Breaking changes out of 4
INFO: Modifications: 3
INFO: Additions: 1
INFO: Breaking Additions: 1

ERROR: breaking changes discovered