[GitHubEnterprise-3.15] Update to 1.1.4-83e5b632882630eb5ec8d27318fd0346 from 1.1.4-2766a6279db0f2ed943b5c4abdd093c7 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] required (10451:17)❌
│ │         └──[➖] required (10452:17)❌
│ ├─┬/repos/{owner}/{repo}/vulnerability-alerts
│ │ └─┬GET
│ │   └─┬Extensions
│ │     └──[🔀] x-github (40925:9)
│ └─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[➖] required (22795:17)❌
│           └──[➖] required (22796:17)❌
└─┬Components
  └─┬ghes-license-info
    └─┬croquetSupport
      └──[🔀] description (72835:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 1             | 0                |

Date: 01/31/25 | Commit: New: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _6_
- **Modifications**: _2_
- **Removals**: _4_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered