[GitHub] Update to 1.1.4-5bd2a30080267627618f4b33aa9b7f31 from 1.1.4-2d60f44f2f6c4f1e645de34b84c95208 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 5b9ea7
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/rulesets/{ruleset_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           ├──[➖] enum (36279:21)❌
│ │           └──[🔀] description (36260:32)
│ ├─┬/orgs/{org}/rulesets
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           ├──[➖] enum (11893:21)❌
│ │           └──[🔀] description (11886:32)
│ ├─┬/repos/{owner}/{repo}/rulesets
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           ├──[➖] enum (36061:21)❌
│ │           └──[🔀] description (36046:32)
│ └─┬/orgs/{org}/rulesets/{ruleset_id}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬target
│             ├──[➖] enum (12106:21)❌
│             └──[🔀] description (12095:32)
└─┬Components
  ├──[➖] schemas (89305:7)❌
  ├──[➖] schemas (92585:7)❌
  ├──[➖] schemas (97246:7)❌
  ├──[➖] schemas (91291:7)❌
  ├──[➖] schemas (93580:7)❌
  ├──[➖] schemas (93515:7)❌
  ├──[➖] schemas (90139:7)❌
  ├──[➖] schemas (90361:7)❌
  ├──[➖] schemas (96618:7)❌
  ├──[➖] schemas (89170:7)❌
  ├──[➖] schemas (90196:7)❌
  ├──[➖] schemas (92501:7)❌
  ├──[➖] schemas (96300:7)❌
  ├──[➖] schemas (93450:7)❌
  ├──[➖] schemas (93094:7)❌
  ├──[➖] schemas (93340:7)❌
  ├──[➖] schemas (89175:7)❌
  ├──[➖] schemas (89224:7)❌
  ├──[➖] schemas (90106:7)❌
  ├──[➖] schemas (89180:7)❌
  ├──[➖] schemas (97476:7)❌
  ├──[➖] schemas (90373:7)❌
  ├──[➖] schemas (95869:7)❌
  ├──[➖] schemas (91432:7)❌
  ├──[➖] schemas (96152:7)❌
  ├──[➖] schemas (96304:7)❌
  ├──[➖] schemas (96934:7)❌
  ├──[➖] schemas (92343:7)❌
  ├──[➖] schemas (89949:7)❌
  ├──[➖] schemas (93215:7)❌
  ├──[➖] schemas (90189:7)❌
  ├──[➖] schemas (92868:7)❌
  ├──[➖] schemas (89184:7)❌
  ├──[➖] schemas (90164:7)❌
  ├──[➖] schemas (89482:7)❌
  ├──[➖] schemas (89188:7)❌
  ├──[➖] schemas (97133:7)❌
  ├──[➖] schemas (89383:7)❌
  ├──[➖] schemas (97519:7)❌
  ├──[➖] schemas (92413:7)❌
  ├──[➖] schemas (89266:7)❌
  ├──[➖] schemas (97472:7)❌
  ├──[➖] schemas (89413:7)❌
  ├──[➖] schemas (92728:7)❌
  ├─┬repository-rule
  │ ├──[➖] oneOf (72024:7)❌
  │ ├──[➖] oneOf (71739:7)❌
  │ ├──[➖] oneOf (71922:7)❌
  │ ├──[➖] oneOf (72223:9)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71937:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71971:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71772:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71761:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (72106:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71795:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71806:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71750:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71863:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71892:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (72005:14)❌
  │ ├─┬ONEOF
  │ │ └──[🔀] $ref (71720:14)❌
  │ └─┬ONEOF
  │   └──[🔀] $ref (71903:14)❌
  ├─┬webhook-issue-comment-edited
  │ ├──changes
  │ └─┬comment
  │   └──[🔀] $ref (105024:11)❌
  ├─┬integration
  │ └──[🔀] type (62866:13)❌
  ├─┬repository-ruleset
  │ └─┬target
  │   ├──[➖] enum (72320:13)❌
  │   └──[🔀] description (72199:24)
  ├─┬webhook-issue-comment-deleted
  │ └─┬comment
  │   └──[🔀] $ref (103664:11)❌
  └─┬repository-ruleset-bypass-actor
    ├──[➕] required (71568:9)❌
    └─┬actor_id
      └──[🔀] type (71573:17)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 4                |
| components       | 68            | 67               |

Date: 04/27/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _76_
- **Modifications**: _22_
- **Removals**: _53_
- **Additions**: _1_
- **Breaking Removals**: _53_
- **Breaking Modifications**: _17_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered