[GitHub] Update to 1.1.4-9c8289fb32417a7c2d7cf660ecfee1f2 from 1.1.4-b29f0a104a78b31f92c3c5617714fccf Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit ea4af9
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/{protection_rule_id}
│ │ └─┬GET
│ │   └──[M] description (26385:20)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules/apps
│ │ └─┬GET
│ │   └──[M] description (26337:20)
│ ├─┬/repos/{owner}/{repo}/pages/deployments
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[M] value (227790:9)
│ │           ├──[M] value (227790:9)
│ │           └──[-] value (227801:9)
│ ├─┬/repos/{owner}/{repo}/codespaces/secrets/{secret_name}
│ │ ├─┬PUT
│ │ │ └──[M] description (23002:20)
│ │ └─┬DELETE
│ │   └──[M] description (23060:20)
│ └─┬/repos/{owner}/{repo}/environments/{environment_name}/deployment_protection_rules
│   └─┬GET
│     └──[M] description (26226:20)
└─┬Components
  ├─┬page-deployment
  │ ├──[-] required (82463:9)❌
  │ └──[-] properties (82438:9)❌
  └─┬webhook-push
    └─┬commits
      └─┬Schema
        ├─┬removed
        │ └──[M] description (194083:30)
        ├─┬modified
        │ └──[M] description (194078:30)
        └─┬added
          └──[M] description (194022:30)

Date: 02/08/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 8             | 0
components       | 5             | 2

❌  2 Breaking changes out of 13
INFO: Modifications: 10
INFO: Removals: 3
INFO: Breaking Removals: 2

ERROR: breaking changes discovered