[GitHub] Update to 1.1.4-a9f9373b436a715e38764f5f7b04e767 from 1.1.4-2613abe9bea3162d3f87cc73a6dfdeed Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/copilot/billing
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (203034:9)
│ │           ├──[🔀] value (203034:9)
│ │           ├──[🔀] value (203034:9)
│ │           ├──[➖] value (203030:9)
│ │           ├──[➖] value (203030:9)
│ │           └──[➖] value (203030:9)
│ └─┬/repos/{owner}/{repo}/codespaces/secrets/public-key
│   └─┬GET
│     └──[🔀] description (24448:20)
└─┬Components
  ├─┬copilot-organization-details
  │ ├──[🔀] title (72183:14)
  │ └──[🔀] description (72184:20)
  └─┬content-tree
    ├──[➕] required (81496:9)❌
    ├──[➕] required (81497:9)❌
    ├──[➖] properties (81379:9)❌
    └─┬entries
      └─┬Schema
        └──[➕] properties (81412:15)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 6             | 3                |
| paths            | 7             | 0                |

Date: 09/23/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _13_
- **Modifications**: _6_
- **Removals**: _4_
- **Additions**: _3_
- **Breaking Removals**: _1_
- **Breaking Additions**: _2_

ERROR: breaking changes discovered