[GitHub] Update to 1.1.4-045e5b013b51c6a9b4cceeceae74dd4d from 1.1.4-79bfc552fc9431ae453024109bc3424d Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/installation
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           └──[➖] value (202678:9)
│ ├─┬/apps/{app_slug}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           └──[➖] value (196269:9)
│ ├─┬/app
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           ├──[🔀] value (196249:9)
│ │           └──[➖] value (196269:9)
│ ├─┬/orgs/{org}/installation
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           └──[➖] value (202678:9)
│ ├─┬/orgs/{org}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (222822:20)
│ ├─┬/users/{username}/installation
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           ├──[🔀] value (202657:9)
│ │           └──[➖] value (202678:9)
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (222822:20)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[🔀] description (222822:20)
│ └─┬/repos/{owner}/{repo}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬security_and_analysis
│             └─┬secret_scanning_non_provider_patterns
│               └──[🔀] description (16201:36)
├─┬deployment-status-created
│ └─┬POST
│   └──[🔀] summary (50258:16)
└─┬Components
  ├─┬secret-scanning-alert
  │ └─┬secret_type_display_name
  │   └──[🔀] description (87263:24)
  ├─┬secret-scanning-alert-webhook
  │ └─┬secret_type_display_name
  │   └──[🔀] description (99757:24)
  ├─┬branch-restriction-policy
  │ └─┬apps
  │   └─┬Schema
  │     └──[➖] properties (78156:15)❌
  ├─┬webhook-check-suite-requested
  │ └─┬check_suite
  │   └─┬app
  │     └──[➖] properties (101384:17)❌
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬app
  │     └──[➖] properties (100766:17)❌
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬app
  │     └──[➖] properties (101995:17)❌
  └─┬organization-secret-scanning-alert
    └─┬secret_type_display_name
      └──[🔀] description (68054:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 78            | 0                |
| webhooks         | 1             | 0                |
| components       | 7             | 4                |

Date: 08/20/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _86_
- **Modifications**: _77_
- **Removals**: _9_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered