[GitHubEnterprise-3.13] Update to 1.1.4-1e4171c4fa0a2799e195f6bc1881cf84 from 1.1.4-71747b16e45e0f2a54b8e1ca561b75d5 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] required (10402:17)❌
│ │         └──[➖] required (10403:17)❌
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] required (21353:17)❌
│ │         └──[➖] required (21352:17)❌
│ └─┬/repos/{owner}/{repo}/vulnerability-alerts
│   └─┬GET
│     └─┬Extensions
│       └──[🔀] x-github (39380:9)
└─┬Components
  └─┬ghes-license-info
    └─┬croquetSupport
      └──[🔀] description (71460:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 1             | 0                |

Date: 01/31/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _6_
- **Modifications**: _2_
- **Removals**: _4_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered