[GitHubEnterprise-3.7] Update to 1.1.4 (hash: 5d20cfa6c374c389646c8e65f150b0ae) from 1.1.4 (hash: 926bc8c894789d2daf95af5a78427ce1) Detected Schema changes:
└─┬Paths
  ├─┬/repos/{owner}/{repo}/issues/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26314:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (20454:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (27386:14)
  ├─┬/repos/{owner}/{repo}/labels/{name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27683:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (27777:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (27717:14)
  ├─┬/repos/{owner}/{repo}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (27578:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (27616:14)
  ├─┬/repos/{owner}/{repo}/assignees
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (17323:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26717:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (26765:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (20153:14)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26067:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (26145:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (26098:14)
  ├─┬/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (6154:14)
  ├─┬/repos/{owner}/{repo}/milestones
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (28029:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (28096:14)
  ├─┬/orgs/{org}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (8311:20)
  ├─┬/repos/{owner}/{repo}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (17365:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (31939:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees
  │ ├─┬POST
  │ │ └─┬External Docs
  │ │   └──[M] url (26580:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (26628:14)
  ├─┬/repos/{owner}/{repo}/deployments
  │ └─┬POST
  │   └──[M] description (23181:20)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22075:14)
  ├─┬/user/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (37417:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (27113:14)
  ├─┬/enterprises/{enterprise}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (4622:20)
  ├─┬/enterprises/{enterprise}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (5013:14)
  ├─┬/repos/{owner}/{repo}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (15833:20)
  ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
  │ └─┬POST
  │   └──[M] description (15866:20)
  ├─┬/repos/{owner}/{repo}/contents/{path}
  │ └─┬GET
  │   └──[M] description (22359:20)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (20362:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26824:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (28281:14)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
  │ └─┬POST
  │   └──[M] description (29799:20)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (28167:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (28257:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (28197:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (31791:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26681:14)
  ├─┬/repos/{owner}/{repo}/check-suites/preferences
  │ └─┬PATCH
  │   ├──[M] description (20288:20)
  │   └─┬External Docs
  │     └──[M] url (20299:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (31840:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (31880:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26862:14)
  │ ├─┬PUT
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (26993:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ └─┬labels
  │ │       │   ├──[+] description (27009:34)
  │ │       │   └─┬Schema
  │ │       │     ├──[-] required (27030:25)❌
  │ │       │     ├──[M] type (27017:29)❌
  │ │       │     └──[-] properties (27027:25)❌
  │ │       ├─┬ONEOF
  │ │       │ ├──[-] items (27034:19)❌
  │ │       │ ├──[M] type (27022:23)❌
  │ │       │ ├──[-] minItems (27032:27)❌
  │ │       │ └──[+] properties (27024:19)
  │ │       └─┬ONEOF
  │ │         ├──[+] items (27037:19)❌
  │ │         ├──[M] type (27034:23)❌
  │ │         ├──[+] minItems (27035:27)❌
  │ │         └──[-] properties (27003:19)❌
  │ ├─┬POST
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (26904:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ └─┬labels
  │ │       │   ├──[-] description (26917:34)
  │ │       │   └─┬Schema
  │ │       │     ├──[+] required (26943:25)❌
  │ │       │     ├──[M] type (26938:29)❌
  │ │       │     └──[+] properties (26940:25)
  │ │       ├─┬ONEOF
  │ │       │ ├──[+] items (26947:19)❌
  │ │       │ ├──[M] type (26944:23)❌
  │ │       │ ├──[+] minItems (26945:27)❌
  │ │       │ └──[-] properties (26931:19)❌
  │ │       └─┬ONEOF
  │ │         ├──[-] items (26944:19)❌
  │ │         ├──[M] type (26915:23)❌
  │ │         ├──[-] minItems (26942:27)❌
  │ │         └──[+] properties (26917:19)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (27083:14)
  ├─┬/orgs/{org}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (11695:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (20394:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (19858:14)
  │ └─┬PATCH
  │   ├─┬External Docs
  │   │ └──[M] url (19889:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (19964:36)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26401:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (26437:14)
  ├─┬/orgs/{org}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (8273:20)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22140:14)
  ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26351:14)
  ├─┬/repos/{owner}/{repo}/issues
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (25796:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (25892:14)
  ├─┬/repos/{owner}/{repo}/check-runs
  │ └─┬POST
  │   ├─┬External Docs
  │   │ └──[M] url (19558:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (19640:36)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (20194:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
  │ ├─┬PUT
  │ │ └─┬External Docs
  │ │   └──[M] url (27158:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (27211:14)
  ├─┬/search/code
  │ └─┬GET
  │   └──[M] description (33963:20)
  ├─┬/repos/{owner}/{repo}/check-suites
  │ └─┬POST
  │   ├──[M] description (20232:20)
  │   └─┬External Docs
  │     └──[M] url (20241:14)
  ├─┬/orgs/{org}/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (10253:14)
  ├─┬/enterprises/{enterprise}/actions/runners/registration-token
  │ └─┬POST
  │   └──[M] description (4584:20)
  └─┬/repos/{owner}/{repo}/issues/comments
    └─┬GET
      └─┬External Docs
        └──[M] url (26016:14)

Date: 07/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.7/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.7/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 96            | 19
❌ 19 Breaking changes out of 96

ERROR: breaking changes discovered