[GitHub] Update to 1.1.4-be512ecb1c6b444be7d7f1c231d0a921 from 1.1.4-8ce8ea6ebca9a21ed76d7617756ee9f1 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/code-security/configurations
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[🔀] value (204216:7)
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (204264:9)
│ │   │       ├──[🔀] value (204264:9)
│ │   │       ├──[🔀] value (204264:9)
│ │   │       ├──[🔀] value (204264:9)
│ │   │       ├──[🔀] value (204264:9)
│ │   │       ├──[🔀] value (204264:9)
│ │   │       └──[➖] value (204366:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] properties (6924:17)❌
│ │         └──[➖] properties (6933:17)❌
│ ├─┬/repos/{owner}/{repo}/code-security-configuration
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (211800:9)
│ ├─┬/repos/{owner}/{repo}/dispatches
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬client_payload
│ │           └──[🔀] description (27891:32)
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (204264:9)
│ │ │         ├──[🔀] value (204264:9)
│ │ │         ├──[🔀] value (204264:9)
│ │ │         ├──[🔀] value (204264:9)
│ │ │         ├──[🔀] value (204264:9)
│ │ │         ├──[🔀] value (204264:9)
│ │ │         └──[➖] value (204366:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (204338:9)
│ │   │       ├──[🔀] value (204338:9)
│ │   │       ├──[🔀] value (204338:9)
│ │   │       ├──[🔀] value (204338:9)
│ │   │       ├──[🔀] value (204338:9)
│ │   │       ├──[🔀] value (204338:9)
│ │   │       └──[➖] value (204448:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] properties (7245:17)❌
│ │         └──[➖] properties (7253:17)❌
│ ├─┬/orgs/{org}/code-security/configurations/defaults
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (204288:7)
│ └─┬/users/{username}/events
│   └─┬GET
│     └──[🔀] description (46971:20)
└─┬Components
  └─┬code-security-configuration
    ├──[➖] properties (72472:9)❌
    └──[➖] properties (72479:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 30            | 4                |
| components       | 2             | 2                |

Date: 10/23/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _32_
- **Modifications**: _23_
- **Removals**: _9_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered