[GitHub] Update to 1.1.4-f7468d269476e7c0c11c8b67322a69a1 from 1.1.4-5111760c5ff914fc4c83cde28d085440 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (207497:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (230670:7)❌
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           └──[➖] value (207593:9)
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (207497:9)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           ├──[🔀] value (207586:9)
│ │           └──[➖] value (207593:9)
│ ├─┬/orgs/{org}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (230670:7)❌
│ ├─┬/repos/{owner}/{repo}/pages/deployments
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[➕] value (37059:19)
│ └─┬/repos/{owner}/{repo}/actions/runners
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[🔀] value (207497:9)
└─┬Components
  └─┬runner
    └──[➖] properties (74923:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 18            | 2                |
| components       | 1             | 1                |

Date: 02/05/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _19_
- **Modifications**: _13_
- **Removals**: _5_
- **Additions**: _1_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered