[GitHub] Update to 1.1.4-d2d01395df29a6b406754b59eca9b64e from 1.1.4-49e6f9eda2f9b53adb152deaeefd9f73 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 17ab18
                                                                                SPEC: extracted 2 commits from history

```
├─┬Paths
│ ├─┬/orgs/{org}/members/{username}/copilot
│ │ └─┬GET
│ │   └──[🔀] description (8908:20)
│ ├─┬/orgs/{org}/copilot/billing/selected_teams
│ │ ├─┬POST
│ │ │ └──[🔀] description (6720:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (6801:20)
│ ├─┬/repos/{owner}/{repo}/commits
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (219705:20)
│ │   └─┬Parameters
│ │     └──[🔀] description (24170:22)
│ ├─┬/orgs/{org}/copilot/billing/selected_users
│ │ ├─┬POST
│ │ │ └──[🔀] description (6883:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (6964:20)
│ ├─┬/orgs/{org}/properties/schema/{custom_property_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬value_type
│ │           ├──[➖] enum (11218:21)❌
│ │           └──[➖] enum (11219:21)❌
│ ├─┬/orgs/{org}/memberships/{username}
│ │ └─┬PUT
│ │   └──[🔀] description (8987:20)
│ ├─┬/orgs/{org}/copilot/billing
│ │ └─┬GET
│ │   └──[🔀] description (6612:20)
│ └─┬/orgs/{org}/copilot/billing/seats
│   └─┬GET
│     └──[🔀] description (6658:20)
└─┬Components
  ├──[➖] schemas (70126:7)❌
  ├─┬copilot-seat-details
  │ ├──[➖] properties (70186:9)❌
  │ └─┬assigning_team
  │   ├──[🔀] description (70127:24)
  │   ├──[➖] oneOf (69923:7)❌
  │   └─┬ONEOF
  │     └──[🔀] $ref (69910:14)❌
  └─┬org-custom-property
    └─┬value_type
      ├──[➖] enum (71085:13)❌
      └──[➖] enum (71086:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 2                |
| components       | 7             | 6                |

Date: 06/13/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _8_ out of _19_
- **Modifications**: _12_
- **Removals**: _7_
- **Breaking Removals**: _7_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered