[GitHubEnterprise-3.14] Update to 1.1.4-e6b97d7e63c1ce77438434e9c1074e81 from 1.1.4-4d3a9ded7363917824fb2d5fa79ad2ce Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[➖] required (21971:17)❌
│ │         └──[➖] required (21972:17)❌
│ ├─┬/repos/{owner}/{repo}/vulnerability-alerts
│ │ └─┬GET
│ │   └─┬Extensions
│ │     └──[🔀] x-github (39999:9)
│ └─┬/orgs/{org}/actions/secrets/{secret_name}
│   └─┬PUT
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[➖] required (10442:17)❌
│           └──[➖] required (10443:17)❌
└─┬Components
  └─┬ghes-license-info
    └─┬croquetSupport
      └──[🔀] description (72420:24)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 1             | 0                |

Date: 01/31/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _6_
- **Modifications**: _2_
- **Removals**: _4_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered