[GitHub] Update to 1.1.4-893e2fb0b8fad9258f8b3396ebcda9b9 from 1.1.4-c22e4288a9c6ed5c4a6a2c04770f2d22 Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/insights/api/subject-stats
│ │ └─┬GET
│ │   └──[➖] parameters (227040:13)❌
│ ├─┬/orgs/{org}/copilot/billing/selected_teams
│ │ ├─┬POST
│ │ │ └──[🔀] description (8492:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (8577:20)
│ ├─┬/orgs/{org}/code-security/configurations
│ │ └─┬POST
│ │   ├─┬Responses
│ │   │ └─┬201
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       ├──[🔀] value (205585:9)
│ │   │       └──[➖] value (205641:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (7094:17)❌
│ ├─┬/enterprises/{enterprise}/team/{team_slug}/copilot/metrics
│ │ └─┬GET
│ │   └──[🔀] description (1769:20)
│ ├─┬/orgs/{org}/code-security/configurations/defaults
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (205610:7)
│ ├─┬/orgs/{org}/insights/api/route-stats/{actor_type}/{actor_id}
│ │ └─┬GET
│ │   └──[➖] parameters (227016:13)❌
│ ├─┬/orgs/{org}/copilot/billing/selected_users
│ │ ├─┬POST
│ │ │ └──[🔀] description (8663:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (8747:20)
│ ├─┬/orgs/{org}/code-security/configurations/{configuration_id}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         ├──[🔀] value (205585:9)
│ │ │         └──[➖] value (205641:9)
│ │ └─┬PATCH
│ │   ├─┬Responses
│ │   │ └─┬200
│ │   │   └─┬application/json
│ │   │     └─┬default
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       ├──[🔀] value (205667:9)
│ │   │       └──[➖] value (205732:9)
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (7419:17)❌
│ ├─┬/enterprises/{enterprise}/team/{team_slug}/copilot/usage
│ │ └─┬GET
│ │   └──[🔀] description (1844:20)
│ └─┬/orgs/{org}/insights/api/user-stats/{user_id}
│   └─┬GET
│     └──[➖] parameters (227063:13)❌
└─┬Components
  ├──[➖] parameters (227063:7)❌
  ├──[➖] parameters (227040:7)❌
  ├──[➖] parameters (227016:7)❌
  ├──[➖] schemas (73925:7)❌
  ├─┬code-security-configuration
  │ └──[➖] properties (73818:9)❌
  ├─┬secret-scanning-scan
  │ ├─┬completed_at
  │ │ └──[🔀] description (89643:24)
  │ ├─┬status
  │ │ └──[🔀] description (89637:24)
  │ └─┬started_at
  │   ├──[🔀] type (89646:17)❌
  │   └──[🔀] description (89648:24)
  └─┬code-scanning-default-setup-update
    ├──[➖] properties (82711:9)❌
    └──[➖] properties (82705:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 75            | 5                |
| components       | 11            | 8                |

Date: 12/05/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _13_ out of _86_
- **Modifications**: _71_
- **Removals**: _15_
- **Breaking Removals**: _12_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered