[GitHub] Update to 1.1.4-7175787c7e49e097149d5858b6551438 from 1.1.4-fab1ddd37553337c5ed4418939293ccb Detected Schema changes:
```
└─┬Paths
  ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions
  │ ├─┬GET
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ └─┬POST
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ ├─┬DELETE
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ └─┬PATCH
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/gists/{gist_id}/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ ├─┬DELETE
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ └─┬PATCH
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/comments/{comment_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments/{comment_id}/replies
  │ └─┬POST
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ ├─┬DELETE
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ └─┬PATCH
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}/reactions
  │ ├─┬GET
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ └─┬POST
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions
  │ ├─┬GET
  │ │ └─┬Parameters
  │ │   └─┬Schema
  │ │     └──[➖] format (223381:17)❌
  │ └─┬POST
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}/reactions/{reaction_id}
  │ └─┬DELETE
  │   └─┬Parameters
  │     └─┬Schema
  │       └──[➖] format (223381:17)❌
  └─┬/repos/{owner}/{repo}/pulls/comments/{comment_id}
    ├─┬GET
    │ └─┬Parameters
    │   └─┬Schema
    │     └──[➖] format (223381:17)❌
    ├─┬DELETE
    │ └─┬Parameters
    │   └─┬Schema
    │     └──[➖] format (223381:17)❌
    └─┬PATCH
      └─┬Parameters
        └─┬Schema
          └──[➖] format (223381:17)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 22            | 22               |

Date: 09/12/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _22_ out of _22_
- **Removals**: _22_
- **Breaking Removals**: _22_

ERROR: breaking changes discovered