[GitHubEnterprise-3.15] Update to 1.1.4-35aa0c27af04ff30389730ec172a99ab from 1.1.4-e316db5b358f9d3f79c9ccc4f90f9cb6 Detected Schema changes:
```
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/issues
│ │ ├─┬GET
│ │ │ └──[➖] parameters (33109:15)❌
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (33257:17)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}
│ │ └─┬PATCH
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └──[➖] properties (33873:17)❌
│ ├─┬/orgs/{org}/properties/schema
│ │ └─┬PATCH
│ │   └──[🔀] description (15949:20)
│ └─┬/orgs/{org}/issues
│   └─┬GET
│     └──[➖] parameters (13516:15)❌
└─┬Components
  ├──[➖] schemas (71629:7)❌
  ├─┬app-permissions
  │ └─┬dependabot_secrets
  │   └──[🔀] description (67399:24)
  ├─┬webhook-issues-closed
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (117281:15)❌
  ├─┬webhook-issues-demilestoned
  │ └─┬issue
  │   └──[➖] properties (119370:13)❌
  ├─┬webhook-issues-labeled
  │ └─┬issue
  │   └──[➖] properties (121303:13)❌
  ├─┬webhooks_issue_2
  │ └──[➖] properties (96173:9)❌
  ├─┬custom-property-set-payload
  │ └──[➖] properties (76533:9)❌
  ├─┬webhook-issues-milestoned
  │ └─┬issue
  │   └──[➖] properties (123261:13)❌
  ├─┬webhook-issue-comment-edited
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (116036:15)❌
  ├─┬webhooks_issue
  │ └──[➖] properties (95091:9)❌
  ├─┬webhook-issues-reopened
  │ └─┬issue
  │   └──[➖] properties (126720:13)❌
  ├─┬webhook-issues-unlocked
  │ └─┬issue
  │   └──[➖] properties (129110:13)❌
  ├─┬webhook-issue-comment-created
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (113603:15)❌
  ├─┬webhook-issues-deleted
  │ └─┬issue
  │   └──[➖] properties (118385:13)❌
  ├─┬webhook-issues-locked
  │ └─┬issue
  │   └──[➖] properties (122296:13)❌
  ├─┬webhook-issues-edited
  │ └─┬issue
  │   └──[➖] properties (120334:13)❌
  ├─┬issue
  │ └──[➖] properties (71929:9)❌
  ├─┬webhook-issue-comment-deleted
  │ └─┬issue
  │   └─┬ALLOF
  │     └──[➖] properties (114816:15)❌
  ├─┬issue-search-result-item
  │ └──[➖] properties (90264:9)❌
  ├─┬webhook-issues-opened
  │ └─┬issue
  │   └──[➖] properties (125627:13)❌
  └─┬webhook-issues-transferred
    └─┬changes
      └─┬new_issue
        └──[➖] properties (127580:17)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 5             | 4                |
| components       | 21            | 24               |

Date: 03/18/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _28_ out of _26_
- **Modifications**: _2_
- **Removals**: _24_
- **Breaking Removals**: _24_

ERROR: breaking changes discovered