[GitHub] Update to 1.1.4-9fb2901e192ade3e8ccc32f59e517598 from 1.1.4-c03183a8896046a8cd867a6cab6116d9 Detected Schema changes:
```
├─┬Paths
│ └──[➖] path (4037:3)❌
└─┬Components
  ├──[➖] parameters (226090:7)❌
  ├──[➖] parameters (226098:7)❌
  ├──[➖] parameters (226082:7)❌
  ├──[➖] parameters (226073:7)❌
  ├──[➖] responses (227214:7)❌
  ├──[➖] examples (203748:7)❌
  └──[➖] schemas (72328:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 1                |
| components       | 7             | 7                |

Date: 11/23/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _8_ out of _8_
- **Removals**: _8_
- **Breaking Removals**: _8_

ERROR: breaking changes discovered