[GitHub] Update to 1.1.4-f1a89aa5fb6ef3d7a6d77044c06b8756 from 1.1.4-5758ce6a93c789209abf3a01ab532091 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (10205:3)❌
│ ├──[➖] path (10053:3)❌
│ ├──[➖] path (10020:3)❌
│ ├──[➖] path (10237:3)❌
│ ├──[➖] path (10112:3)❌
│ ├──[➖] path (10082:3)❌
│ ├──[➖] path (10144:3)❌
│ ├──[➖] path (10174:3)❌
│ ├──[➖] path (9985:3)❌
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ ├─┬GET
│ │ │ └──[🔀] description (48006:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (48038:20)
│ ├─┬/users/{username}/packages
│ │ └─┬GET
│ │   └──[🔀] description (47801:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └──[➕] parameters (9868:15)❌
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └─┬POST
│ │   └──[🔀] description (12007:20)
│ ├─┬/user/packages/{package_type}/{package_name}/restore
│ │ └─┬POST
│ │   └──[🔀] description (45860:20)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ ├─┬GET
│ │ │ └──[🔀] description (11941:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (11973:20)
│ ├─┬/user/packages/{package_type}/{package_name}/versions/{package_version_id}
│ │ ├─┬GET
│ │ │ └──[🔀] description (45951:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (45982:20)
│ ├─┬/orgs/{org}/packages
│ │ └─┬GET
│ │   └──[🔀] description (11712:20)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └──[🔀] description (11889:20)
│ ├─┬/user/packages/{package_type}/{package_name}
│ │ ├─┬GET
│ │ │ └──[🔀] description (45800:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (45830:20)
│ ├─┬/orgs/{org}/personal-access-token-requests
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (206120:7)
│ ├─┬/orgs/{org}/personal-access-tokens
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (206154:7)
│ ├─┬/user/packages
│ │ └─┬GET
│ │   └──[🔀] description (45747:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/restore
│ │ └─┬POST
│ │   └──[🔀] description (47923:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └──[🔀] description (47966:20)
│ ├─┬/app/hook/deliveries
│ │ └─┬GET
│ │   └──[➕] parameters (508:15)❌
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └──[➕] parameters (30830:15)❌
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}/restore
│ │ └─┬POST
│ │   └──[🔀] description (11846:20)
│ ├─┬/user/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│ │ └─┬POST
│ │   └──[🔀] description (46015:20)
│ ├─┬/orgs/{org}/packages/{package_type}/{package_name}
│ │ ├─┬GET
│ │ │ └──[🔀] description (11782:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (11813:20)
│ ├─┬/user/packages/{package_type}/{package_name}/versions
│ │ └─┬GET
│ │   └──[🔀] description (45900:20)
│ ├─┬/users/{username}/packages/{package_type}/{package_name}
│ │ ├─┬GET
│ │ │ └──[🔀] description (47859:20)
│ │ └─┬DELETE
│ │   └──[🔀] description (47890:20)
│ └─┬/users/{username}/packages/{package_type}/{package_name}/versions/{package_version_id}/restore
│   └─┬POST
│     └──[🔀] description (48072:20)
└─┬Components
  ├──[➖] parameters (225782:7)❌
  ├──[➖] parameters (225849:7)❌
  ├──[➖] parameters (225809:7)❌
  ├──[➖] parameters (225795:7)❌
  ├──[➖] parameters (225833:7)❌
  ├──[➖] parameters (225856:7)❌
  ├──[➖] parameters (225816:7)❌
  ├──[➖] parameters (225802:7)❌
  ├──[➖] examples (205457:7)❌
  ├──[➖] examples (205467:7)❌
  ├──[➖] examples (205491:7)❌
  ├──[➖] examples (205449:7)❌
  ├──[➖] examples (205471:7)❌
  ├──[➖] schemas (74238:7)❌
  ├──[➖] schemas (74210:7)❌
  ├──[➖] schemas (74291:7)❌
  ├──[➖] schemas (74276:7)❌
  ├──[➖] schemas (74262:7)❌
  ├─┬organization-programmatic-access-grant
  │ ├──[➖] required (74997:9)❌
  │ ├──[➖] properties (74969:9)❌
  │ └─┬id
  │   └──[🔀] description (74541:24)
  ├─┬personal-access-token-request
  │ ├──[➖] required (96964:9)❌
  │ └──[➖] properties (96933:9)❌
  ├─┬organization-programmatic-access-grant-request
  │ ├──[➖] required (74921:9)❌
  │ └──[➖] properties (74892:9)❌
  └─┬check-suite
    └─┬id
      └──[➖] format (81351:19)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 38            | 12               |
| components       | 26            | 25               |

Date: 11/01/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _37_ out of _64_
- **Modifications**: _27_
- **Removals**: _34_
- **Additions**: _3_
- **Breaking Removals**: _34_
- **Breaking Additions**: _3_

ERROR: breaking changes discovered