[GitHubEnterprise-3.14] Update to 1.1.4-c6bac21f127e4771c961c4af72e21fc4 from 1.1.4-d5ac2a68d76d323d5182cd11d4daf614 Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│   └─┬PATCH
│     ├─┬Responses
│     │ └──[➖] codes (218127:7)❌
│     └─┬Requestbody
│       └─┬application/json
│         ├─┬Schema
│         │ └──[➖] properties (25913:17)❌
│         └─┬default
│           ├──[🔀] value (25918:19)
│           ├──[🔀] value (25918:19)
│           ├──[🔀] value (25918:19)
│           └──[➖] value (25920:19)
└─┬Components
  ├──[➖] schemas (92033:7)❌
  ├──[➖] schemas (81652:7)❌
  ├──[➖] schemas (91995:7)❌
  ├──[➕] schemas (92025:7)
  ├──[➕] schemas (91987:7)
  └─┬exemption-request
    ├─┬metadata
    │ └─┬ONEOF
    │   └──[🔀] $ref (92025:14)❌
    └─┬exemption_request_data
      └─┬ONEOF
        └──[🔀] $ref (91987:14)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 6             | 2                |
| components       | 7             | 5                |

Date: 03/08/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _7_ out of _13_
- **Modifications**: _5_
- **Removals**: _6_
- **Additions**: _2_
- **Breaking Removals**: _5_
- **Breaking Modifications**: _2_

ERROR: breaking changes discovered