[GitHubAE] Update to 1.1.4-4516e4506b1725b6dedcb395a7795d46 from 1.1.4-cf31a7400788c7bef478bddc6524b440 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       ├─┬Schema
│ │       │ └──[-] properties (19079:17)❌
│ │       └─┬default
│ │         ├──[M] value (19106:19)
│ │         ├──[M] value (19106:19)
│ │         └──[-] value (19107:19)
│ └─┬/orgs/{org}/migrations
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬exclude
│             └──[M] description (7631:32)
├──ping
└─┬Components
  ├──[-] schemas (58776:7)❌
  ├─┬webhook-check-suite-requested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (68652:28)
  ├─┬webhook-code-scanning-alert-fixed
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (70343:28)
  ├─┬webhook-code-scanning-alert-appeared-in-branch
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (69578:28)
  ├─┬webhook-check-suite-completed
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (68038:28)
  ├─┬webhook-code-scanning-alert-closed-by-user
  │ └─┬alert
  │   └─┬dismissed_reason
  │     └──[M] description (69836:28)
  ├─┬webhook-check-suite-rerequested
  │ └─┬check_suite
  │   └─┬conclusion
  │     └──[M] description (69259:28)
  ├─┬full-repository
  │ └──[+] required (54451:9)❌
  └─┬webhook-deployment-status-created
    └─┬check_run
      └─┬conclusion
        └──[M] description (75150:28)

Date: 10/05/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 1
components       | 9             | 2
❌  3 Breaking changes out of 14
INFO: Modifications: 10
INFO: Removals: 3
INFO: Additions: 1
INFO: Breaking Removals: 2
INFO: Breaking Additions: 1

ERROR: breaking changes discovered