[GitHubEnterprise-3.13] Update to 1.1.4-65c7d90809c912f318fd98e5a759353c from 1.1.4-c3eeb28f55a8ddf476a0103d39889bfa Detected Schema changes:
```
├─┬Paths
│ ├─┬/zen
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       ├──[➕] content (47367:15)
│ │       └──[➖] content (47368:15)❌
│ ├─┬/search/issues
│ │ └─┬GET
│ │   └──[➖] parameters (216042:13)❌
│ └─┬/repos/{owner}/{repo}/dependency-graph/compare/{basehead}
│   └─┬GET
│     └─┬Responses
│       └─┬403
│         └──[🔀] description (216330:20)
└─┬Components
  └──[➖] parameters (216042:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 2                |
| components       | 1             | 1                |

Date: 03/01/25 | Commit: Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _5_
- **Modifications**: _1_
- **Removals**: _3_
- **Additions**: _1_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered