[GitHubEnterprise-3.9] Update to 1.1.4-d1cc219023169a82457fb797e7d85531 from 1.1.4-93fcb79e417a73083950e021c1a1da31 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (14763:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──Parameters
│ └─┬/repos/{owner}/{repo}/code-scanning/sarifs
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           ├──[-] additionalProperties (22871:37)❌
│           └─┬ref
│             └──[M] $ref (63525:13)❌
└─┬Components
  ├──[-] schemas (72847:7)❌
  └─┬code-scanning-ref
    └──[M] description (63526:20)

Date: 11/15/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 2
components       | 2             | 1

❌  3 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered