[GitHubAE] Update to 1.1.4-4c5e05b63b9b55649d3117efa99d0e48 from 1.1.4-dabccf38624f2b1c7063062e59b13705 Detected Schema changes:
├─┬Paths
│ ├─┬/users/{username}/repos
│ │ └─┬GET
│ │   └──[M] description (32311:20)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (196307:7)
│ ├─┬/repos/{template_owner}/{template_repo}/generate
│ │ └─┬POST
│ │   └──[M] description (27809:20)
│ ├─┬/orgs/{org}/repos
│ │ └─┬POST
│ │   └──[M] description (8166:20)
│ └─┬/user/repos
│   └─┬POST
│     └──[M] description (31249:20)
└─┬Components
  ├──[-] schemas (63581:7)❌
  ├──[-] schemas (63566:7)❌
  ├──[-] schemas (63552:7)❌
  ├──[-] schemas (63596:7)❌
  ├──[-] schemas (63498:7)❌
  ├──[-] schemas (63538:7)❌
  ├──[-] schemas (63524:7)❌
  ├──[-] schemas (63511:7)❌
  ├─┬minimal-repository
  │ └─┬size
  │   └──[M] description (50978:24)
  ├─┬repository-webhooks
  │ └─┬size
  │   └──[M] description (65534:24)
  ├─┬repository
  │ └─┬size
  │   └──[M] description (47860:24)
  ├─┬full-repository
  │ └─┬size
  │   └──[M] description (52731:24)
  ├─┬secret-scanning-location
  │ ├─┬type
  │ │ ├──[-] enum (63621:13)❌
  │ │ ├──[-] enum (63622:13)❌
  │ │ ├──[-] enum (63626:13)❌
  │ │ ├──[-] enum (63627:13)❌
  │ │ ├──[-] enum (63620:13)❌
  │ │ ├──[-] enum (63623:13)❌
  │ │ ├──[-] enum (63624:13)❌
  │ │ ├──[-] enum (63625:13)❌
  │ │ └──[M] description (63502:24)
  │ └─┬details
  │   ├──[-] oneOf (63581:7)❌
  │   ├──[-] oneOf (63409:7)❌
  │   ├──[-] oneOf (63485:7)❌
  │   ├──[-] oneOf (63511:7)❌
  │   ├──[-] oneOf (63459:7)❌
  │   ├──[-] oneOf (63552:7)❌
  │   ├──[-] oneOf (63566:7)❌
  │   ├──[-] oneOf (63524:7)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (63467:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (63404:20)❌
  │   ├─┬ONEOF
  │   │ └──[M] $ref (63480:20)❌
  │   └─┬ONEOF
  │     └──[M] $ref (63454:20)❌
  └─┬api-overview
    └─┬domains
      └──[-] properties (50700:13)❌

Date: 12/01/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 0
components       | 34            | 29

❌  29 Breaking changes out of 39
INFO: Modifications: 14
INFO: Removals: 25
INFO: Breaking Removals: 25
INFO: Breaking Modifications: 4

ERROR: breaking changes discovered