[GitHubEnterprise-3.8] Update to 1.1.4-66a4084e7d5da2718c022156a2c3bb03 from 1.1.4-eb41001f4408b1f5b925f27ed2823e43 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 8944b3                                                                                 SPEC: extracted 2 commits from history
├─┬Paths
│ ├─┬/users/{username}/received_events
│ │ └─┬GET
│ │   └──[M] description (40734:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (21516:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (21639:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│ │ └─┬GET
│ │   └──[M] description (21943:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ └─┬GET
│ │   └──[M] description (21417:20)
│ └─┬/repos/{owner}/{repo}/code-scanning/analyses
│   └─┬GET
│     └──[M] description (21559:20)
├─┬project-deleted
│ └─┬POST
│   ├──[M] summary (49849:16)
│   └──[M] description (49855:20)
├─┬project-column-moved
│ └─┬POST
│   ├──[M] summary (49697:16)
│   └──[M] description (49703:20)
├─┬project-column-deleted
│ └─┬POST
│   ├──[M] summary (49545:16)
│   └──[M] description (49551:20)
├─┬project-card-converted
│ └─┬POST
│   ├──[M] summary (49012:16)
│   └──[M] description (49018:20)
├─┬project-reopened
│ └─┬POST
│   ├──[M] summary (50001:16)
│   └──[M] description (50007:20)
├─┬security-advisory-published
│ └─┬POST
│   └──[M] summary (55103:16)
├─┬project-created
│ └─┬POST
│   ├──[M] summary (49773:16)
│   └──[M] description (49779:20)
├─┬project-card-edited
│ └─┬POST
│   ├──[M] summary (49240:16)
│   └──[M] description (49246:20)
├─┬security-advisory-withdrawn
│ └─┬POST
│   └──[M] summary (55248:16)
├─┬project-edited
│ └─┬POST
│   ├──[M] summary (49925:16)
│   └──[M] description (49931:20)
├─┬security-advisory-updated
│ └─┬POST
│   ├──[M] summary (55175:16)
│   └──[M] description (55179:20)
├─┬project-closed
│ └─┬POST
│   ├──[M] summary (49393:16)
│   └──[M] description (49399:20)
├─┬project-card-moved
│ └─┬POST
│   ├──[M] summary (49316:16)
│   └──[M] description (49322:20)
├─┬project-card-created
│ └─┬POST
│   ├──[M] summary (49088:16)
│   └──[M] description (49094:20)
├─┬project-column-edited
│ └─┬POST
│   ├──[M] summary (49621:16)
│   └──[M] description (49627:20)
├─┬project-column-created
│ └─┬POST
│   ├──[M] summary (49469:16)
│   └──[M] description (49475:20)
├─┬project-card-deleted
│ └─┬POST
│   ├──[M] summary (49164:16)
│   └──[M] description (49170:20)
└─┬Components
  ├─┬code-scanning-ref-full
  │ ├──[M] pattern (69884:16)❌
  │ └──[M] description (69881:20)
  ├─┬app-permissions
  │ ├──[-] properties (58208:9)❌
  │ ├──[-] properties (58222:9)❌
  │ ├──[-] properties (58446:9)❌
  │ ├──[-] properties (58453:9)❌
  │ ├──[-] properties (58460:9)❌
  │ ├──[-] properties (58467:9)❌
  │ ├──[-] properties (58474:9)❌
  │ ├──[-] properties (58369:9)❌
  │ ├──[-] properties (58481:9)❌
  │ └──[-] properties (58487:9)❌
  └─┬actions-workflow-access-to-repository
    └─┬access_level
      └──[M] description (67472:24)

Date: 12/08/23 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 6             | 0
webhooks         | 32            | 0
components       | 13            | 11

❌  11 Breaking changes out of 51
INFO: Modifications: 41
INFO: Removals: 10
INFO: Breaking Removals: 10
INFO: Breaking Modifications: 1

                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [59348:7]
ERROR: breaking changes discovered