[GitHubEnterprise-3.14] Update to 1.1.4-aeaedf4d332292bd7f909991602bd632 from 1.1.4-e6b97d7e63c1ce77438434e9c1074e81 Detected Schema changes:
```
├─┬Paths
│ ├─┬/enterprises/{enterprise}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           └──[➖] value (195776:9)
│ ├─┬/orgs/{org}/actions/runner-groups/{runner_group_id}/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (195668:9)
│ ├─┬/orgs/{org}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           └──[➖] value (195776:9)
│ ├─┬/repos/{owner}/{repo}/pages/deployments
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬default
│ │         └──[➕] value (35192:19)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           ├──[🔀] value (195767:9)
│ │           └──[➖] value (195776:9)
│ ├─┬/enterprises/{enterprise}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (218017:7)❌
│ ├─┬/enterprises/{enterprise}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (195668:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners/generate-jitconfig
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[➖] codes (218017:7)❌
│ ├─┬/orgs/{org}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (195668:9)
│ ├─┬/enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (195668:9)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (195668:9)
│ └─┬/orgs/{org}/actions/runners/generate-jitconfig
│   └─┬POST
│     └─┬Responses
│       └──[➖] codes (218017:7)❌
└─┬Components
  └─┬runner
    └──[➖] properties (69585:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 27            | 3                |
| components       | 1             | 1                |

Date: 02/06/25 | Commit: New: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml

- ❌ **BREAKING Changes**: _4_ out of _28_
- **Modifications**: _20_
- **Removals**: _7_
- **Additions**: _1_
- **Breaking Removals**: _4_

ERROR: breaking changes discovered