[GitHubEnterprise-3.15] Update to 1.1.4-dafc4bb4ca8269335f6c4492394f88df from 1.1.4-a52c4c09b475fc1c0194c7e656ee966d Detected Schema changes:
```
└─┬Components
  ├──[➖] schemas (92426:7)❌
  ├──[➖] schemas (92388:7)❌
  ├─┬exemption-request
  │ ├─┬metadata
  │ │ └──[➖] oneOf (92426:7)❌
  │ ├─┬number
  │ │ └──[🔀] type (92442:17)❌
  │ ├─┬exemption_request_data
  │ │ └──[➖] oneOf (92388:7)❌
  │ └─┬request_type
  │   └──[➖] enum (92501:13)❌
  └─┬webhook-release-edited
    └─┬changes
      └──[➖] properties (184103:13)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| components       | 7             | 7                |

Date: 03/04/25 | Commit: Original: etc/specs/GitHubEnterprise-3.15/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.15/previous.spec.yaml,

- ❌ **BREAKING Changes**: _7_ out of _7_
- **Modifications**: _1_
- **Removals**: _6_
- **Breaking Removals**: _6_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered