[GitHub] Update to 1.1.4-c03183a8896046a8cd867a6cab6116d9 from 1.1.4-7714c88ff6c09a4c649c225f5b2ccf5c Detected Schema changes:
```
├─┬Paths
│ ├─┬/orgs/{org}/insights/api/summary-stats/{actor_type}/{actor_id}
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (226088:20)
│ │   └─┬Parameters
│ │     ├──[🔀] description (226095:20)
│ │     └──[🔀] required (226097:17)❌
│ ├─┬/orgs/{org}/insights/api/summary-stats
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ ├──[🔀] description (226095:20)
│ │   │ └──[🔀] required (226097:17)❌
│ │   └─┬Parameters
│ │     └──[🔀] description (226088:20)
│ ├─┬/orgs/{org}/insights/api/time-stats/users/{user_id}
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (226088:20)
│ │   └─┬Parameters
│ │     ├──[🔀] description (226095:20)
│ │     └──[🔀] required (226097:17)❌
│ ├─┬/orgs/{org}/insights/api/subject-stats
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (226088:20)
│ │   └─┬Parameters
│ │     ├──[🔀] description (226095:20)
│ │     └──[🔀] required (226097:17)❌
│ ├─┬/orgs/{org}/insights/api/time-stats/{actor_type}/{actor_id}
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (226088:20)
│ │   └─┬Parameters
│ │     ├──[🔀] description (226095:20)
│ │     └──[🔀] required (226097:17)❌
│ ├─┬/orgs/{org}/insights/api/summary-stats/users/{user_id}
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ ├──[🔀] description (226095:20)
│ │   │ └──[🔀] required (226097:17)❌
│ │   └─┬Parameters
│ │     └──[🔀] description (226088:20)
│ ├─┬/orgs/{org}/insights/api/user-stats/{user_id}
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (226088:20)
│ │   └─┬Parameters
│ │     ├──[🔀] description (226095:20)
│ │     └──[🔀] required (226097:17)❌
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[🔀] value (219821:7)
│ ├─┬/orgs/{org}/insights/api/time-stats
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ └──[🔀] description (226088:20)
│ │   └─┬Parameters
│ │     ├──[🔀] description (226095:20)
│ │     └──[🔀] required (226097:17)❌
│ ├─┬/orgs/{org}/insights/api/route-stats/{actor_type}/{actor_id}
│ │ └─┬GET
│ │   ├─┬Parameters
│ │   │ ├──[🔀] description (226095:20)
│ │   │ └──[🔀] required (226097:17)❌
│ │   └─┬Parameters
│ │     └──[🔀] description (226088:20)
│ └─┬/repos/{owner}/{repo}/releases
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬make_latest
│             └──[🔀] default (37740:28)❌
├─┬custom-property-updated
│ └─┬POST
│   └─┬Extensions
│     └──[🔀] x-github (50474:9)
├─┬custom-property-created
│ └─┬POST
│   └─┬Extensions
│     └──[🔀] x-github (50344:9)
├─┬custom-property-deleted
│ └─┬POST
│   └─┬Extensions
│     └──[🔀] x-github (50409:9)
└─┬Components
  ├─┬secret-scanning-location-pull-request-title
  │ └─┬pull_request_title_url
  │   └──[🔀] examples (89082:13)
  ├─┬copilot-dotcom-chat
  │ └─┬models
  │   └─┬Schema
  │     └─┬name
  │       └──[🔀] description (69111:30)
  ├─┬secret-scanning-location-pull-request-body
  │ └─┬pull_request_body_url
  │   └──[🔀] examples (89096:13)
  ├─┬copilot-ide-code-completions
  │ └─┬editors
  │   └─┬Schema
  │     └─┬models
  │       └─┬Schema
  │         └─┬name
  │           └──[🔀] description (68979:36)
  ├─┬copilot-ide-chat
  │ └─┬editors
  │   └─┬Schema
  │     └─┬models
  │       └─┬Schema
  │         └─┬name
  │           └──[🔀] description (69064:36)
  └─┬copilot-dotcom-pull-requests
    └─┬repositories
      └─┬Schema
        └─┬models
          └─┬Schema
            └─┬name
              └──[🔀] description (69162:36)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 29            | 10               |
| webhooks         | 3             | 0                |
| components       | 6             | 0                |

Date: 11/20/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _10_ out of _38_
- **Modifications**: _38_
- **Breaking Modifications**: _10_

ERROR: breaking changes discovered