[GitHub] Update to 1.1.4-ed5550c2efb9457d295e9fdc8af6d2c7 from 1.1.4-d934eed2382f2e3ae89ee32d3f556f88 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 44329c                                                                                 SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [62936:7]
└─┬Paths
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
  │ └─┬POST
  │   └──[M] description (21396:20)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
  │ └─┬GET
  │   └──[M] description (23928:20)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
  │ └─┬GET
  │   └──[M] description (21336:20)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
  │ └─┬POST
  │   └──[M] description (21134:20)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
  │ └─┬GET
  │   └──[M] description (23861:20)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
  │ ├─┬GET
  │ │ └──[M] description (20801:20)
  │ └─┬PATCH
  │   └──[M] description (20832:20)
  ├─┬/notifications/threads/{thread_id}
  │ └──[-] delete (3391:7)❌
  ├─┬/repos/{owner}/{repo}/check-suites
  │ └─┬POST
  │   └──[M] description (21183:20)
  ├─┬/feeds
  │ └─┬GET
  │   └──[M] description (1578:20)
  ├─┬/repos/{owner}/{repo}/releases/{release_id}
  │ └─┬GET
  │   ├──[M] description (34218:20)
  │   └─┬Responses
  │     └─┬200
  │       └──[M] description (34232:24)
  ├─┬/repos/{owner}/{repo}/check-suites/preferences
  │ └─┬PATCH
  │   └──[M] description (21239:20)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
  │ └─┬GET
  │   └──[M] description (21094:20)
  ├─┬/repos/{owner}/{repo}/releases/{release_id}/assets
  │ └─┬POST
  │   └──[M] description (34399:20)
  ├─┬/repos/{owner}/{repo}/check-runs
  │ └─┬POST
  │   └──[M] description (20499:20)
  └─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
    └─┬GET
      └──[M] description (21304:20)

Date: 12/20/23 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 17            | 1

❌  1 Breaking changes out of 17
INFO: Modifications: 16
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered