[GitHubEnterprise-3.13] Update to 1.1.4-71747b16e45e0f2a54b8e1ca561b75d5 from 1.1.4-8985016ac4b27cc23057fb31dee10264 Detected Schema changes:
```
├─┬Paths
│ └─┬/repos/{owner}/{repo}/dependabot/alerts/{alert_number}
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             ├──[🔀] value (204847:9)
│             ├──[🔀] value (204847:9)
│             ├──[🔀] value (204847:9)
│             ├──[🔀] value (204847:9)
│             ├──[🔀] value (204847:9)
│             ├──[🔀] value (204847:9)
│             ├──[🔀] value (204847:9)
│             ├──[➕] value (204847:9)
│             ├──[➕] value (204847:9)
│             ├──[➕] value (204847:9)
│             ├──[➕] value (204847:9)
│             └──[➕] value (204847:9)
└─┬Components
  ├──[➖] schemas (66445:7)❌
  └─┬global-advisory
    └─┬epss
      └──[🔀] $ref (66634:11)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 12            | 0                |
| components       | 2             | 2                |

Date: 01/25/25 | Commit: New: etc/specs/GitHubEnterprise-3.13/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.13/current.spec.yaml

- ❌ **BREAKING Changes**: _2_ out of _14_
- **Modifications**: _8_
- **Removals**: _1_
- **Additions**: _5_
- **Breaking Removals**: _1_
- **Breaking Modifications**: _1_

ERROR: breaking changes discovered