[GitHub] Update to 1.1.4-2fa68ef1401ab1f8ecec407bb7c5d77b from 1.1.4-529209138ca3f128f373739100dbd53c Detected Schema changes:
```
└─┬Paths
  ├─┬/orgs/{org}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (227939:20)
  │     └─┬Schema
  │       └──[➖] enum (227953:11)❌
  ├─┬/enterprises/{enterprise}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (227939:20)
  │     └─┬Schema
  │       └──[➖] enum (227953:11)❌
  ├─┬/users/{username}
  │ └─┬GET
  │   └──[🔀] description (48641:20)
  ├─┬/repos/{owner}/{repo}/dependabot/alerts
  │ └─┬GET
  │   └─┬Parameters
  │     ├──[🔀] description (227939:20)
  │     └─┬Schema
  │       └──[➖] enum (227953:11)❌
  └─┬/user/{account_id}
    └─┬GET
      └──[🔀] description (48558:20)

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 8             | 3                |

Date: 01/16/25 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _3_ out of _8_
- **Modifications**: _5_
- **Removals**: _3_
- **Breaking Removals**: _3_

ERROR: breaking changes discovered