[GitHubEnterprise-3.9] Update to 1.1.4 (hash: 10f013d285501dda982ff5f8a215c603current=36074b1453fb0e64ca7f1dc80447feef) from 1.1.4 (hash: ) Detected Schema changes:
├─┬Paths
│ ├─┬/repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (35817:20)
│ ├─┬/repos/{owner}/{repo}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (25427:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ ├─┬GET
│ │ │ └──[-] description (15375:20)
│ │ └─┬DELETE
│ │   └──[-] description (15469:20)
│ ├─┬/user/memberships/orgs/{org}
│ │ ├─┬GET
│ │ │ └──[-] description (40625:20)
│ │ └─┬PATCH
│ │   └──[-] description (40659:20)
│ ├─┬/projects/columns/{column_id}
│ │ ├─┬GET
│ │ │ └──[-] description (15620:20)
│ │ └─┬DELETE
│ │   └──[-] description (15705:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
│ │ └─┬GET
│ │   └──[-] description (30890:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
│ │ └─┬GET
│ │   └──[-] description (30001:20)
│ ├─┬/projects/{project_id}/columns
│ │ ├─┬GET
│ │ │ └──[-] description (16308:20)
│ │ └─┬POST
│ │   └──[-] description (16347:20)
│ ├─┬/user/memberships/orgs
│ │ └─┬GET
│ │   └──[-] description (40574:20)
│ ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
│ │ └─┬GET
│ │   └──[-] description (28966:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (9392:20)
│ ├─┬/repos/{owner}/{repo}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (30189:20)
│ │ └─┬POST
│ │   └──[-] description (30225:20)
│ ├─┬/orgs/{org}/public_members/{username}
│ │ ├─┬GET
│ │ │ └──[-] description (13141:20)
│ │ └─┬DELETE
│ │   └──[-] description (13188:20)
│ ├─┬/projects/columns/{column_id}/cards
│ │ └─┬GET
│ │   └──[-] description (15731:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[-] codes (220805:7)❌
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
│ │ ├─┬GET
│ │ │ └──[-] description (30776:20)
│ │ └─┬DELETE
│ │   └──[-] description (30866:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
│ │ └─┬GET
│ │   └──[-] description (29439:20)
│ ├─┬/orgs/{org}/dependabot/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (10694:20)
│ ├─┬/repos/{owner}/{repo}/labels/{name}
│ │ ├─┬GET
│ │ │ └──[-] description (30294:20)
│ │ ├─┬DELETE
│ │ │ └──[-] description (30388:20)
│ │ └─┬PATCH
│ │   └──[-] description (30328:20)
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └─┬GET
│ │   ├──[-] description (35269:20)
│ │   └─┬Responses
│ │     └──[-] codes (220793:7)❌
│ ├─┬/users/{username}/projects
│ │ └─┬GET
│ │   └──[-] description (43235:20)
│ ├─┬/repos/{owner}/{repo}/issues/events
│ │ └─┬GET
│ │   └──[-] description (28929:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (29477:20)
│ │ ├─┬POST
│ │ │ └──[-] description (29518:20)
│ │ └─┬DELETE
│ │   └──[-] description (29698:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (19019:20)
│ └─┬/repos/{owner}/{repo}/milestones
│   ├─┬GET
│   │ └──[-] description (30638:20)
│   └─┬POST
│     └──[-] description (30705:20)
└─┬Components
  └─┬api-overview
    └──[-] properties (66290:9)❌

Date: 06/03/23 | Commit: New: etc/specs/GitHubEnterprise-3.9/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.9/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 38            | 2
components       | 1             | 1
❌ 3 Breaking changes out of 39

ERROR: breaking changes discovered