[GitHubEnterprise-3.14] Update to 1.1.4-1ea96b0756988647879c8bead15393bf from 1.1.4-4b8ff7792783a0592e25008fb6c20f98 Detected Schema changes:
```
├─┬Paths
│ └─┬/orgs/{org}
│   └─┬GET
│     └──[🔀] description (8452:20)
└─┬Components
  ├──[➖] schemas (76612:7)❌
  └─┬repository-rule-params-required-reviewer-configuration
    ├──[➕] required (76635:9)❌
    ├──[➕] properties (76629:9)
    └──[➖] properties (76645:9)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 1             | 0                |
| components       | 4             | 3                |

Date: 02/27/25 | Commit: Original: etc/specs/GitHubEnterprise-3.14/current.spec.yaml, Modified: etc/specs/GitHubEnterprise-3.14/previous.spec.yaml,

- ❌ **BREAKING Changes**: _3_ out of _5_
- **Modifications**: _1_
- **Removals**: _2_
- **Additions**: _2_
- **Breaking Removals**: _2_
- **Breaking Additions**: _1_

ERROR: breaking changes discovered