[GitHub] Update to 1.1.4-79bfc552fc9431ae453024109bc3424d from 1.1.4-9bdf0d87b61dcb75ec907d0344bd6b72 Detected Schema changes:
```
├─┬Paths
│ ├──[➖] path (23861:3)❌
│ ├─┬/repos/{owner}/{repo}/rulesets
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬target
│ │           └──[➖] default (37283:28)❌
│ ├─┬/repos/{owner}/{repo}/readme
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[➖] codes (223903:7)❌
│ └─┬/orgs/{org}/rulesets
│   └─┬POST
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬target
│             └──[➖] default (12593:28)❌
└─┬Components
  ├──[➖] examples (209347:7)❌
  └──[➖] schemas (79950:7)❌

```

| Document Element | Total Changes | Breaking Changes |
|------------------|---------------|------------------|
| paths            | 4             | 4                |
| components       | 2             | 2                |

Date: 08/16/24 | Commit: New: etc/specs/GitHub/previous.spec.yaml, Original: etc/specs/GitHub/current.spec.yaml

- ❌ **BREAKING Changes**: _6_ out of _6_
- **Removals**: _6_
- **Breaking Removals**: _6_

ERROR: breaking changes discovered