[GitHubEnterprise-3.11] Update to 1.1.4-c130f6d882ed81d2bb9f0a52fabb02d9 from 1.1.4-3be240f188d592ffe6c58927a2a011e4 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 33518b                                                                                 SPEC: extracted 2 commits from history                                                                                 DONE: completed
WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [64885:7]

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/default-setup
│ │ ├─┬GET
│ │ │ └──[M] description (24215:20)
│ │ └─┬PATCH
│ │   └──[M] description (24251:20)
│ ├─┬/users/{username}/received_events
│ │ └─┬GET
│ │   └──[M] description (44741:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──[M] description (23907:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses/{analysis_id}
│ │ └─┬GET
│ │   └──[M] description (24030:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}
│ │ └─┬GET
│ │   └──[M] description (23808:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/analyses
│ │ └─┬GET
│ │   └──[M] description (23950:20)
│ └─┬/repos/{owner}/{repo}/code-scanning/sarifs/{sarif_id}
│   └─┬GET
│     └──[M] description (24430:20)
├─┬project-column-deleted
│ └─┬POST
│   ├──[M] summary (54204:16)
│   └──[M] description (54210:20)
├─┬security-advisory-withdrawn
│ └─┬POST
│   └──[M] summary (60491:16)
├─┬project-card-deleted
│ └─┬POST
│   ├──[M] summary (53823:16)
│   └──[M] description (53829:20)
├─┬project-reopened
│ └─┬POST
│   ├──[M] summary (54660:16)
│   └──[M] description (54666:20)
├─┬project-column-edited
│ └─┬POST
│   ├──[M] summary (54280:16)
│   └──[M] description (54286:20)
├─┬project-column-moved
│ └─┬POST
│   ├──[M] summary (54356:16)
│   └──[M] description (54362:20)
├─┬project-edited
│ └─┬POST
│   ├──[M] summary (54584:16)
│   └──[M] description (54590:20)
├─┬project-closed
│ └─┬POST
│   ├──[M] summary (54052:16)
│   └──[M] description (54058:20)
├─┬security-advisory-updated
│ └─┬POST
│   ├──[M] summary (60418:16)
│   └──[M] description (60422:20)
├─┬project-card-edited
│ └─┬POST
│   ├──[M] summary (53899:16)
│   └──[M] description (53905:20)
├─┬project-card-converted
│ └─┬POST
│   ├──[M] summary (53671:16)
│   └──[M] description (53677:20)
├─┬project-card-created
│ └─┬POST
│   ├──[M] summary (53747:16)
│   └──[M] description (53753:20)
├─┬project-card-moved
│ └─┬POST
│   ├──[M] summary (53975:16)
│   └──[M] description (53981:20)
├─┬security-advisory-published
│ └─┬POST
│   └──[M] summary (60346:16)
├─┬project-deleted
│ └─┬POST
│   ├──[M] summary (54508:16)
│   └──[M] description (54514:20)
├─┬project-created
│ └─┬POST
│   ├──[M] summary (54432:16)
│   └──[M] description (54438:20)
├─┬project-column-created
│ └─┬POST
│   ├──[M] summary (54128:16)
│   └──[M] description (54134:20)
└─┬Components
  ├─┬actions-workflow-access-to-repository
  │ └─┬access_level
  │   └──[M] description (74379:24)
  ├─┬org-ruleset-conditions
  │ └──[M] description (71864:20)
  ├─┬app-permissions
  │ ├──[-] properties (63453:9)❌
  │ ├──[-] properties (63467:9)❌
  │ ├──[-] properties (63698:9)❌
  │ ├──[-] properties (63705:9)❌
  │ ├──[-] properties (63712:9)❌
  │ ├──[-] properties (63719:9)❌
  │ ├──[-] properties (63726:9)❌
  │ ├──[-] properties (63621:9)❌
  │ ├──[-] properties (63733:9)❌
  │ └──[-] properties (63739:9)❌
  └─┬code-scanning-ref-full
    ├──[M] pattern (76941:16)❌
    └──[M] description (76938:20)

Date: 12/08/23 | Commit: New: etc/specs/GitHubEnterprise-3.11/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.11/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 8             | 0
webhooks         | 32            | 0
components       | 14            | 11

❌  11 Breaking changes out of 54
INFO: Modifications: 44
INFO: Removals: 10
INFO: Breaking Removals: 10
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered