[GitHubEnterprise-3.8] Update to 1.1.4-7cba10c0c2f8c46f83e2eb785b1234ac from 1.1.4-4addb1e2535529282967a529f6306fc3 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 807c5d
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬config
│ │           ├──[+] properties (26198:21)
│ │           └──[+] properties (26194:21)
│ └─┬/repos/{owner}/{repo}/hooks/{hook_id}
│   └─┬PATCH
│     └─┬Requestbody
│       └─┬application/json
│         └─┬Schema
│           └─┬config
│             └──[M] $ref (26310:19)❌
└─┬Components
  └─┬hook
    └─┬config
      └──[M] $ref (72577:11)❌

Date: 01/13/24 | Commit: New: etc/specs/GitHubEnterprise-3.8/previous.spec.yaml, Original: etc/specs/GitHubEnterprise-3.8/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 1
components       | 1             | 1

❌  2 Breaking changes out of 4
INFO: Modifications: 2
INFO: Additions: 2
INFO: Breaking Modifications: 2

ERROR: breaking changes discovered