[GitHubAE] Update to 1.1.4-f264cd8fc305b9584ace80883c429a95 from 1.1.4-685363466de14cc34165c665b088a065 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts/{alert_number}/instances
│ │ └─┬GET
│ │   └──Parameters
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └──[M] description (9881:20)
│ ├─┬/repos/{owner}/{repo}/code-scanning/sarifs
│ │ └─┬POST
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         ├──[-] additionalProperties (16690:37)❌
│ │         └─┬ref
│ │           └──[M] $ref (51847:13)❌
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──Parameters
│ └─┬/repos/{owner}/{repo}/code-scanning/analyses
│   └─┬GET
│     └──Parameters
├─┬ping
│ └──POST
└─┬Components
  ├──[-] schemas (56946:7)❌
  └─┬code-scanning-ref
    └──[M] description (51848:20)

Date: 11/15/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 2
components       | 2             | 1

❌  3 Breaking changes out of 5
INFO: Modifications: 3
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered